// Package api.rapidsign.v1 contains the canonical protobuf definitions for
// the RapidSign API served from `rapidsign.isaapi.com`. Under ADR-026 these
// protos are the source of truth for every generated SDK (Go, PHP,
// TypeScript) and the OpenAPI consumed by ReadMe.
//
// common.proto previously duplicated the cross-platform error model and
// scope enumeration; those types now live in `api/isa/v1/common.proto`
// (ProblemDetails, ErrorCode, Scope). Import that file wherever those
// types appear in message fields or RPC signatures.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/rapidsign/v1/common.proto

package rapidsignv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_rapidsign_v1_common_proto protoreflect.FileDescriptor

const file_api_rapidsign_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/rapidsign/v1/common.proto\x12\x10api.rapidsign.v1B\xe5\x01\n" +
	"\x14com.api.rapidsign.v1B\vCommonProtoP\x01ZVgithub.com/isa-sdk/sdk/rapidsign/api/rapidsign/v1;rapidsignv1\xa2\x02\x03ARX\xaa\x02\x17IsaSdk.RapidSign.Api.V1\xca\x02\x14Sah\\RapidSign\\Api\\V1\xe2\x02\x19Sah\\RapidSign\\Api\\V1\\Meta\xea\x02\x12Api::Rapidsign::V1b\x06proto3"

var file_api_rapidsign_v1_common_proto_goTypes = []any{}
var file_api_rapidsign_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_rapidsign_v1_common_proto_init() }
func file_api_rapidsign_v1_common_proto_init() {
	if File_api_rapidsign_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rapidsign_v1_common_proto_rawDesc), len(file_api_rapidsign_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_rapidsign_v1_common_proto_goTypes,
		DependencyIndexes: file_api_rapidsign_v1_common_proto_depIdxs,
	}.Build()
	File_api_rapidsign_v1_common_proto = out.File
	file_api_rapidsign_v1_common_proto_goTypes = nil
	file_api_rapidsign_v1_common_proto_depIdxs = nil
}
