// documents.proto defines the document-lifecycle surface for RapidSign
// served from `rapidsign.isaapi.com`. Per ADR-019 this surface is
// bearer-only and server-to-server; no CORS is intentionally exposed.
//
// Endpoint set covered here is the five operations already implemented
// in the rapidsign service (see internal/handler/handler.go). Reserved
// stubs (cancel, audit) and unimplemented legacy bridges
// (case-restoration, pdf-prefill/render, retrieve, replace-signid) are
// intentionally omitted from v1 until their semantics are finalised —
// they are tracked separately in #38.
//
// Scopes
//
//   - CreateDocument   → rapidsign:documents:write
//   - SignDocument     → rapidsign:documents:sign
//   - GetDocument      → rapidsign:documents:read
//   - DownloadDocument → rapidsign:documents:read
//   - NotifyDocument   → rapidsign:documents:notify

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/rapidsign/v1/documents.proto

package rapidsignv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentStatus tracks the lifecycle state of a document.
type DocumentStatus int32

const (
	// Default zero value. Never emitted by the server.
	DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED DocumentStatus = 0
	// Packet rendered and stored; awaiting signature(s).
	DocumentStatus_DOCUMENT_STATUS_PENDING DocumentStatus = 1
	// At least one signature captured.
	DocumentStatus_DOCUMENT_STATUS_SAVED DocumentStatus = 2
	// Signer-notification email accepted by the emailer.
	DocumentStatus_DOCUMENT_STATUS_NOTIFIED DocumentStatus = 3
)

// Enum value maps for DocumentStatus.
var (
	DocumentStatus_name = map[int32]string{
		0: "DOCUMENT_STATUS_UNSPECIFIED",
		1: "DOCUMENT_STATUS_PENDING",
		2: "DOCUMENT_STATUS_SAVED",
		3: "DOCUMENT_STATUS_NOTIFIED",
	}
	DocumentStatus_value = map[string]int32{
		"DOCUMENT_STATUS_UNSPECIFIED": 0,
		"DOCUMENT_STATUS_PENDING":     1,
		"DOCUMENT_STATUS_SAVED":       2,
		"DOCUMENT_STATUS_NOTIFIED":    3,
	}
)

func (x DocumentStatus) Enum() *DocumentStatus {
	p := new(DocumentStatus)
	*p = x
	return p
}

func (x DocumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rapidsign_v1_documents_proto_enumTypes[0].Descriptor()
}

func (DocumentStatus) Type() protoreflect.EnumType {
	return &file_api_rapidsign_v1_documents_proto_enumTypes[0]
}

func (x DocumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentStatus.Descriptor instead.
func (DocumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{0}
}

// PdfRenderSource references one PDF input the renderer must fetch,
// optionally pinned to an expected SHA-256 hash for integrity. URLs are
// fetched server-side; the caller never proxies binary content.
type PdfRenderSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully-qualified URL to fetch the source PDF from. Required.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Optional hex-encoded SHA-256 of the expected source bytes. When
	// present the renderer aborts with a validation error if the fetch
	// does not match.
	ExpectedHash  string `protobuf:"bytes,2,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfRenderSource) Reset() {
	*x = PdfRenderSource{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfRenderSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfRenderSource) ProtoMessage() {}

func (x *PdfRenderSource) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfRenderSource.ProtoReflect.Descriptor instead.
func (*PdfRenderSource) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{0}
}

func (x *PdfRenderSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PdfRenderSource) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

// CreateDocumentRequest is the body for POST /v1/documents.
//
// `data` is the templating bundle passed verbatim into the renderer;
// its shape is renderer-specific so it is typed as a free-form Struct.
// `expected_hashes` lets callers pin known sources by name (e.g. an
// integration that already computed the source SHA at upload time).
type CreateDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Originating session identifier; binds the document to a single
	// signing session for replay protection. Required.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Ordered list of PDF sources to fetch and merge into the packet.
	Packet []*PdfRenderSource `protobuf:"bytes,2,rep,name=packet,proto3" json:"packet,omitempty"`
	// Template bundle the renderer interpolates into the packet.
	Data *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// When true (default) the document may be signed remotely. When
	// false the renderer marks the packet as in-person only.
	RemoteAllowed bool `protobuf:"varint,4,opt,name=remote_allowed,json=remoteAllowed,proto3" json:"remote_allowed,omitempty"`
	// Pre-issued sign ids the renderer should reuse instead of minting
	// new ones. When empty the service mints ids per signer.
	SignIds []string `protobuf:"bytes,5,rep,name=sign_ids,json=signIds,proto3" json:"sign_ids,omitempty"`
	// Optional view-only id for read-only audit access to the packet.
	ViewOnlyId string `protobuf:"bytes,6,opt,name=view_only_id,json=viewOnlyId,proto3" json:"view_only_id,omitempty"`
	// User-agent of the signer's browser captured at render time, for
	// audit-trail provenance.
	UserAgent string `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// When true the renderer applies production policy (binding legal
	// text, watermark suppression). False keeps the rendered packet
	// labelled as non-production for compliance.
	IsProduction bool `protobuf:"varint,8,opt,name=is_production,json=isProduction,proto3" json:"is_production,omitempty"`
	// Legal text to embed beneath each signature block. Empty disables
	// the embed.
	BindingLegalText string `protobuf:"bytes,9,opt,name=binding_legal_text,json=bindingLegalText,proto3" json:"binding_legal_text,omitempty"`
	// Time-to-live duration applied to the stored packet. ISO-8601
	// duration string (e.g. `P30D`). Empty applies the service default.
	Ttl string `protobuf:"bytes,10,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Map from source URL → expected SHA-256 hex. Equivalent to
	// PdfRenderSource.expected_hash but keyed for callers that build
	// hashes out-of-band.
	ExpectedHashes map[string]string `protobuf:"bytes,11,rep,name=expected_hashes,json=expectedHashes,proto3" json:"expected_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDocumentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateDocumentRequest) GetPacket() []*PdfRenderSource {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *CreateDocumentRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateDocumentRequest) GetRemoteAllowed() bool {
	if x != nil {
		return x.RemoteAllowed
	}
	return false
}

func (x *CreateDocumentRequest) GetSignIds() []string {
	if x != nil {
		return x.SignIds
	}
	return nil
}

func (x *CreateDocumentRequest) GetViewOnlyId() string {
	if x != nil {
		return x.ViewOnlyId
	}
	return ""
}

func (x *CreateDocumentRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *CreateDocumentRequest) GetIsProduction() bool {
	if x != nil {
		return x.IsProduction
	}
	return false
}

func (x *CreateDocumentRequest) GetBindingLegalText() string {
	if x != nil {
		return x.BindingLegalText
	}
	return ""
}

func (x *CreateDocumentRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *CreateDocumentRequest) GetExpectedHashes() map[string]string {
	if x != nil {
		return x.ExpectedHashes
	}
	return nil
}

// CreateDocumentResponse is the success body for POST /v1/documents.
type CreateDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the rendered packet was persisted to storage. A false
	// value is never returned on a 2xx response — the renderer surfaces
	// a 5xx instead.
	PacketStored bool `protobuf:"varint,1,opt,name=packet_stored,json=packetStored,proto3" json:"packet_stored,omitempty"`
	// Map from rendered source URL → SHA-256 of the bytes actually
	// fetched and embedded. Always populated.
	Hashes        map[string]string `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentResponse) Reset() {
	*x = CreateDocumentResponse{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentResponse) ProtoMessage() {}

func (x *CreateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDocumentResponse) GetPacketStored() bool {
	if x != nil {
		return x.PacketStored
	}
	return false
}

func (x *CreateDocumentResponse) GetHashes() map[string]string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// SignDocumentRequest is the body for POST /v1/documents/{sign_id}/sign.
type SignDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sign id path parameter. Required.
	SignId string `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	// Originating session identifier; must match the session_id used
	// when the document was created.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Optional signing secret (one-time code) when the document was
	// created with a secret-protected sign_id.
	Secret string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	// Base64-encoded signature image bytes. Required.
	Signature string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Opaque signer metadata (browser fingerprint, ip, etc.) captured at
	// signing time, stored verbatim for the audit trail.
	UserMetadata  string `protobuf:"bytes,5,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignDocumentRequest) Reset() {
	*x = SignDocumentRequest{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDocumentRequest) ProtoMessage() {}

func (x *SignDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDocumentRequest.ProtoReflect.Descriptor instead.
func (*SignDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{3}
}

func (x *SignDocumentRequest) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *SignDocumentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignDocumentRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SignDocumentRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignDocumentRequest) GetUserMetadata() string {
	if x != nil {
		return x.UserMetadata
	}
	return ""
}

// SignDocumentResponse is the success body for POST /v1/documents/{sign_id}/sign.
type SignDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sign id that was signed. Echoed from the path.
	SignId string `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	// Lifecycle state after the signature was saved. Always `saved`
	// on a 2xx response.
	Status        DocumentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=api.rapidsign.v1.DocumentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignDocumentResponse) Reset() {
	*x = SignDocumentResponse{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDocumentResponse) ProtoMessage() {}

func (x *SignDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDocumentResponse.ProtoReflect.Descriptor instead.
func (*SignDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{4}
}

func (x *SignDocumentResponse) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *SignDocumentResponse) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

// GetDocumentRequest is the query for GET /v1/documents/{sign_id}.
type GetDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sign id path parameter. Required.
	SignId string `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	// Originating session identifier; the service returns 404 when this
	// does not match the session the signature was captured under.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{5}
}

func (x *GetDocumentRequest) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *GetDocumentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetDocumentResponse is the success body for GET /v1/documents/{sign_id}.
type GetDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sign id this signature was captured for.
	SignId string `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	// Base64-encoded signature image bytes.
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Opaque signer metadata as supplied at signing time.
	UserMetadata string `protobuf:"bytes,3,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	// Unix-seconds timestamp at which the signature was saved.
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{6}
}

func (x *GetDocumentResponse) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *GetDocumentResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *GetDocumentResponse) GetUserMetadata() string {
	if x != nil {
		return x.UserMetadata
	}
	return ""
}

func (x *GetDocumentResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DownloadDocumentRequest is the query for GET /v1/documents/{sign_id}/download.
type DownloadDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sign id path parameter. Required.
	SignId string `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	// Originating session identifier.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDocumentRequest) Reset() {
	*x = DownloadDocumentRequest{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentRequest) ProtoMessage() {}

func (x *DownloadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentRequest.ProtoReflect.Descriptor instead.
func (*DownloadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadDocumentRequest) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *DownloadDocumentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DownloadDocumentResponse is the success body for GET /v1/documents/{sign_id}/download.
type DownloadDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sign id whose document is being downloaded.
	SignId string `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	// Gzipped PDF payload, base64-encoded. Always set on 2xx.
	PdfGzipBase64 string `protobuf:"bytes,2,opt,name=pdf_gzip_base64,json=pdfGzipBase64,proto3" json:"pdf_gzip_base64,omitempty"`
	// True when `pdf_gzip_base64` is gzip-compressed (always true for
	// this version; reserved for a future uncompressed transport).
	Compressed bool `protobuf:"varint,3,opt,name=compressed,proto3" json:"compressed,omitempty"`
	// The binding legal text that was embedded at render time (empty
	// when none was requested).
	BindingLegalText string `protobuf:"bytes,4,opt,name=binding_legal_text,json=bindingLegalText,proto3" json:"binding_legal_text,omitempty"`
	// Size of the uncompressed PDF in bytes.
	SizeBytes     int64 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDocumentResponse) Reset() {
	*x = DownloadDocumentResponse{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentResponse) ProtoMessage() {}

func (x *DownloadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentResponse.ProtoReflect.Descriptor instead.
func (*DownloadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadDocumentResponse) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *DownloadDocumentResponse) GetPdfGzipBase64() string {
	if x != nil {
		return x.PdfGzipBase64
	}
	return ""
}

func (x *DownloadDocumentResponse) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

func (x *DownloadDocumentResponse) GetBindingLegalText() string {
	if x != nil {
		return x.BindingLegalText
	}
	return ""
}

func (x *DownloadDocumentResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// NotifyDocumentRequest is the body for POST /v1/documents/{sign_id}/notify.
type NotifyDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sign id path parameter. Required.
	SignId string `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	// Originating session identifier.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Recipient email address. Required.
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// Optional template/notification key (selects which template the
	// emailer renders). Empty applies the default signer template.
	Key           string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyDocumentRequest) Reset() {
	*x = NotifyDocumentRequest{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDocumentRequest) ProtoMessage() {}

func (x *NotifyDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDocumentRequest.ProtoReflect.Descriptor instead.
func (*NotifyDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyDocumentRequest) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *NotifyDocumentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NotifyDocumentRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *NotifyDocumentRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// NotifyDocumentResponse is the success body for POST /v1/documents/{sign_id}/notify.
type NotifyDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sign id the notification refers to.
	SignId string `protobuf:"bytes,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	// Lifecycle state after the notification was accepted. Always
	// `notified` on a 2xx response.
	Status        DocumentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=api.rapidsign.v1.DocumentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyDocumentResponse) Reset() {
	*x = NotifyDocumentResponse{}
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDocumentResponse) ProtoMessage() {}

func (x *NotifyDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rapidsign_v1_documents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDocumentResponse.ProtoReflect.Descriptor instead.
func (*NotifyDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rapidsign_v1_documents_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyDocumentResponse) GetSignId() string {
	if x != nil {
		return x.SignId
	}
	return ""
}

func (x *NotifyDocumentResponse) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

var File_api_rapidsign_v1_documents_proto protoreflect.FileDescriptor

const file_api_rapidsign_v1_documents_proto_rawDesc = "" +
	"\n" +
	" api/rapidsign/v1/documents.proto\x12\x10api.rapidsign.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"H\n" +
	"\x0fPdfRenderSource\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12#\n" +
	"\rexpected_hash\x18\x02 \x01(\tR\fexpectedHash\"\xaf\x04\n" +
	"\x15CreateDocumentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\x06packet\x18\x02 \x03(\v2!.api.rapidsign.v1.PdfRenderSourceR\x06packet\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12%\n" +
	"\x0eremote_allowed\x18\x04 \x01(\bR\rremoteAllowed\x12\x19\n" +
	"\bsign_ids\x18\x05 \x03(\tR\asignIds\x12 \n" +
	"\fview_only_id\x18\x06 \x01(\tR\n" +
	"viewOnlyId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\x12#\n" +
	"\ris_production\x18\b \x01(\bR\fisProduction\x12,\n" +
	"\x12binding_legal_text\x18\t \x01(\tR\x10bindingLegalText\x12\x10\n" +
	"\x03ttl\x18\n" +
	" \x01(\tR\x03ttl\x12d\n" +
	"\x0fexpected_hashes\x18\v \x03(\v2;.api.rapidsign.v1.CreateDocumentRequest.ExpectedHashesEntryR\x0eexpectedHashes\x1aA\n" +
	"\x13ExpectedHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\x16CreateDocumentResponse\x12#\n" +
	"\rpacket_stored\x18\x01 \x01(\bR\fpacketStored\x12L\n" +
	"\x06hashes\x18\x02 \x03(\v24.api.rapidsign.v1.CreateDocumentResponse.HashesEntryR\x06hashes\x1a9\n" +
	"\vHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\x13SignDocumentRequest\x12\x17\n" +
	"\asign_id\x18\x01 \x01(\tR\x06signId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12#\n" +
	"\ruser_metadata\x18\x05 \x01(\tR\fuserMetadata\"i\n" +
	"\x14SignDocumentResponse\x12\x17\n" +
	"\asign_id\x18\x01 \x01(\tR\x06signId\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .api.rapidsign.v1.DocumentStatusR\x06status\"L\n" +
	"\x12GetDocumentRequest\x12\x17\n" +
	"\asign_id\x18\x01 \x01(\tR\x06signId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x8f\x01\n" +
	"\x13GetDocumentResponse\x12\x17\n" +
	"\asign_id\x18\x01 \x01(\tR\x06signId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12#\n" +
	"\ruser_metadata\x18\x03 \x01(\tR\fuserMetadata\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"Q\n" +
	"\x17DownloadDocumentRequest\x12\x17\n" +
	"\asign_id\x18\x01 \x01(\tR\x06signId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xc8\x01\n" +
	"\x18DownloadDocumentResponse\x12\x17\n" +
	"\asign_id\x18\x01 \x01(\tR\x06signId\x12&\n" +
	"\x0fpdf_gzip_base64\x18\x02 \x01(\tR\rpdfGzipBase64\x12\x1e\n" +
	"\n" +
	"compressed\x18\x03 \x01(\bR\n" +
	"compressed\x12,\n" +
	"\x12binding_legal_text\x18\x04 \x01(\tR\x10bindingLegalText\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\"q\n" +
	"\x15NotifyDocumentRequest\x12\x17\n" +
	"\asign_id\x18\x01 \x01(\tR\x06signId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"k\n" +
	"\x16NotifyDocumentResponse\x12\x17\n" +
	"\asign_id\x18\x01 \x01(\tR\x06signId\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .api.rapidsign.v1.DocumentStatusR\x06status*\x87\x01\n" +
	"\x0eDocumentStatus\x12\x1f\n" +
	"\x1bDOCUMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DOCUMENT_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15DOCUMENT_STATUS_SAVED\x10\x02\x12\x1c\n" +
	"\x18DOCUMENT_STATUS_NOTIFIED\x10\x032\xbe\x05\n" +
	"\x10DocumentsService\x12}\n" +
	"\x0eCreateDocument\x12'.api.rapidsign.v1.CreateDocumentRequest\x1a(.api.rapidsign.v1.CreateDocumentResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/documents\x12\x86\x01\n" +
	"\fSignDocument\x12%.api.rapidsign.v1.SignDocumentRequest\x1a&.api.rapidsign.v1.SignDocumentResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/documents/{sign_id}/sign\x12{\n" +
	"\vGetDocument\x12$.api.rapidsign.v1.GetDocumentRequest\x1a%.api.rapidsign.v1.GetDocumentResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/documents/{sign_id}\x12\x93\x01\n" +
	"\x10DownloadDocument\x12).api.rapidsign.v1.DownloadDocumentRequest\x1a*.api.rapidsign.v1.DownloadDocumentResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/documents/{sign_id}/download\x12\x8e\x01\n" +
	"\x0eNotifyDocument\x12'.api.rapidsign.v1.NotifyDocumentRequest\x1a(.api.rapidsign.v1.NotifyDocumentResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/documents/{sign_id}/notifyB\xe8\x01\n" +
	"\x14com.api.rapidsign.v1B\x0eDocumentsProtoP\x01ZVgithub.com/isa-sdk/sdk/rapidsign/api/rapidsign/v1;rapidsignv1\xa2\x02\x03ARX\xaa\x02\x17IsaSdk.RapidSign.Api.V1\xca\x02\x14Sah\\RapidSign\\Api\\V1\xe2\x02\x19Sah\\RapidSign\\Api\\V1\\Meta\xea\x02\x12Api::Rapidsign::V1b\x06proto3"

var (
	file_api_rapidsign_v1_documents_proto_rawDescOnce sync.Once
	file_api_rapidsign_v1_documents_proto_rawDescData []byte
)

func file_api_rapidsign_v1_documents_proto_rawDescGZIP() []byte {
	file_api_rapidsign_v1_documents_proto_rawDescOnce.Do(func() {
		file_api_rapidsign_v1_documents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rapidsign_v1_documents_proto_rawDesc), len(file_api_rapidsign_v1_documents_proto_rawDesc)))
	})
	return file_api_rapidsign_v1_documents_proto_rawDescData
}

var file_api_rapidsign_v1_documents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_rapidsign_v1_documents_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_rapidsign_v1_documents_proto_goTypes = []any{
	(DocumentStatus)(0),              // 0: api.rapidsign.v1.DocumentStatus
	(*PdfRenderSource)(nil),          // 1: api.rapidsign.v1.PdfRenderSource
	(*CreateDocumentRequest)(nil),    // 2: api.rapidsign.v1.CreateDocumentRequest
	(*CreateDocumentResponse)(nil),   // 3: api.rapidsign.v1.CreateDocumentResponse
	(*SignDocumentRequest)(nil),      // 4: api.rapidsign.v1.SignDocumentRequest
	(*SignDocumentResponse)(nil),     // 5: api.rapidsign.v1.SignDocumentResponse
	(*GetDocumentRequest)(nil),       // 6: api.rapidsign.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),      // 7: api.rapidsign.v1.GetDocumentResponse
	(*DownloadDocumentRequest)(nil),  // 8: api.rapidsign.v1.DownloadDocumentRequest
	(*DownloadDocumentResponse)(nil), // 9: api.rapidsign.v1.DownloadDocumentResponse
	(*NotifyDocumentRequest)(nil),    // 10: api.rapidsign.v1.NotifyDocumentRequest
	(*NotifyDocumentResponse)(nil),   // 11: api.rapidsign.v1.NotifyDocumentResponse
	nil,                              // 12: api.rapidsign.v1.CreateDocumentRequest.ExpectedHashesEntry
	nil,                              // 13: api.rapidsign.v1.CreateDocumentResponse.HashesEntry
	(*structpb.Struct)(nil),          // 14: google.protobuf.Struct
}
var file_api_rapidsign_v1_documents_proto_depIdxs = []int32{
	1,  // 0: api.rapidsign.v1.CreateDocumentRequest.packet:type_name -> api.rapidsign.v1.PdfRenderSource
	14, // 1: api.rapidsign.v1.CreateDocumentRequest.data:type_name -> google.protobuf.Struct
	12, // 2: api.rapidsign.v1.CreateDocumentRequest.expected_hashes:type_name -> api.rapidsign.v1.CreateDocumentRequest.ExpectedHashesEntry
	13, // 3: api.rapidsign.v1.CreateDocumentResponse.hashes:type_name -> api.rapidsign.v1.CreateDocumentResponse.HashesEntry
	0,  // 4: api.rapidsign.v1.SignDocumentResponse.status:type_name -> api.rapidsign.v1.DocumentStatus
	0,  // 5: api.rapidsign.v1.NotifyDocumentResponse.status:type_name -> api.rapidsign.v1.DocumentStatus
	2,  // 6: api.rapidsign.v1.DocumentsService.CreateDocument:input_type -> api.rapidsign.v1.CreateDocumentRequest
	4,  // 7: api.rapidsign.v1.DocumentsService.SignDocument:input_type -> api.rapidsign.v1.SignDocumentRequest
	6,  // 8: api.rapidsign.v1.DocumentsService.GetDocument:input_type -> api.rapidsign.v1.GetDocumentRequest
	8,  // 9: api.rapidsign.v1.DocumentsService.DownloadDocument:input_type -> api.rapidsign.v1.DownloadDocumentRequest
	10, // 10: api.rapidsign.v1.DocumentsService.NotifyDocument:input_type -> api.rapidsign.v1.NotifyDocumentRequest
	3,  // 11: api.rapidsign.v1.DocumentsService.CreateDocument:output_type -> api.rapidsign.v1.CreateDocumentResponse
	5,  // 12: api.rapidsign.v1.DocumentsService.SignDocument:output_type -> api.rapidsign.v1.SignDocumentResponse
	7,  // 13: api.rapidsign.v1.DocumentsService.GetDocument:output_type -> api.rapidsign.v1.GetDocumentResponse
	9,  // 14: api.rapidsign.v1.DocumentsService.DownloadDocument:output_type -> api.rapidsign.v1.DownloadDocumentResponse
	11, // 15: api.rapidsign.v1.DocumentsService.NotifyDocument:output_type -> api.rapidsign.v1.NotifyDocumentResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_rapidsign_v1_documents_proto_init() }
func file_api_rapidsign_v1_documents_proto_init() {
	if File_api_rapidsign_v1_documents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rapidsign_v1_documents_proto_rawDesc), len(file_api_rapidsign_v1_documents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rapidsign_v1_documents_proto_goTypes,
		DependencyIndexes: file_api_rapidsign_v1_documents_proto_depIdxs,
		EnumInfos:         file_api_rapidsign_v1_documents_proto_enumTypes,
		MessageInfos:      file_api_rapidsign_v1_documents_proto_msgTypes,
	}.Build()
	File_api_rapidsign_v1_documents_proto = out.File
	file_api_rapidsign_v1_documents_proto_goTypes = nil
	file_api_rapidsign_v1_documents_proto_depIdxs = nil
}
