// accounts.proto defines the account, subscription-plan, and plan-rate
// management surface for the ZyINS Unified API. All routes are mounted
// under `zyins.isaapi.com/v1`.
//
// Accounts are the billing/service owners of API tokens (see
// tokens.proto). Each account is assigned exactly one SubscriptionPlan,
// which is billed per-endpoint via PlanRate entries. Authentication is
// BearerAuth on every RPC; create/update RPCs additionally require the
// admin scope, carried in the generated OpenAPI via the merge overlay
// (shared/schemas/overlays/zyins-v1.yaml) rather than inline annotations.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/zyins/v1/accounts.proto

package zyinsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlanTier is the subscription plan's pricing tier. Wire values are
// lowercase single words per ADR-012. Ordering is from least to most
// inclusive; new tiers are appended (never inserted) to preserve the
// numeric ordering for consumers that switch on it.
type PlanTier int32

const (
	// Default zero value. Never emitted by the server.
	PlanTier_PLAN_TIER_UNSPECIFIED PlanTier = 0
	// Free tier with capped usage (wire: `free`).
	PlanTier_PLAN_TIER_FREE PlanTier = 1
	// Entry-level paid tier (wire: `starter`).
	PlanTier_PLAN_TIER_STARTER PlanTier = 2
	// Production tier (wire: `pro`).
	PlanTier_PLAN_TIER_PRO PlanTier = 3
	// Custom-contract tier (wire: `enterprise`).
	PlanTier_PLAN_TIER_ENTERPRISE PlanTier = 4
)

// Enum value maps for PlanTier.
var (
	PlanTier_name = map[int32]string{
		0: "PLAN_TIER_UNSPECIFIED",
		1: "PLAN_TIER_FREE",
		2: "PLAN_TIER_STARTER",
		3: "PLAN_TIER_PRO",
		4: "PLAN_TIER_ENTERPRISE",
	}
	PlanTier_value = map[string]int32{
		"PLAN_TIER_UNSPECIFIED": 0,
		"PLAN_TIER_FREE":        1,
		"PLAN_TIER_STARTER":     2,
		"PLAN_TIER_PRO":         3,
		"PLAN_TIER_ENTERPRISE":  4,
	}
)

func (x PlanTier) Enum() *PlanTier {
	p := new(PlanTier)
	*p = x
	return p
}

func (x PlanTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanTier) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zyins_v1_accounts_proto_enumTypes[0].Descriptor()
}

func (PlanTier) Type() protoreflect.EnumType {
	return &file_api_zyins_v1_accounts_proto_enumTypes[0]
}

func (x PlanTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanTier.Descriptor instead.
func (PlanTier) EnumDescriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{0}
}

// CreateAccountRequest is the body for POST /v1/accounts.
type CreateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Externally assigned account identifier. Must be unique.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable account name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Primary contact email for the account.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Identifier of the subscription plan to assign at creation. Optional;
	// empty string leaves the account on the default plan.
	PlanId        string `protobuf:"bytes,4,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

// GetAccountRequest identifies an account by id.
type GetAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account identifier (path parameter).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListAccountsRequest is the empty request body for GET /v1/accounts.
type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{2}
}

// ListAccountsResponse is the 200 body from ListAccounts.
type ListAccountsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `list`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The accounts visible to the caller.
	Data          []*AccountDetail `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccountsResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ListAccountsResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *ListAccountsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListAccountsResponse) GetData() []*AccountDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateAccountPlanRequest is the body for PUT /v1/accounts/{id}/plan.
type UpdateAccountPlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account identifier (path parameter).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identifier of the subscription plan to assign. Required.
	PlanId        string `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountPlanRequest) Reset() {
	*x = UpdateAccountPlanRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountPlanRequest) ProtoMessage() {}

func (x *UpdateAccountPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountPlanRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAccountPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccountPlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

// AccountDetail is the canonical account resource shape returned by
// every account RPC.
type AccountDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `account`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Account identifier.
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable account name.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Primary contact email for the account.
	Email string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	// Identifier of the currently assigned subscription plan. Empty string
	// if the account is on the default plan.
	PlanId string `protobuf:"bytes,7,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// Current lifecycle state.
	Status AccountStatus `protobuf:"varint,8,opt,name=status,proto3,enum=api.zyins.v1.AccountStatus" json:"status,omitempty"`
	// RFC 3339 creation timestamp.
	CreatedAt string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// RFC 3339 timestamp of the most recent mutation.
	UpdatedAt     string `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountDetail) Reset() {
	*x = AccountDetail{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetail) ProtoMessage() {}

func (x *AccountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetail.ProtoReflect.Descriptor instead.
func (*AccountDetail) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *AccountDetail) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *AccountDetail) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *AccountDetail) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AccountDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountDetail) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *AccountDetail) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *AccountDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccountDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetPlanRequest identifies a subscription plan by id.
type GetPlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plan identifier (path parameter).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListPlansRequest is the empty request body for GET /v1/plans.
type ListPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{7}
}

// ListPlansResponse is the 200 body from ListPlans.
type ListPlansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `list`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The available subscription plans.
	Data          []*PlanDetail `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{8}
}

func (x *ListPlansResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ListPlansResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *ListPlansResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListPlansResponse) GetData() []*PlanDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

// CreatePlanRequest is the body for POST /v1/plans.
type CreatePlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Externally assigned plan identifier. Must be unique.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable plan name (e.g. "Starter", "Pro", "Enterprise").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Long-form description shown on billing pages.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Pricing tier classification.
	Tier PlanTier `protobuf:"varint,4,opt,name=tier,proto3,enum=api.zyins.v1.PlanTier" json:"tier,omitempty"`
	// Per-plan usage limits. Optional; omitted means unlimited.
	Limits        *PlanLimits `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlanRequest) Reset() {
	*x = CreatePlanRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlanRequest) ProtoMessage() {}

func (x *CreatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlanRequest.ProtoReflect.Descriptor instead.
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePlanRequest) GetTier() PlanTier {
	if x != nil {
		return x.Tier
	}
	return PlanTier_PLAN_TIER_UNSPECIFIED
}

func (x *CreatePlanRequest) GetLimits() *PlanLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

// PlanDetail is the canonical subscription plan resource shape. Returned
// by GetPlan, CreatePlan, and ListPlans (nested).
type PlanDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `plan`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Plan identifier.
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable plan name.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Long-form description.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Pricing tier classification.
	Tier PlanTier `protobuf:"varint,7,opt,name=tier,proto3,enum=api.zyins.v1.PlanTier" json:"tier,omitempty"`
	// Per-plan usage limits. Omitted means unlimited.
	Limits *PlanLimits `protobuf:"bytes,8,opt,name=limits,proto3" json:"limits,omitempty"`
	// Whether the plan is available for new assignments.
	IsActive bool `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// RFC 3339 creation timestamp.
	CreatedAt string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Per-metric rates configured for this plan. Populated by GetPlan;
	// empty on ListPlans and CreatePlan responses.
	Rates         []*PlanRate `protobuf:"bytes,11,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanDetail) Reset() {
	*x = PlanDetail{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanDetail) ProtoMessage() {}

func (x *PlanDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanDetail.ProtoReflect.Descriptor instead.
func (*PlanDetail) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{10}
}

func (x *PlanDetail) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *PlanDetail) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *PlanDetail) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlanDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlanDetail) GetTier() PlanTier {
	if x != nil {
		return x.Tier
	}
	return PlanTier_PLAN_TIER_UNSPECIFIED
}

func (x *PlanDetail) GetLimits() *PlanLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *PlanDetail) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PlanDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PlanDetail) GetRates() []*PlanRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

// PlanLimits captures the usage ceilings enforced for a plan. A zero
// value in any field means "unlimited for that dimension". The server
// also enforces per-token and global rate limits; those are separate.
type PlanLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum authenticated requests per month. Zero means unlimited.
	RequestsPerMonth int64 `protobuf:"varint,1,opt,name=requests_per_month,json=requestsPerMonth,proto3" json:"requests_per_month,omitempty"`
	// Maximum API tokens the account may hold concurrently. Zero means
	// unlimited.
	MaxTokens int32 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// Maximum concurrent requests per second. Zero means unlimited.
	RequestsPerSecond int32 `protobuf:"varint,3,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanLimits) Reset() {
	*x = PlanLimits{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanLimits) ProtoMessage() {}

func (x *PlanLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanLimits.ProtoReflect.Descriptor instead.
func (*PlanLimits) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{11}
}

func (x *PlanLimits) GetRequestsPerMonth() int64 {
	if x != nil {
		return x.RequestsPerMonth
	}
	return 0
}

func (x *PlanLimits) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *PlanLimits) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

// GetPlanRatesRequest identifies the plan whose rates are requested.
type GetPlanRatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plan identifier (path parameter).
	PlanId        string `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRatesRequest) Reset() {
	*x = GetPlanRatesRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRatesRequest) ProtoMessage() {}

func (x *GetPlanRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRatesRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRatesRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{12}
}

func (x *GetPlanRatesRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

// ListPlanRatesResponse is the 200 body from GetPlanRates.
type ListPlanRatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `list`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The rates configured for the plan.
	Data          []*PlanRate `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlanRatesResponse) Reset() {
	*x = ListPlanRatesResponse{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlanRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlanRatesResponse) ProtoMessage() {}

func (x *ListPlanRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlanRatesResponse.ProtoReflect.Descriptor instead.
func (*ListPlanRatesResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{13}
}

func (x *ListPlanRatesResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ListPlanRatesResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *ListPlanRatesResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListPlanRatesResponse) GetData() []*PlanRate {
	if x != nil {
		return x.Data
	}
	return nil
}

// SetPlanRateRequest is the body for PUT /v1/plans/{plan_id}/rates/{metric}.
// The server upserts by (plan_id, metric): if a rate for the metric
// already exists it is replaced; otherwise a new rate is inserted.
type SetPlanRateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plan identifier (path parameter).
	PlanId string `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// Metric identifier (path parameter). Conventionally the endpoint name
	// being priced, e.g. `prequalify`, `quote`, or `datasets.fetch`.
	Metric string `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	// Cost per unit of the metric, in the minor unit of `currency`
	// (e.g. cents for USD). A decimal string to preserve sub-cent precision.
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// ISO 4217 currency code for `amount` (e.g. `USD`).
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// RFC 3339 timestamp at which the rate takes effect. Empty string
	// means "immediately on upsert".
	EffectiveAt string `protobuf:"bytes,5,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	// Requests included at no additional charge before `amount` applies.
	// Zero means every request is billed at `amount`.
	IncludedFree  int32 `protobuf:"varint,6,opt,name=included_free,json=includedFree,proto3" json:"included_free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlanRateRequest) Reset() {
	*x = SetPlanRateRequest{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlanRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlanRateRequest) ProtoMessage() {}

func (x *SetPlanRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlanRateRequest.ProtoReflect.Descriptor instead.
func (*SetPlanRateRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{14}
}

func (x *SetPlanRateRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SetPlanRateRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SetPlanRateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SetPlanRateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SetPlanRateRequest) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

func (x *SetPlanRateRequest) GetIncludedFree() int32 {
	if x != nil {
		return x.IncludedFree
	}
	return 0
}

// SetPlanRateResponse is the 200 body from SetPlanRate.
type SetPlanRateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `plan_rate`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Plan identifier the rate belongs to.
	PlanId string `protobuf:"bytes,4,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// Metric identifier (e.g. `prequalify`, `quote`).
	Metric string `protobuf:"bytes,5,opt,name=metric,proto3" json:"metric,omitempty"`
	// Cost per unit of the metric, in the minor unit of `currency`. A
	// decimal string to preserve sub-cent precision.
	Amount string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// ISO 4217 currency code for `amount`.
	Currency string `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	// RFC 3339 timestamp at which the rate took effect.
	EffectiveAt string `protobuf:"bytes,8,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	// Requests included at no additional charge before `amount` applies.
	IncludedFree  int32 `protobuf:"varint,9,opt,name=included_free,json=includedFree,proto3" json:"included_free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlanRateResponse) Reset() {
	*x = SetPlanRateResponse{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlanRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlanRateResponse) ProtoMessage() {}

func (x *SetPlanRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlanRateResponse.ProtoReflect.Descriptor instead.
func (*SetPlanRateResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{15}
}

func (x *SetPlanRateResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *SetPlanRateResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *SetPlanRateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SetPlanRateResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SetPlanRateResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SetPlanRateResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SetPlanRateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SetPlanRateResponse) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

func (x *SetPlanRateResponse) GetIncludedFree() int32 {
	if x != nil {
		return x.IncludedFree
	}
	return 0
}

// PlanRate is the canonical rate resource shape nested in
// ListPlanRatesResponse and PlanDetail.
type PlanRate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `plan_rate`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Plan identifier the rate belongs to.
	PlanId string `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// Metric identifier (e.g. `prequalify`, `quote`).
	Metric string `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	// Cost per unit of the metric, in the minor unit of `currency`. A
	// decimal string to preserve sub-cent precision.
	Amount string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// ISO 4217 currency code for `amount`.
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// RFC 3339 timestamp at which the rate took effect.
	EffectiveAt string `protobuf:"bytes,6,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	// Requests included at no additional charge before `amount` applies.
	IncludedFree  int32 `protobuf:"varint,7,opt,name=included_free,json=includedFree,proto3" json:"included_free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRate) Reset() {
	*x = PlanRate{}
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRate) ProtoMessage() {}

func (x *PlanRate) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_accounts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRate.ProtoReflect.Descriptor instead.
func (*PlanRate) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_accounts_proto_rawDescGZIP(), []int{16}
}

func (x *PlanRate) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *PlanRate) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanRate) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *PlanRate) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PlanRate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PlanRate) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

func (x *PlanRate) GetIncludedFree() int32 {
	if x != nil {
		return x.IncludedFree
	}
	return 0
}

var File_api_zyins_v1_accounts_proto protoreflect.FileDescriptor

const file_api_zyins_v1_accounts_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/zyins/v1/accounts.proto\x12\fapi.zyins.v1\x1a\x19api/zyins/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"i\n" +
	"\x14CreateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x17\n" +
	"\aplan_id\x18\x04 \x01(\tR\x06planId\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ListAccountsRequest\"\x9a\x01\n" +
	"\x14ListAccountsResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12/\n" +
	"\x04data\x18\x04 \x03(\v2\x1b.api.zyins.v1.AccountDetailR\x04data\"C\n" +
	"\x18UpdateAccountPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\"\xa8\x02\n" +
	"\rAccountDetail\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x17\n" +
	"\aplan_id\x18\a \x01(\tR\x06planId\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x1b.api.zyins.v1.AccountStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\" \n" +
	"\x0eGetPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10ListPlansRequest\"\x94\x01\n" +
	"\x11ListPlansResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12,\n" +
	"\x04data\x18\x04 \x03(\v2\x18.api.zyins.v1.PlanDetailR\x04data\"\xb7\x01\n" +
	"\x11CreatePlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x04tier\x18\x04 \x01(\x0e2\x16.api.zyins.v1.PlanTierR\x04tier\x120\n" +
	"\x06limits\x18\x05 \x01(\v2\x18.api.zyins.v1.PlanLimitsR\x06limits\"\xed\x02\n" +
	"\n" +
	"PlanDetail\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12*\n" +
	"\x04tier\x18\a \x01(\x0e2\x16.api.zyins.v1.PlanTierR\x04tier\x120\n" +
	"\x06limits\x18\b \x01(\v2\x18.api.zyins.v1.PlanLimitsR\x06limits\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12,\n" +
	"\x05rates\x18\v \x03(\v2\x16.api.zyins.v1.PlanRateR\x05rates\"\x89\x01\n" +
	"\n" +
	"PlanLimits\x12,\n" +
	"\x12requests_per_month\x18\x01 \x01(\x03R\x10requestsPerMonth\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05R\tmaxTokens\x12.\n" +
	"\x13requests_per_second\x18\x03 \x01(\x05R\x11requestsPerSecond\".\n" +
	"\x13GetPlanRatesRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"\x96\x01\n" +
	"\x15ListPlanRatesResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12*\n" +
	"\x04data\x18\x04 \x03(\v2\x16.api.zyins.v1.PlanRateR\x04data\"\xc1\x01\n" +
	"\x12SetPlanRateRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\feffective_at\x18\x05 \x01(\tR\veffectiveAt\x12#\n" +
	"\rincluded_free\x18\x06 \x01(\x05R\fincludedFree\"\x95\x02\n" +
	"\x13SetPlanRateResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x17\n" +
	"\aplan_id\x18\x04 \x01(\tR\x06planId\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\tR\x06metric\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12!\n" +
	"\feffective_at\x18\b \x01(\tR\veffectiveAt\x12#\n" +
	"\rincluded_free\x18\t \x01(\x05R\fincludedFree\"\xcf\x01\n" +
	"\bPlanRate\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12!\n" +
	"\feffective_at\x18\x06 \x01(\tR\veffectiveAt\x12#\n" +
	"\rincluded_free\x18\a \x01(\x05R\fincludedFree*}\n" +
	"\bPlanTier\x12\x19\n" +
	"\x15PLAN_TIER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePLAN_TIER_FREE\x10\x01\x12\x15\n" +
	"\x11PLAN_TIER_STARTER\x10\x02\x12\x11\n" +
	"\rPLAN_TIER_PRO\x10\x03\x12\x18\n" +
	"\x14PLAN_TIER_ENTERPRISE\x10\x042\xe7\a\n" +
	"\x0fAccountsService\x12i\n" +
	"\rCreateAccount\x12\".api.zyins.v1.CreateAccountRequest\x1a\x1b.api.zyins.v1.AccountDetail\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/accounts\x12e\n" +
	"\n" +
	"GetAccount\x12\x1f.api.zyins.v1.GetAccountRequest\x1a\x1b.api.zyins.v1.AccountDetail\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/accounts/{id}\x12k\n" +
	"\fListAccounts\x12!.api.zyins.v1.ListAccountsRequest\x1a\".api.zyins.v1.ListAccountsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/accounts\x12{\n" +
	"\x11UpdateAccountPlan\x12&.api.zyins.v1.UpdateAccountPlanRequest\x1a\x1b.api.zyins.v1.AccountDetail\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v1/accounts/{id}/plan\x12Y\n" +
	"\aGetPlan\x12\x1c.api.zyins.v1.GetPlanRequest\x1a\x18.api.zyins.v1.PlanDetail\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/plans/{id}\x12_\n" +
	"\tListPlans\x12\x1e.api.zyins.v1.ListPlansRequest\x1a\x1f.api.zyins.v1.ListPlansResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/plans\x12]\n" +
	"\n" +
	"CreatePlan\x12\x1f.api.zyins.v1.CreatePlanRequest\x1a\x18.api.zyins.v1.PlanDetail\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/plans\x12y\n" +
	"\fGetPlanRates\x12!.api.zyins.v1.GetPlanRatesRequest\x1a#.api.zyins.v1.ListPlanRatesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/plans/{plan_id}/rates\x12\x81\x01\n" +
	"\vSetPlanRate\x12 .api.zyins.v1.SetPlanRateRequest\x1a!.api.zyins.v1.SetPlanRateResponse\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/v1/plans/{plan_id}/rates/{metric}B\xc7\x01\n" +
	"\x10com.api.zyins.v1B\rAccountsProtoP\x01ZJgithub.com/isa-sdk/sdk/zyins/api/zyins/v1;zyinsv1\xa2\x02\x03AZX\xaa\x02\x13IsaSdk.ZyINS.Api.V1\xca\x02\x10Sah\\ZyINS\\Api\\V1\xe2\x02\x15Sah\\ZyINS\\Api\\V1\\Meta\xea\x02\x0eApi::Zyins::V1b\x06proto3"

var (
	file_api_zyins_v1_accounts_proto_rawDescOnce sync.Once
	file_api_zyins_v1_accounts_proto_rawDescData []byte
)

func file_api_zyins_v1_accounts_proto_rawDescGZIP() []byte {
	file_api_zyins_v1_accounts_proto_rawDescOnce.Do(func() {
		file_api_zyins_v1_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zyins_v1_accounts_proto_rawDesc), len(file_api_zyins_v1_accounts_proto_rawDesc)))
	})
	return file_api_zyins_v1_accounts_proto_rawDescData
}

var file_api_zyins_v1_accounts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_zyins_v1_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_zyins_v1_accounts_proto_goTypes = []any{
	(PlanTier)(0),                    // 0: api.zyins.v1.PlanTier
	(*CreateAccountRequest)(nil),     // 1: api.zyins.v1.CreateAccountRequest
	(*GetAccountRequest)(nil),        // 2: api.zyins.v1.GetAccountRequest
	(*ListAccountsRequest)(nil),      // 3: api.zyins.v1.ListAccountsRequest
	(*ListAccountsResponse)(nil),     // 4: api.zyins.v1.ListAccountsResponse
	(*UpdateAccountPlanRequest)(nil), // 5: api.zyins.v1.UpdateAccountPlanRequest
	(*AccountDetail)(nil),            // 6: api.zyins.v1.AccountDetail
	(*GetPlanRequest)(nil),           // 7: api.zyins.v1.GetPlanRequest
	(*ListPlansRequest)(nil),         // 8: api.zyins.v1.ListPlansRequest
	(*ListPlansResponse)(nil),        // 9: api.zyins.v1.ListPlansResponse
	(*CreatePlanRequest)(nil),        // 10: api.zyins.v1.CreatePlanRequest
	(*PlanDetail)(nil),               // 11: api.zyins.v1.PlanDetail
	(*PlanLimits)(nil),               // 12: api.zyins.v1.PlanLimits
	(*GetPlanRatesRequest)(nil),      // 13: api.zyins.v1.GetPlanRatesRequest
	(*ListPlanRatesResponse)(nil),    // 14: api.zyins.v1.ListPlanRatesResponse
	(*SetPlanRateRequest)(nil),       // 15: api.zyins.v1.SetPlanRateRequest
	(*SetPlanRateResponse)(nil),      // 16: api.zyins.v1.SetPlanRateResponse
	(*PlanRate)(nil),                 // 17: api.zyins.v1.PlanRate
	(AccountStatus)(0),               // 18: api.zyins.v1.AccountStatus
}
var file_api_zyins_v1_accounts_proto_depIdxs = []int32{
	6,  // 0: api.zyins.v1.ListAccountsResponse.data:type_name -> api.zyins.v1.AccountDetail
	18, // 1: api.zyins.v1.AccountDetail.status:type_name -> api.zyins.v1.AccountStatus
	11, // 2: api.zyins.v1.ListPlansResponse.data:type_name -> api.zyins.v1.PlanDetail
	0,  // 3: api.zyins.v1.CreatePlanRequest.tier:type_name -> api.zyins.v1.PlanTier
	12, // 4: api.zyins.v1.CreatePlanRequest.limits:type_name -> api.zyins.v1.PlanLimits
	0,  // 5: api.zyins.v1.PlanDetail.tier:type_name -> api.zyins.v1.PlanTier
	12, // 6: api.zyins.v1.PlanDetail.limits:type_name -> api.zyins.v1.PlanLimits
	17, // 7: api.zyins.v1.PlanDetail.rates:type_name -> api.zyins.v1.PlanRate
	17, // 8: api.zyins.v1.ListPlanRatesResponse.data:type_name -> api.zyins.v1.PlanRate
	1,  // 9: api.zyins.v1.AccountsService.CreateAccount:input_type -> api.zyins.v1.CreateAccountRequest
	2,  // 10: api.zyins.v1.AccountsService.GetAccount:input_type -> api.zyins.v1.GetAccountRequest
	3,  // 11: api.zyins.v1.AccountsService.ListAccounts:input_type -> api.zyins.v1.ListAccountsRequest
	5,  // 12: api.zyins.v1.AccountsService.UpdateAccountPlan:input_type -> api.zyins.v1.UpdateAccountPlanRequest
	7,  // 13: api.zyins.v1.AccountsService.GetPlan:input_type -> api.zyins.v1.GetPlanRequest
	8,  // 14: api.zyins.v1.AccountsService.ListPlans:input_type -> api.zyins.v1.ListPlansRequest
	10, // 15: api.zyins.v1.AccountsService.CreatePlan:input_type -> api.zyins.v1.CreatePlanRequest
	13, // 16: api.zyins.v1.AccountsService.GetPlanRates:input_type -> api.zyins.v1.GetPlanRatesRequest
	15, // 17: api.zyins.v1.AccountsService.SetPlanRate:input_type -> api.zyins.v1.SetPlanRateRequest
	6,  // 18: api.zyins.v1.AccountsService.CreateAccount:output_type -> api.zyins.v1.AccountDetail
	6,  // 19: api.zyins.v1.AccountsService.GetAccount:output_type -> api.zyins.v1.AccountDetail
	4,  // 20: api.zyins.v1.AccountsService.ListAccounts:output_type -> api.zyins.v1.ListAccountsResponse
	6,  // 21: api.zyins.v1.AccountsService.UpdateAccountPlan:output_type -> api.zyins.v1.AccountDetail
	11, // 22: api.zyins.v1.AccountsService.GetPlan:output_type -> api.zyins.v1.PlanDetail
	9,  // 23: api.zyins.v1.AccountsService.ListPlans:output_type -> api.zyins.v1.ListPlansResponse
	11, // 24: api.zyins.v1.AccountsService.CreatePlan:output_type -> api.zyins.v1.PlanDetail
	14, // 25: api.zyins.v1.AccountsService.GetPlanRates:output_type -> api.zyins.v1.ListPlanRatesResponse
	16, // 26: api.zyins.v1.AccountsService.SetPlanRate:output_type -> api.zyins.v1.SetPlanRateResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_zyins_v1_accounts_proto_init() }
func file_api_zyins_v1_accounts_proto_init() {
	if File_api_zyins_v1_accounts_proto != nil {
		return
	}
	file_api_zyins_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zyins_v1_accounts_proto_rawDesc), len(file_api_zyins_v1_accounts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zyins_v1_accounts_proto_goTypes,
		DependencyIndexes: file_api_zyins_v1_accounts_proto_depIdxs,
		EnumInfos:         file_api_zyins_v1_accounts_proto_enumTypes,
		MessageInfos:      file_api_zyins_v1_accounts_proto_msgTypes,
	}.Build()
	File_api_zyins_v1_accounts_proto = out.File
	file_api_zyins_v1_accounts_proto_goTypes = nil
	file_api_zyins_v1_accounts_proto_depIdxs = nil
}
