// branding.proto is a DESIGN-ONLY placeholder for the whitelabel
// branding contract.
//
// Status: DRAFT — not wired to any RPC, not exposed in the OpenAPI
// surface, not assigned a stable token namespace, not consumed by any
// SDK. This file exists so the design surface is visible in code review
// while the whitelabel contract is finalized.
//
// DO NOT:
//   - Add `google.api.http` annotations to messages here.
//   - Reference these messages from `cases.proto`, `email.proto`,
//     `preferences.proto`, or any other shipped proto.
//   - Generate OpenAPI schemas for this file.
//   - Generate SDK bindings for this file.
//
// TODO(whitelabel-contract): finalize the field set, allocate a stable
// proto field-number range, decide the persistence model (whether
// branding is a slice of preferences or a sibling resource), and add
// the service definition. Until then, treat this message as scratch.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/zyins/v1/branding.proto

package zyinsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Branding is the placeholder shape for the whitelabel branding
// resource. The field set will change before this message ships;
// callers MUST NOT depend on these field numbers.
//
// TODO(whitelabel-contract): replace this message with the finalized
// shape.
type Branding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Placeholder identifier. Wire value semantics undecided.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Placeholder display name. May be removed.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Placeholder primary color. May be removed.
	PrimaryColor string `protobuf:"bytes,3,opt,name=primary_color,json=primaryColor,proto3" json:"primary_color,omitempty"`
	// Placeholder logo URL. May be removed.
	LogoUrl       string `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branding) Reset() {
	*x = Branding{}
	mi := &file_api_zyins_v1_branding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branding) ProtoMessage() {}

func (x *Branding) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_branding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branding.ProtoReflect.Descriptor instead.
func (*Branding) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_branding_proto_rawDescGZIP(), []int{0}
}

func (x *Branding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Branding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branding) GetPrimaryColor() string {
	if x != nil {
		return x.PrimaryColor
	}
	return ""
}

func (x *Branding) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

var File_api_zyins_v1_branding_proto protoreflect.FileDescriptor

const file_api_zyins_v1_branding_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/zyins/v1/branding.proto\x12\fapi.zyins.v1\"n\n" +
	"\bBranding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rprimary_color\x18\x03 \x01(\tR\fprimaryColor\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrlB\xc7\x01\n" +
	"\x10com.api.zyins.v1B\rBrandingProtoP\x01ZJgithub.com/isa-sdk/sdk/zyins/api/zyins/v1;zyinsv1\xa2\x02\x03AZX\xaa\x02\x13IsaSdk.ZyINS.Api.V1\xca\x02\x10Sah\\ZyINS\\Api\\V1\xe2\x02\x15Sah\\ZyINS\\Api\\V1\\Meta\xea\x02\x0eApi::Zyins::V1b\x06proto3"

var (
	file_api_zyins_v1_branding_proto_rawDescOnce sync.Once
	file_api_zyins_v1_branding_proto_rawDescData []byte
)

func file_api_zyins_v1_branding_proto_rawDescGZIP() []byte {
	file_api_zyins_v1_branding_proto_rawDescOnce.Do(func() {
		file_api_zyins_v1_branding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zyins_v1_branding_proto_rawDesc), len(file_api_zyins_v1_branding_proto_rawDesc)))
	})
	return file_api_zyins_v1_branding_proto_rawDescData
}

var file_api_zyins_v1_branding_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_zyins_v1_branding_proto_goTypes = []any{
	(*Branding)(nil), // 0: api.zyins.v1.Branding
}
var file_api_zyins_v1_branding_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_zyins_v1_branding_proto_init() }
func file_api_zyins_v1_branding_proto_init() {
	if File_api_zyins_v1_branding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zyins_v1_branding_proto_rawDesc), len(file_api_zyins_v1_branding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_zyins_v1_branding_proto_goTypes,
		DependencyIndexes: file_api_zyins_v1_branding_proto_depIdxs,
		MessageInfos:      file_api_zyins_v1_branding_proto_msgTypes,
	}.Build()
	File_api_zyins_v1_branding_proto = out.File
	file_api_zyins_v1_branding_proto_goTypes = nil
	file_api_zyins_v1_branding_proto_depIdxs = nil
}
