// cases.proto defines the account-scoped case persistence surface for the
// ZyINS Unified API. A "case" is an immutable, content-addressable
// snapshot of an underwriting evaluation (input + optional results +
// product list) that can be linked to from outside the API — the
// canonical agent-facing URL is `https://bestplanpro.com/?case=<hash>`.
//
// All routes are mounted under `zyins.isaapi.com/v1`. Every operation is
// account-scoped: the calling token determines `account_id`, every read
// filters by `account_id`, and there is no cross-account visibility at
// the query layer. Storage backs onto PostgreSQL (`store.CaseRepository`)
// with content-hash deduplication; large payloads spill to S3 with the
// row carrying an `s3_key` reference.
//
// Companion guides for integrators live in `api/guides/cases.md`. This
// file is the wire contract; the guides explain the dedup model, the
// readonly semantics, and the email helper.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/zyins/v1/cases.proto

package zyinsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateCaseRequest is the body for POST /v1/case. The `input` field is
// polymorphic: a JSON object is converted to XML server-side; a JSON
// string is treated as raw XML for backward compatibility with legacy
// integrations. New integrations should always send a structured object.
type CreateCaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The applicant inputs that produced this case. Either a structured
	// JSON object describing the proposed insured (preferred) or a raw
	// XML string for legacy callers. Required.
	Input *structpb.Value `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// The evaluation results to display alongside the input. When set,
	// the case is marked readonly: viewers see the cached results rather
	// than re-running the engine. Optional.
	Results *structpb.Value `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`
	// The product slugs the case was evaluated against. Persisted as a
	// `|`-joined string internally; supplied as an array on the wire.
	// Optional.
	Products      []string `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCaseRequest) Reset() {
	*x = CreateCaseRequest{}
	mi := &file_api_zyins_v1_cases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCaseRequest) ProtoMessage() {}

func (x *CreateCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_cases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCaseRequest.ProtoReflect.Descriptor instead.
func (*CreateCaseRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_cases_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCaseRequest) GetInput() *structpb.Value {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CreateCaseRequest) GetResults() *structpb.Value {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CreateCaseRequest) GetProducts() []string {
	if x != nil {
		return x.Products
	}
	return nil
}

// GetCaseRequest identifies a case by short hash.
type GetCaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 11-character alphanumeric short hash from CreateCase. Path parameter.
	Hash          string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaseRequest) Reset() {
	*x = GetCaseRequest{}
	mi := &file_api_zyins_v1_cases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseRequest) ProtoMessage() {}

func (x *GetCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_cases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseRequest.ProtoReflect.Descriptor instead.
func (*GetCaseRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_cases_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaseRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// ListCasesRequest is the cursor-paginated request body for
// GET /v1/cases.
type ListCasesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque pagination cursor from a previous response's `next_cursor`.
	// Empty string requests the first page.
	Cursor string `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Page size. Defaults to 25, max 100. Zero means default.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCasesRequest) Reset() {
	*x = ListCasesRequest{}
	mi := &file_api_zyins_v1_cases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCasesRequest) ProtoMessage() {}

func (x *ListCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_cases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCasesRequest.ProtoReflect.Descriptor instead.
func (*ListCasesRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_cases_proto_rawDescGZIP(), []int{2}
}

func (x *ListCasesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListCasesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListCasesResponse is the 200 body from ListCases.
type ListCasesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `list`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The cases visible to the calling account, newest first.
	Data []*CaseDetail `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	// True when more results exist past `next_cursor`.
	HasMore bool `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// Cursor for the next page, or empty when `has_more` is false.
	NextCursor    string `protobuf:"bytes,6,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCasesResponse) Reset() {
	*x = ListCasesResponse{}
	mi := &file_api_zyins_v1_cases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCasesResponse) ProtoMessage() {}

func (x *ListCasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_cases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCasesResponse.ProtoReflect.Descriptor instead.
func (*ListCasesResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_cases_proto_rawDescGZIP(), []int{3}
}

func (x *ListCasesResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ListCasesResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *ListCasesResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListCasesResponse) GetData() []*CaseDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListCasesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListCasesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// EmailCaseRequest is the body for POST /v1/cases/{hash}/email.
type EmailCaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short hash of the case to email. Path parameter.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Recipient email address. Required; must be RFC 5322 valid.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Subject line. Optional; falls back to a server-default subject when
	// empty.
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// Caller-supplied prose appended above the case link in the email
	// body. Optional; markdown is not interpreted.
	Note          string `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailCaseRequest) Reset() {
	*x = EmailCaseRequest{}
	mi := &file_api_zyins_v1_cases_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCaseRequest) ProtoMessage() {}

func (x *EmailCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_cases_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCaseRequest.ProtoReflect.Descriptor instead.
func (*EmailCaseRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_cases_proto_rawDescGZIP(), []int{4}
}

func (x *EmailCaseRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EmailCaseRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EmailCaseRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailCaseRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// EmailCaseResponse is the 202 body from EmailCase. The send is
// asynchronous — the response confirms enqueue, not delivery.
type EmailCaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `email`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Lifecycle state of the enqueued email. Wire value: `queued`.
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailCaseResponse) Reset() {
	*x = EmailCaseResponse{}
	mi := &file_api_zyins_v1_cases_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCaseResponse) ProtoMessage() {}

func (x *EmailCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_cases_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCaseResponse.ProtoReflect.Descriptor instead.
func (*EmailCaseResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_cases_proto_rawDescGZIP(), []int{5}
}

func (x *EmailCaseResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *EmailCaseResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *EmailCaseResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EmailCaseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// CaseDetail is the canonical case resource shape returned by every
// case RPC. Field numbers 1–3 mirror the platform response envelope;
// the resource fields begin at 4.
type CaseDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `case`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 11-character alphanumeric short hash. Stable identifier for the
	// case across its lifetime.
	Hash string `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	// Canonical agent-facing URL: `https://bestplanpro.com/?case=<hash>`.
	// Provided as a convenience so callers do not reconstruct it.
	Url string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	// True when the case carries cached evaluation results that viewers
	// see verbatim rather than re-running the engine.
	Readonly bool `protobuf:"varint,6,opt,name=readonly,proto3" json:"readonly,omitempty"`
	// RFC 3339 creation timestamp.
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The original applicant inputs, returned only by GetCase. Empty on
	// CreateCase and ListCases responses to keep payloads compact.
	Input *structpb.Value `protobuf:"bytes,8,opt,name=input,proto3" json:"input,omitempty"`
	// The evaluation results stored with the case, returned only by
	// GetCase when the case is readonly. Empty otherwise.
	Results *structpb.Value `protobuf:"bytes,9,opt,name=results,proto3" json:"results,omitempty"`
	// The product slugs the case was evaluated against. Returned by
	// GetCase; empty on CreateCase and ListCases responses.
	Products      []string `protobuf:"bytes,10,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseDetail) Reset() {
	*x = CaseDetail{}
	mi := &file_api_zyins_v1_cases_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseDetail) ProtoMessage() {}

func (x *CaseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_cases_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseDetail.ProtoReflect.Descriptor instead.
func (*CaseDetail) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_cases_proto_rawDescGZIP(), []int{6}
}

func (x *CaseDetail) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *CaseDetail) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *CaseDetail) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CaseDetail) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CaseDetail) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CaseDetail) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *CaseDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CaseDetail) GetInput() *structpb.Value {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CaseDetail) GetResults() *structpb.Value {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CaseDetail) GetProducts() []string {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_api_zyins_v1_cases_proto protoreflect.FileDescriptor

const file_api_zyins_v1_cases_proto_rawDesc = "" +
	"\n" +
	"\x18api/zyins/v1/cases.proto\x12\fapi.zyins.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8f\x01\n" +
	"\x11CreateCaseRequest\x12,\n" +
	"\x05input\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05input\x120\n" +
	"\aresults\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\aresults\x12\x1a\n" +
	"\bproducts\x18\x03 \x03(\tR\bproducts\"$\n" +
	"\x0eGetCaseRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"@\n" +
	"\x10ListCasesRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xd0\x01\n" +
	"\x11ListCasesResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12,\n" +
	"\x04data\x18\x04 \x03(\v2\x18.api.zyins.v1.CaseDetailR\x04data\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x06 \x01(\tR\n" +
	"nextCursor\"d\n" +
	"\x10EmailCaseRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\"~\n" +
	"\x11EmailCaseResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xbc\x02\n" +
	"\n" +
	"CaseDetail\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1a\n" +
	"\breadonly\x18\x06 \x01(\bR\breadonly\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12,\n" +
	"\x05input\x18\b \x01(\v2\x16.google.protobuf.ValueR\x05input\x120\n" +
	"\aresults\x18\t \x01(\v2\x16.google.protobuf.ValueR\aresults\x12\x1a\n" +
	"\bproducts\x18\n" +
	" \x03(\tR\bproducts2\x9a\x03\n" +
	"\fCasesService\x12\\\n" +
	"\n" +
	"CreateCase\x12\x1f.api.zyins.v1.CreateCaseRequest\x1a\x18.api.zyins.v1.CaseDetail\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/case\x12Z\n" +
	"\aGetCase\x12\x1c.api.zyins.v1.GetCaseRequest\x1a\x18.api.zyins.v1.CaseDetail\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/case/{hash}\x12_\n" +
	"\tListCases\x12\x1e.api.zyins.v1.ListCasesRequest\x1a\x1f.api.zyins.v1.ListCasesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/cases\x12o\n" +
	"\tEmailCase\x12\x1e.api.zyins.v1.EmailCaseRequest\x1a\x1f.api.zyins.v1.EmailCaseResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/cases/{hash}/emailB\xc4\x01\n" +
	"\x10com.api.zyins.v1B\n" +
	"CasesProtoP\x01ZJgithub.com/isa-sdk/sdk/zyins/api/zyins/v1;zyinsv1\xa2\x02\x03AZX\xaa\x02\x13IsaSdk.ZyINS.Api.V1\xca\x02\x10Sah\\ZyINS\\Api\\V1\xe2\x02\x15Sah\\ZyINS\\Api\\V1\\Meta\xea\x02\x0eApi::Zyins::V1b\x06proto3"

var (
	file_api_zyins_v1_cases_proto_rawDescOnce sync.Once
	file_api_zyins_v1_cases_proto_rawDescData []byte
)

func file_api_zyins_v1_cases_proto_rawDescGZIP() []byte {
	file_api_zyins_v1_cases_proto_rawDescOnce.Do(func() {
		file_api_zyins_v1_cases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zyins_v1_cases_proto_rawDesc), len(file_api_zyins_v1_cases_proto_rawDesc)))
	})
	return file_api_zyins_v1_cases_proto_rawDescData
}

var file_api_zyins_v1_cases_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_zyins_v1_cases_proto_goTypes = []any{
	(*CreateCaseRequest)(nil), // 0: api.zyins.v1.CreateCaseRequest
	(*GetCaseRequest)(nil),    // 1: api.zyins.v1.GetCaseRequest
	(*ListCasesRequest)(nil),  // 2: api.zyins.v1.ListCasesRequest
	(*ListCasesResponse)(nil), // 3: api.zyins.v1.ListCasesResponse
	(*EmailCaseRequest)(nil),  // 4: api.zyins.v1.EmailCaseRequest
	(*EmailCaseResponse)(nil), // 5: api.zyins.v1.EmailCaseResponse
	(*CaseDetail)(nil),        // 6: api.zyins.v1.CaseDetail
	(*structpb.Value)(nil),    // 7: google.protobuf.Value
}
var file_api_zyins_v1_cases_proto_depIdxs = []int32{
	7, // 0: api.zyins.v1.CreateCaseRequest.input:type_name -> google.protobuf.Value
	7, // 1: api.zyins.v1.CreateCaseRequest.results:type_name -> google.protobuf.Value
	6, // 2: api.zyins.v1.ListCasesResponse.data:type_name -> api.zyins.v1.CaseDetail
	7, // 3: api.zyins.v1.CaseDetail.input:type_name -> google.protobuf.Value
	7, // 4: api.zyins.v1.CaseDetail.results:type_name -> google.protobuf.Value
	0, // 5: api.zyins.v1.CasesService.CreateCase:input_type -> api.zyins.v1.CreateCaseRequest
	1, // 6: api.zyins.v1.CasesService.GetCase:input_type -> api.zyins.v1.GetCaseRequest
	2, // 7: api.zyins.v1.CasesService.ListCases:input_type -> api.zyins.v1.ListCasesRequest
	4, // 8: api.zyins.v1.CasesService.EmailCase:input_type -> api.zyins.v1.EmailCaseRequest
	6, // 9: api.zyins.v1.CasesService.CreateCase:output_type -> api.zyins.v1.CaseDetail
	6, // 10: api.zyins.v1.CasesService.GetCase:output_type -> api.zyins.v1.CaseDetail
	3, // 11: api.zyins.v1.CasesService.ListCases:output_type -> api.zyins.v1.ListCasesResponse
	5, // 12: api.zyins.v1.CasesService.EmailCase:output_type -> api.zyins.v1.EmailCaseResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_zyins_v1_cases_proto_init() }
func file_api_zyins_v1_cases_proto_init() {
	if File_api_zyins_v1_cases_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zyins_v1_cases_proto_rawDesc), len(file_api_zyins_v1_cases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zyins_v1_cases_proto_goTypes,
		DependencyIndexes: file_api_zyins_v1_cases_proto_depIdxs,
		MessageInfos:      file_api_zyins_v1_cases_proto_msgTypes,
	}.Build()
	File_api_zyins_v1_cases_proto = out.File
	file_api_zyins_v1_cases_proto_goTypes = nil
	file_api_zyins_v1_cases_proto_depIdxs = nil
}
