// Package api.zyins.v1 contains the canonical protobuf definitions for the
// ZyINS Unified API (see /services/zyins, historically go/zyins). Under
// ADR-016 these protos are the source of truth; the OpenAPI YAML consumed
// by ReadMe is regenerated from them.
//
// common.proto holds the shared envelope and the zyins-specific
// cross-resource enumerations. Cross-service types (ProblemDetails,
// ErrorCode, Scope, the health probe contract) live in
// `api/isa/v1/common.proto` and `api/isa/v1/health.proto`; sibling protos
// should import those files directly when they reference shared types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/zyins/v1/common.proto

package zyinsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gender captures biological sex for underwriting. Canonical wire values
// are lowercase full words (`male`, `female`) per ADR-012. The server
// normalizes legacy inputs (`M`, `F`, `Male`) to canonical values in
// responses.
type Gender int32

const (
	// Default zero value. Never emitted by the server.
	Gender_GENDER_UNSPECIFIED Gender = 0
	// Male biological sex for underwriting (wire value: `male`).
	Gender_GENDER_MALE Gender = 1
	// Female biological sex for underwriting (wire value: `female`).
	Gender_GENDER_FEMALE Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zyins_v1_common_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_api_zyins_v1_common_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_api_zyins_v1_common_proto_rawDescGZIP(), []int{0}
}

// TokenStatus is the API token lifecycle state per ADR-012.
type TokenStatus int32

const (
	// Default zero value. Never emitted by the server.
	TokenStatus_TOKEN_STATUS_UNSPECIFIED TokenStatus = 0
	// Token is usable (wire: `active`).
	TokenStatus_TOKEN_STATUS_ACTIVE TokenStatus = 1
	// Token was intentionally terminated (wire: `revoked`). Permanent.
	TokenStatus_TOKEN_STATUS_REVOKED TokenStatus = 2
	// Token aged out of its validity window (wire: `expired`). Permanent.
	TokenStatus_TOKEN_STATUS_EXPIRED TokenStatus = 3
	// Token was permanently banned by an administrator (wire: `banned`).
	// Unlike revoked, a banned token can never be reinstated.
	TokenStatus_TOKEN_STATUS_BANNED TokenStatus = 4
)

// Enum value maps for TokenStatus.
var (
	TokenStatus_name = map[int32]string{
		0: "TOKEN_STATUS_UNSPECIFIED",
		1: "TOKEN_STATUS_ACTIVE",
		2: "TOKEN_STATUS_REVOKED",
		3: "TOKEN_STATUS_EXPIRED",
		4: "TOKEN_STATUS_BANNED",
	}
	TokenStatus_value = map[string]int32{
		"TOKEN_STATUS_UNSPECIFIED": 0,
		"TOKEN_STATUS_ACTIVE":      1,
		"TOKEN_STATUS_REVOKED":     2,
		"TOKEN_STATUS_EXPIRED":     3,
		"TOKEN_STATUS_BANNED":      4,
	}
)

func (x TokenStatus) Enum() *TokenStatus {
	p := new(TokenStatus)
	*p = x
	return p
}

func (x TokenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zyins_v1_common_proto_enumTypes[1].Descriptor()
}

func (TokenStatus) Type() protoreflect.EnumType {
	return &file_api_zyins_v1_common_proto_enumTypes[1]
}

func (x TokenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenStatus.Descriptor instead.
func (TokenStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_zyins_v1_common_proto_rawDescGZIP(), []int{1}
}

// AccountStatus is the account lifecycle state per ADR-012.
type AccountStatus int32

const (
	// Default zero value. Never emitted by the server.
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	// Account is in normal operation (wire: `active`).
	AccountStatus_ACCOUNT_STATUS_ACTIVE AccountStatus = 1
	// Reversible admin hold (wire: `suspended`).
	AccountStatus_ACCOUNT_STATUS_SUSPENDED AccountStatus = 2
	// Permanent admin closure; archival only (wire: `closed`).
	AccountStatus_ACCOUNT_STATUS_CLOSED AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_ACTIVE",
		2: "ACCOUNT_STATUS_SUSPENDED",
		3: "ACCOUNT_STATUS_CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_ACTIVE":      1,
		"ACCOUNT_STATUS_SUSPENDED":   2,
		"ACCOUNT_STATUS_CLOSED":      3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zyins_v1_common_proto_enumTypes[2].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_api_zyins_v1_common_proto_enumTypes[2]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_zyins_v1_common_proto_rawDescGZIP(), []int{2}
}

// LicenseStatus is the license validation state.
type LicenseStatus int32

const (
	// Default zero value. Never emitted by the server.
	LicenseStatus_LICENSE_STATUS_UNSPECIFIED LicenseStatus = 0
	// License is authenticated and currently usable (wire: `valid`).
	LicenseStatus_LICENSE_STATUS_VALID LicenseStatus = 1
	// Credentials do not match a known license (wire: `invalid`).
	LicenseStatus_LICENSE_STATUS_INVALID LicenseStatus = 2
	// License exists but is not currently usable (wire: `inactive`).
	LicenseStatus_LICENSE_STATUS_INACTIVE LicenseStatus = 3
)

// Enum value maps for LicenseStatus.
var (
	LicenseStatus_name = map[int32]string{
		0: "LICENSE_STATUS_UNSPECIFIED",
		1: "LICENSE_STATUS_VALID",
		2: "LICENSE_STATUS_INVALID",
		3: "LICENSE_STATUS_INACTIVE",
	}
	LicenseStatus_value = map[string]int32{
		"LICENSE_STATUS_UNSPECIFIED": 0,
		"LICENSE_STATUS_VALID":       1,
		"LICENSE_STATUS_INVALID":     2,
		"LICENSE_STATUS_INACTIVE":    3,
	}
)

func (x LicenseStatus) Enum() *LicenseStatus {
	p := new(LicenseStatus)
	*p = x
	return p
}

func (x LicenseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LicenseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zyins_v1_common_proto_enumTypes[3].Descriptor()
}

func (LicenseStatus) Type() protoreflect.EnumType {
	return &file_api_zyins_v1_common_proto_enumTypes[3]
}

func (x LicenseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LicenseStatus.Descriptor instead.
func (LicenseStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_zyins_v1_common_proto_rawDescGZIP(), []int{3}
}

// ProductClass is the insurance product family classification.
type ProductClass int32

const (
	// Default zero value. Never emitted by the server.
	ProductClass_PRODUCT_CLASS_UNSPECIFIED ProductClass = 0
	// Final expense (wire: `fex`).
	ProductClass_PRODUCT_CLASS_FEX ProductClass = 1
	// Term life (wire: `term`).
	ProductClass_PRODUCT_CLASS_TERM ProductClass = 2
	// Medicare supplement (wire: `medsup`).
	ProductClass_PRODUCT_CLASS_MEDSUP ProductClass = 3
	// Pre-need funeral (wire: `preneed`).
	ProductClass_PRODUCT_CLASS_PRENEED ProductClass = 4
	// Whole life (wire: `wl`).
	ProductClass_PRODUCT_CLASS_WL ProductClass = 5
)

// Enum value maps for ProductClass.
var (
	ProductClass_name = map[int32]string{
		0: "PRODUCT_CLASS_UNSPECIFIED",
		1: "PRODUCT_CLASS_FEX",
		2: "PRODUCT_CLASS_TERM",
		3: "PRODUCT_CLASS_MEDSUP",
		4: "PRODUCT_CLASS_PRENEED",
		5: "PRODUCT_CLASS_WL",
	}
	ProductClass_value = map[string]int32{
		"PRODUCT_CLASS_UNSPECIFIED": 0,
		"PRODUCT_CLASS_FEX":         1,
		"PRODUCT_CLASS_TERM":        2,
		"PRODUCT_CLASS_MEDSUP":      3,
		"PRODUCT_CLASS_PRENEED":     4,
		"PRODUCT_CLASS_WL":          5,
	}
)

func (x ProductClass) Enum() *ProductClass {
	p := new(ProductClass)
	*p = x
	return p
}

func (x ProductClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductClass) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zyins_v1_common_proto_enumTypes[4].Descriptor()
}

func (ProductClass) Type() protoreflect.EnumType {
	return &file_api_zyins_v1_common_proto_enumTypes[4]
}

func (x ProductClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductClass.Descriptor instead.
func (ProductClass) EnumDescriptor() ([]byte, []int) {
	return file_api_zyins_v1_common_proto_rawDescGZIP(), []int{4}
}

// DeathBenefitRank is the underwriting rank category.
type DeathBenefitRank int32

const (
	// Default zero value. Never emitted by the server.
	DeathBenefitRank_DEATH_BENEFIT_RANK_UNSPECIFIED DeathBenefitRank = 0
	// Policy takes effect immediately (wire: `immediate`).
	DeathBenefitRank_DEATH_BENEFIT_RANK_IMMEDIATE DeathBenefitRank = 1
	// Waiting period applies (wire: `graded`).
	DeathBenefitRank_DEATH_BENEFIT_RANK_GRADED DeathBenefitRank = 2
	// Return of premium (wire: `rop`).
	DeathBenefitRank_DEATH_BENEFIT_RANK_ROP DeathBenefitRank = 3
	// Remaining classifications (wire: `other`).
	DeathBenefitRank_DEATH_BENEFIT_RANK_OTHER DeathBenefitRank = 4
)

// Enum value maps for DeathBenefitRank.
var (
	DeathBenefitRank_name = map[int32]string{
		0: "DEATH_BENEFIT_RANK_UNSPECIFIED",
		1: "DEATH_BENEFIT_RANK_IMMEDIATE",
		2: "DEATH_BENEFIT_RANK_GRADED",
		3: "DEATH_BENEFIT_RANK_ROP",
		4: "DEATH_BENEFIT_RANK_OTHER",
	}
	DeathBenefitRank_value = map[string]int32{
		"DEATH_BENEFIT_RANK_UNSPECIFIED": 0,
		"DEATH_BENEFIT_RANK_IMMEDIATE":   1,
		"DEATH_BENEFIT_RANK_GRADED":      2,
		"DEATH_BENEFIT_RANK_ROP":         3,
		"DEATH_BENEFIT_RANK_OTHER":       4,
	}
)

func (x DeathBenefitRank) Enum() *DeathBenefitRank {
	p := new(DeathBenefitRank)
	*p = x
	return p
}

func (x DeathBenefitRank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeathBenefitRank) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zyins_v1_common_proto_enumTypes[5].Descriptor()
}

func (DeathBenefitRank) Type() protoreflect.EnumType {
	return &file_api_zyins_v1_common_proto_enumTypes[5]
}

func (x DeathBenefitRank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeathBenefitRank.Descriptor instead.
func (DeathBenefitRank) EnumDescriptor() ([]byte, []int) {
	return file_api_zyins_v1_common_proto_rawDescGZIP(), []int{5}
}

// QuoteType is the quote computation mode.
type QuoteType int32

const (
	// Default zero value. Never emitted by the server.
	QuoteType_QUOTE_TYPE_UNSPECIFIED QuoteType = 0
	// Compute premiums for given face-value amounts (wire: `face_amounts`).
	QuoteType_QUOTE_TYPE_FACE_AMOUNTS QuoteType = 1
	// Compute coverage achievable for a given monthly budget (wire: `monthly_budget`).
	QuoteType_QUOTE_TYPE_MONTHLY_BUDGET QuoteType = 2
)

// Enum value maps for QuoteType.
var (
	QuoteType_name = map[int32]string{
		0: "QUOTE_TYPE_UNSPECIFIED",
		1: "QUOTE_TYPE_FACE_AMOUNTS",
		2: "QUOTE_TYPE_MONTHLY_BUDGET",
	}
	QuoteType_value = map[string]int32{
		"QUOTE_TYPE_UNSPECIFIED":    0,
		"QUOTE_TYPE_FACE_AMOUNTS":   1,
		"QUOTE_TYPE_MONTHLY_BUDGET": 2,
	}
)

func (x QuoteType) Enum() *QuoteType {
	p := new(QuoteType)
	*p = x
	return p
}

func (x QuoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zyins_v1_common_proto_enumTypes[6].Descriptor()
}

func (QuoteType) Type() protoreflect.EnumType {
	return &file_api_zyins_v1_common_proto_enumTypes[6]
}

func (x QuoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuoteType.Descriptor instead.
func (QuoteType) EnumDescriptor() ([]byte, []int) {
	return file_api_zyins_v1_common_proto_rawDescGZIP(), []int{6}
}

// Envelope is the standard response wrapper per the response-envelope
// contract. Every success response carries `object`, `livemode`, and
// `request_id`; resource-specific bodies live in a typed `data` field on
// each response message (not this shared type — proto does not inherit).
// This message exists for documentation of the contract; concrete
// responses duplicate the three fields explicitly so each has a typed
// `data` shape rather than a `google.protobuf.Any`.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Concrete values depend on the endpoint
	// (e.g. "quote_result", "license", "token").
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True in production; false for test-mode responses.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier; echoed into all log lines for the request.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Endpoint-specific payload. Concrete responses replace this with a
	// typed message; it appears here only to document the envelope shape.
	Data          *structpb.Value `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_api_zyins_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *Envelope) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_zyins_v1_common_proto protoreflect.FileDescriptor

const file_api_zyins_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19api/zyins/v1/common.proto\x12\fapi.zyins.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x89\x01\n" +
	"\bEnvelope\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12*\n" +
	"\x04data\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x04data*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02*\x91\x01\n" +
	"\vTokenStatus\x12\x1c\n" +
	"\x18TOKEN_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TOKEN_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14TOKEN_STATUS_REVOKED\x10\x02\x12\x18\n" +
	"\x14TOKEN_STATUS_EXPIRED\x10\x03\x12\x17\n" +
	"\x13TOKEN_STATUS_BANNED\x10\x04*\x83\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18ACCOUNT_STATUS_SUSPENDED\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_STATUS_CLOSED\x10\x03*\x82\x01\n" +
	"\rLicenseStatus\x12\x1e\n" +
	"\x1aLICENSE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LICENSE_STATUS_VALID\x10\x01\x12\x1a\n" +
	"\x16LICENSE_STATUS_INVALID\x10\x02\x12\x1b\n" +
	"\x17LICENSE_STATUS_INACTIVE\x10\x03*\xa7\x01\n" +
	"\fProductClass\x12\x1d\n" +
	"\x19PRODUCT_CLASS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRODUCT_CLASS_FEX\x10\x01\x12\x16\n" +
	"\x12PRODUCT_CLASS_TERM\x10\x02\x12\x18\n" +
	"\x14PRODUCT_CLASS_MEDSUP\x10\x03\x12\x19\n" +
	"\x15PRODUCT_CLASS_PRENEED\x10\x04\x12\x14\n" +
	"\x10PRODUCT_CLASS_WL\x10\x05*\xb1\x01\n" +
	"\x10DeathBenefitRank\x12\"\n" +
	"\x1eDEATH_BENEFIT_RANK_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cDEATH_BENEFIT_RANK_IMMEDIATE\x10\x01\x12\x1d\n" +
	"\x19DEATH_BENEFIT_RANK_GRADED\x10\x02\x12\x1a\n" +
	"\x16DEATH_BENEFIT_RANK_ROP\x10\x03\x12\x1c\n" +
	"\x18DEATH_BENEFIT_RANK_OTHER\x10\x04*c\n" +
	"\tQuoteType\x12\x1a\n" +
	"\x16QUOTE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17QUOTE_TYPE_FACE_AMOUNTS\x10\x01\x12\x1d\n" +
	"\x19QUOTE_TYPE_MONTHLY_BUDGET\x10\x02B\xc5\x01\n" +
	"\x10com.api.zyins.v1B\vCommonProtoP\x01ZJgithub.com/isa-sdk/sdk/zyins/api/zyins/v1;zyinsv1\xa2\x02\x03AZX\xaa\x02\x13IsaSdk.ZyINS.Api.V1\xca\x02\x10Sah\\ZyINS\\Api\\V1\xe2\x02\x15Sah\\ZyINS\\Api\\V1\\Meta\xea\x02\x0eApi::Zyins::V1b\x06proto3"

var (
	file_api_zyins_v1_common_proto_rawDescOnce sync.Once
	file_api_zyins_v1_common_proto_rawDescData []byte
)

func file_api_zyins_v1_common_proto_rawDescGZIP() []byte {
	file_api_zyins_v1_common_proto_rawDescOnce.Do(func() {
		file_api_zyins_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zyins_v1_common_proto_rawDesc), len(file_api_zyins_v1_common_proto_rawDesc)))
	})
	return file_api_zyins_v1_common_proto_rawDescData
}

var file_api_zyins_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_api_zyins_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_zyins_v1_common_proto_goTypes = []any{
	(Gender)(0),            // 0: api.zyins.v1.Gender
	(TokenStatus)(0),       // 1: api.zyins.v1.TokenStatus
	(AccountStatus)(0),     // 2: api.zyins.v1.AccountStatus
	(LicenseStatus)(0),     // 3: api.zyins.v1.LicenseStatus
	(ProductClass)(0),      // 4: api.zyins.v1.ProductClass
	(DeathBenefitRank)(0),  // 5: api.zyins.v1.DeathBenefitRank
	(QuoteType)(0),         // 6: api.zyins.v1.QuoteType
	(*Envelope)(nil),       // 7: api.zyins.v1.Envelope
	(*structpb.Value)(nil), // 8: google.protobuf.Value
}
var file_api_zyins_v1_common_proto_depIdxs = []int32{
	8, // 0: api.zyins.v1.Envelope.data:type_name -> google.protobuf.Value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_zyins_v1_common_proto_init() }
func file_api_zyins_v1_common_proto_init() {
	if File_api_zyins_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zyins_v1_common_proto_rawDesc), len(file_api_zyins_v1_common_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_zyins_v1_common_proto_goTypes,
		DependencyIndexes: file_api_zyins_v1_common_proto_depIdxs,
		EnumInfos:         file_api_zyins_v1_common_proto_enumTypes,
		MessageInfos:      file_api_zyins_v1_common_proto_msgTypes,
	}.Build()
	File_api_zyins_v1_common_proto = out.File
	file_api_zyins_v1_common_proto_goTypes = nil
	file_api_zyins_v1_common_proto_depIdxs = nil
}
