// email.proto defines the account-scoped transactional email enqueue
// surface for the ZyINS Unified API. Mounted at
// `zyins.isaapi.com/v1/email/enqueue`.
//
// The send path is asynchronous: the handler validates and persists the
// payload to `email_queue`, and a worker drains the queue through the
// configured transport (Postmark for credentials/transactional, Resend
// for rapidsign signer notifications). The response confirms enqueue,
// not delivery.
//
// Per-account isolation: every row carries the calling account; cross-
// account queue inspection is not exposed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/zyins/v1/email.proto

package zyinsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnqueueEmailRequest is the body for POST /v1/email/enqueue.
//
// The server constructs the canonical `From` header from a verified
// brand domain — callers cannot set it. `template`/`template_data` are
// reserved for future server-rendered templates; current callers
// supply the rendered HTML in `body`.
type EnqueueEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipient email address. Required; RFC 5322 valid.
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// Subject line. Required; non-empty after trim.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Rendered HTML email body. Required. The transport sends as
	// `text/html`; clients that need a plaintext alternative should
	// include it server-side once template support ships.
	Body string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Server-rendered template identifier. Reserved for future use;
	// ignored by current handlers. Optional.
	Template string `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	// Substitution data for the template. Reserved for future use;
	// ignored by current handlers. Optional.
	TemplateData *structpb.Value `protobuf:"bytes,5,opt,name=template_data,json=templateData,proto3" json:"template_data,omitempty"`
	// Address to set as `Reply-To`. Optional; falls back to the
	// configured no-reply when empty.
	ReplyTo string `protobuf:"bytes,6,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// Attachments to include on the message. Total decoded size is
	// capped per the platform's transport limit; oversize attachments
	// are rejected at enqueue time. Optional.
	Attachments   []*EmailAttachment `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueEmailRequest) Reset() {
	*x = EnqueueEmailRequest{}
	mi := &file_api_zyins_v1_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueEmailRequest) ProtoMessage() {}

func (x *EnqueueEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueEmailRequest.ProtoReflect.Descriptor instead.
func (*EnqueueEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_email_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EnqueueEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EnqueueEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EnqueueEmailRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *EnqueueEmailRequest) GetTemplateData() *structpb.Value {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *EnqueueEmailRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *EnqueueEmailRequest) GetAttachments() []*EmailAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// EmailAttachment is a single base64-encoded file to include with the
// outbound email. The transport infers content-type from the filename
// extension; explicit MIME types are not accepted from clients.
type EmailAttachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display filename. Must not contain path separators, null bytes,
	// CR/LF, or a leading dot. Required.
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// Base64-encoded file bytes. Required. Decoded size must fit within
	// the per-attachment ceiling enforced at enqueue time.
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAttachment) Reset() {
	*x = EmailAttachment{}
	mi := &file_api_zyins_v1_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAttachment) ProtoMessage() {}

func (x *EmailAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAttachment.ProtoReflect.Descriptor instead.
func (*EmailAttachment) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_email_proto_rawDescGZIP(), []int{1}
}

func (x *EmailAttachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EmailAttachment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// EnqueueEmailResponse is the 202 body from EnqueueEmail.
type EnqueueEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `email`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Lifecycle state of the enqueued email. Wire value: `queued`.
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueEmailResponse) Reset() {
	*x = EnqueueEmailResponse{}
	mi := &file_api_zyins_v1_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueEmailResponse) ProtoMessage() {}

func (x *EnqueueEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueEmailResponse.ProtoReflect.Descriptor instead.
func (*EnqueueEmailResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_email_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueEmailResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *EnqueueEmailResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *EnqueueEmailResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EnqueueEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_zyins_v1_email_proto protoreflect.FileDescriptor

const file_api_zyins_v1_email_proto_rawDesc = "" +
	"\n" +
	"\x18api/zyins/v1/email.proto\x12\fapi.zyins.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x88\x02\n" +
	"\x13EnqueueEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1a\n" +
	"\btemplate\x18\x04 \x01(\tR\btemplate\x12;\n" +
	"\rtemplate_data\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\ftemplateData\x12\x19\n" +
	"\breply_to\x18\x06 \x01(\tR\areplyTo\x12?\n" +
	"\vattachments\x18\a \x03(\v2\x1d.api.zyins.v1.EmailAttachmentR\vattachments\"G\n" +
	"\x0fEmailAttachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x81\x01\n" +
	"\x14EnqueueEmailResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\x83\x01\n" +
	"\fEmailService\x12s\n" +
	"\fEnqueueEmail\x12!.api.zyins.v1.EnqueueEmailRequest\x1a\".api.zyins.v1.EnqueueEmailResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/email/enqueueB\xc4\x01\n" +
	"\x10com.api.zyins.v1B\n" +
	"EmailProtoP\x01ZJgithub.com/isa-sdk/sdk/zyins/api/zyins/v1;zyinsv1\xa2\x02\x03AZX\xaa\x02\x13IsaSdk.ZyINS.Api.V1\xca\x02\x10Sah\\ZyINS\\Api\\V1\xe2\x02\x15Sah\\ZyINS\\Api\\V1\\Meta\xea\x02\x0eApi::Zyins::V1b\x06proto3"

var (
	file_api_zyins_v1_email_proto_rawDescOnce sync.Once
	file_api_zyins_v1_email_proto_rawDescData []byte
)

func file_api_zyins_v1_email_proto_rawDescGZIP() []byte {
	file_api_zyins_v1_email_proto_rawDescOnce.Do(func() {
		file_api_zyins_v1_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zyins_v1_email_proto_rawDesc), len(file_api_zyins_v1_email_proto_rawDesc)))
	})
	return file_api_zyins_v1_email_proto_rawDescData
}

var file_api_zyins_v1_email_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_zyins_v1_email_proto_goTypes = []any{
	(*EnqueueEmailRequest)(nil),  // 0: api.zyins.v1.EnqueueEmailRequest
	(*EmailAttachment)(nil),      // 1: api.zyins.v1.EmailAttachment
	(*EnqueueEmailResponse)(nil), // 2: api.zyins.v1.EnqueueEmailResponse
	(*structpb.Value)(nil),       // 3: google.protobuf.Value
}
var file_api_zyins_v1_email_proto_depIdxs = []int32{
	3, // 0: api.zyins.v1.EnqueueEmailRequest.template_data:type_name -> google.protobuf.Value
	1, // 1: api.zyins.v1.EnqueueEmailRequest.attachments:type_name -> api.zyins.v1.EmailAttachment
	0, // 2: api.zyins.v1.EmailService.EnqueueEmail:input_type -> api.zyins.v1.EnqueueEmailRequest
	2, // 3: api.zyins.v1.EmailService.EnqueueEmail:output_type -> api.zyins.v1.EnqueueEmailResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_zyins_v1_email_proto_init() }
func file_api_zyins_v1_email_proto_init() {
	if File_api_zyins_v1_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zyins_v1_email_proto_rawDesc), len(file_api_zyins_v1_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zyins_v1_email_proto_goTypes,
		DependencyIndexes: file_api_zyins_v1_email_proto_depIdxs,
		MessageInfos:      file_api_zyins_v1_email_proto_msgTypes,
	}.Build()
	File_api_zyins_v1_email_proto = out.File
	file_api_zyins_v1_email_proto_goTypes = nil
	file_api_zyins_v1_email_proto_depIdxs = nil
}
