// tokens.proto defines the API-token management surface for the ZyINS
// Unified API. Every RPC here is authenticated with BearerAuth (ADR-013);
// tokens are the credential type used to call the public compute surface
// (prequalify, quote, datasets). All routes are mounted under
// `zyins.isaapi.com/v1/tokens`.
//
// Token values are returned in plaintext only on Create and Rotate;
// every other response returns a redacted `hint` (last four characters)
// plus metadata.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/zyins/v1/tokens.proto

package zyinsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListTokensRequest is the empty request body for GET /v1/tokens. The
// auth context identifies the account whose tokens are listed.
type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{0}
}

// ListTokensResponse mirrors the shipped `TokenListResponse` shape.
type ListTokensResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `list`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The tokens owned by the authenticated account, redacted.
	Data          []*TokenDetail `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *ListTokensResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ListTokensResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *ListTokensResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListTokensResponse) GetData() []*TokenDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

// CreateTokenRequest is the body for POST /v1/tokens.
type CreateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable label for the token (e.g. "Production API key").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Permission scopes granted to this token (e.g. ["prequalify",
	// "datasets"]).
	Scopes []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Number of days until the token expires. Zero or absent means the
	// token does not expire on a fixed schedule.
	ExpiresInDays int32 `protobuf:"varint,3,opt,name=expires_in_days,json=expiresInDays,proto3" json:"expires_in_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateTokenRequest) GetExpiresInDays() int32 {
	if x != nil {
		return x.ExpiresInDays
	}
	return 0
}

// CreateTokenResponse is the 201 body for Create and the 200 body for
// Rotate. This is the only shape that carries the plaintext `token`.
type CreateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `token`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Token identifier (e.g. `tok_abc123def456`).
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// The full plaintext token value. Only returned here and on rotation.
	Token string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	// Human-readable label.
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Last four characters of the token, used for later identification.
	Hint string `protobuf:"bytes,7,opt,name=hint,proto3" json:"hint,omitempty"`
	// Permission scopes granted to this token.
	Scopes []string `protobuf:"bytes,8,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// RFC 3339 creation timestamp.
	CreatedAt string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// RFC 3339 expiry timestamp. Empty string means the token does not
	// expire.
	ExpiresAt string `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// RFC 3339 timestamp at which the *previous* token is scheduled to
	// revoke. Populated only on Rotate responses with a non-zero grace
	// window; empty on Create or immediate revocation. Task #117.
	PreviousTokenRevokesAt string `protobuf:"bytes,11,opt,name=previous_token_revokes_at,json=previousTokenRevokesAt,proto3" json:"previous_token_revokes_at,omitempty"`
	// Identifier of the *previous* token (the one being rotated).
	// Populated only on Rotate responses; empty on Create. Task #117.
	PreviousTokenId string `protobuf:"bytes,12,opt,name=previous_token_id,json=previousTokenId,proto3" json:"previous_token_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTokenResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *CreateTokenResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *CreateTokenResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateTokenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenResponse) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *CreateTokenResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateTokenResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreateTokenResponse) GetPreviousTokenRevokesAt() string {
	if x != nil {
		return x.PreviousTokenRevokesAt
	}
	return ""
}

func (x *CreateTokenResponse) GetPreviousTokenId() string {
	if x != nil {
		return x.PreviousTokenId
	}
	return ""
}

// GetTokenRequest identifies a token by its database ID.
type GetTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token identifier (path parameter).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteTokenRequest identifies a token to revoke without a reason.
// Deprecated path; use RevokeTokenRequest instead.
type DeleteTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token identifier (path parameter).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenRequest) Reset() {
	*x = DeleteTokenRequest{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenRequest) ProtoMessage() {}

func (x *DeleteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteTokenResponse is the empty 204 body from Delete.
type DeleteTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenResponse) Reset() {
	*x = DeleteTokenResponse{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenResponse) ProtoMessage() {}

func (x *DeleteTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{6}
}

// RevokeTokenRequest records the reason for a token revocation.
type RevokeTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token identifier (path parameter).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Operator-supplied reason captured in the audit log.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RevokeTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReinstateTokenRequest targets a previously revoked token.
type ReinstateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token identifier (path parameter).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReinstateTokenRequest) Reset() {
	*x = ReinstateTokenRequest{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReinstateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReinstateTokenRequest) ProtoMessage() {}

func (x *ReinstateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReinstateTokenRequest.ProtoReflect.Descriptor instead.
func (*ReinstateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{8}
}

func (x *ReinstateTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// BanTokenRequest permanently bans a token and records the reason.
type BanTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token identifier (path parameter).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Operator-supplied reason captured in the audit log.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanTokenRequest) Reset() {
	*x = BanTokenRequest{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanTokenRequest) ProtoMessage() {}

func (x *BanTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanTokenRequest.ProtoReflect.Descriptor instead.
func (*BanTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{9}
}

func (x *BanTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BanTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RotateTokenRequest targets an existing token; the server issues a new
// token with the same scopes and schedules the old one for revocation
// after a grace window.
type RotateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the token to rotate. May be supplied as the
	// path parameter on `/v1/tokens/{token_id}/rotate` or in the
	// request body on the legacy `/v1/tokens/rotate` binding.
	TokenId string `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// Expiry for the replacement token in days. Zero or absent keeps the
	// original expiry policy.
	ExpiresInDays int32 `protobuf:"varint,2,opt,name=expires_in_days,json=expiresInDays,proto3" json:"expires_in_days,omitempty"`
	// Seconds the old token remains active after rotation before the
	// sweeper revokes it. Absent applies the default 2,592,000 (30
	// days). Range 0 to 7,776,000 (90 days). Explicit 0 revokes the old
	// token immediately; the new token still ships in the response.
	//
	// Task #117 + #118: handler stamps `revokes_at = now() +
	// grace_period_seconds`; the sweeper Lambda flips status to
	// `revoked` when the deadline elapses.
	GracePeriodSeconds *int32 `protobuf:"varint,3,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3,oneof" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RotateTokenRequest) Reset() {
	*x = RotateTokenRequest{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateTokenRequest) ProtoMessage() {}

func (x *RotateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateTokenRequest.ProtoReflect.Descriptor instead.
func (*RotateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{10}
}

func (x *RotateTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *RotateTokenRequest) GetExpiresInDays() int32 {
	if x != nil {
		return x.ExpiresInDays
	}
	return 0
}

func (x *RotateTokenRequest) GetGracePeriodSeconds() int32 {
	if x != nil && x.GracePeriodSeconds != nil {
		return *x.GracePeriodSeconds
	}
	return 0
}

// TokenDetail is the canonical token resource shape returned by every
// read and lifecycle-transition endpoint (except Create and Rotate,
// which additionally return the plaintext token value).
type TokenDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type discriminator. Wire value: `token`.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// True for live mode, false for test mode.
	Livemode bool `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// Unique request identifier.
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Token identifier (e.g. `tok_abc123def456`).
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable label.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Last four characters of the token.
	Hint string `protobuf:"bytes,6,opt,name=hint,proto3" json:"hint,omitempty"`
	// Permission scopes granted to this token.
	Scopes []string `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Current lifecycle state.
	Status TokenStatus `protobuf:"varint,8,opt,name=status,proto3,enum=api.zyins.v1.TokenStatus" json:"status,omitempty"`
	// Reason recorded when the token was revoked or banned. Empty
	// otherwise.
	RevokedReason string `protobuf:"bytes,9,opt,name=revoked_reason,json=revokedReason,proto3" json:"revoked_reason,omitempty"`
	// RFC 3339 creation timestamp.
	CreatedAt string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// RFC 3339 expiry timestamp. Empty string means the token does not
	// expire.
	ExpiresAt string `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// RFC 3339 revocation timestamp. Empty string if the token has never
	// been revoked.
	RevokedAt string `protobuf:"bytes,12,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// RFC 3339 timestamp of the most recent authenticated request made
	// with this token. Empty string if the token has never been used.
	LastUsedAt string `protobuf:"bytes,13,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	// RFC 3339 timestamp at which the sweeper will revoke this token.
	// Set when the token has been replaced via Rotate but its grace
	// window has not yet elapsed. Empty string when no rotation is
	// pending. Task #117 + #118.
	RevokesAt     string `protobuf:"bytes,14,opt,name=revokes_at,json=revokesAt,proto3" json:"revokes_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDetail) Reset() {
	*x = TokenDetail{}
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDetail) ProtoMessage() {}

func (x *TokenDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_zyins_v1_tokens_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDetail.ProtoReflect.Descriptor instead.
func (*TokenDetail) Descriptor() ([]byte, []int) {
	return file_api_zyins_v1_tokens_proto_rawDescGZIP(), []int{11}
}

func (x *TokenDetail) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *TokenDetail) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *TokenDetail) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TokenDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenDetail) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *TokenDetail) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *TokenDetail) GetStatus() TokenStatus {
	if x != nil {
		return x.Status
	}
	return TokenStatus_TOKEN_STATUS_UNSPECIFIED
}

func (x *TokenDetail) GetRevokedReason() string {
	if x != nil {
		return x.RevokedReason
	}
	return ""
}

func (x *TokenDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TokenDetail) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *TokenDetail) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

func (x *TokenDetail) GetLastUsedAt() string {
	if x != nil {
		return x.LastUsedAt
	}
	return ""
}

func (x *TokenDetail) GetRevokesAt() string {
	if x != nil {
		return x.RevokesAt
	}
	return ""
}

var File_api_zyins_v1_tokens_proto protoreflect.FileDescriptor

const file_api_zyins_v1_tokens_proto_rawDesc = "" +
	"\n" +
	"\x19api/zyins/v1/tokens.proto\x12\fapi.zyins.v1\x1a\x19api/zyins/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\x13\n" +
	"\x11ListTokensRequest\"\x96\x01\n" +
	"\x12ListTokensResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12-\n" +
	"\x04data\x18\x04 \x03(\v2\x19.api.zyins.v1.TokenDetailR\x04data\"h\n" +
	"\x12CreateTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\x12&\n" +
	"\x0fexpires_in_days\x18\x03 \x01(\x05R\rexpiresInDays\"\xf3\x02\n" +
	"\x13CreateTokenResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04hint\x18\a \x01(\tR\x04hint\x12\x16\n" +
	"\x06scopes\x18\b \x03(\tR\x06scopes\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tR\texpiresAt\x129\n" +
	"\x19previous_token_revokes_at\x18\v \x01(\tR\x16previousTokenRevokesAt\x12*\n" +
	"\x11previous_token_id\x18\f \x01(\tR\x0fpreviousTokenId\"!\n" +
	"\x0fGetTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteTokenResponse\"<\n" +
	"\x12RevokeTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"'\n" +
	"\x15ReinstateTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x0fBanTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa7\x01\n" +
	"\x12RotateTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12&\n" +
	"\x0fexpires_in_days\x18\x02 \x01(\x05R\rexpiresInDays\x125\n" +
	"\x14grace_period_seconds\x18\x03 \x01(\x05H\x00R\x12gracePeriodSeconds\x88\x01\x01B\x17\n" +
	"\x15_grace_period_seconds\"\xa8\x03\n" +
	"\vTokenDetail\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04hint\x18\x06 \x01(\tR\x04hint\x12\x16\n" +
	"\x06scopes\x18\a \x03(\tR\x06scopes\x121\n" +
	"\x06status\x18\b \x01(\x0e2\x19.api.zyins.v1.TokenStatusR\x06status\x12%\n" +
	"\x0erevoked_reason\x18\t \x01(\tR\rrevokedReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\v \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\f \x01(\tR\trevokedAt\x12 \n" +
	"\flast_used_at\x18\r \x01(\tR\n" +
	"lastUsedAt\x12\x1d\n" +
	"\n" +
	"revokes_at\x18\x0e \x01(\tR\trevokesAt2\xe5\x06\n" +
	"\rTokensService\x12]\n" +
	"\x04List\x12\x1f.api.zyins.v1.ListTokensRequest\x1a .api.zyins.v1.ListTokensResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/tokens\x12d\n" +
	"\x06Create\x12 .api.zyins.v1.CreateTokenRequest\x1a!.api.zyins.v1.CreateTokenResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/tokens\x12X\n" +
	"\x03Get\x12\x1d.api.zyins.v1.GetTokenRequest\x1a\x19.api.zyins.v1.TokenDetail\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/tokens/{id}\x12f\n" +
	"\x06Delete\x12 .api.zyins.v1.DeleteTokenRequest\x1a!.api.zyins.v1.DeleteTokenResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/tokens/{id}\x12h\n" +
	"\x06Revoke\x12 .api.zyins.v1.RevokeTokenRequest\x1a\x19.api.zyins.v1.TokenDetail\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/tokens/{id}/revoke\x12q\n" +
	"\tReinstate\x12#.api.zyins.v1.ReinstateTokenRequest\x1a\x19.api.zyins.v1.TokenDetail\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/tokens/{id}/reinstate\x12_\n" +
	"\x03Ban\x12\x1d.api.zyins.v1.BanTokenRequest\x1a\x19.api.zyins.v1.TokenDetail\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/tokens/{id}/ban\x12\x8e\x01\n" +
	"\x06Rotate\x12 .api.zyins.v1.RotateTokenRequest\x1a!.api.zyins.v1.CreateTokenResponse\"?\x82\xd3\xe4\x93\x029:\x01*Z\x16:\x01*\"\x11/v1/tokens/rotate\"\x1c/v1/tokens/{token_id}/rotateB\xc5\x01\n" +
	"\x10com.api.zyins.v1B\vTokensProtoP\x01ZJgithub.com/isa-sdk/sdk/zyins/api/zyins/v1;zyinsv1\xa2\x02\x03AZX\xaa\x02\x13IsaSdk.ZyINS.Api.V1\xca\x02\x10Sah\\ZyINS\\Api\\V1\xe2\x02\x15Sah\\ZyINS\\Api\\V1\\Meta\xea\x02\x0eApi::Zyins::V1b\x06proto3"

var (
	file_api_zyins_v1_tokens_proto_rawDescOnce sync.Once
	file_api_zyins_v1_tokens_proto_rawDescData []byte
)

func file_api_zyins_v1_tokens_proto_rawDescGZIP() []byte {
	file_api_zyins_v1_tokens_proto_rawDescOnce.Do(func() {
		file_api_zyins_v1_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zyins_v1_tokens_proto_rawDesc), len(file_api_zyins_v1_tokens_proto_rawDesc)))
	})
	return file_api_zyins_v1_tokens_proto_rawDescData
}

var file_api_zyins_v1_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_zyins_v1_tokens_proto_goTypes = []any{
	(*ListTokensRequest)(nil),     // 0: api.zyins.v1.ListTokensRequest
	(*ListTokensResponse)(nil),    // 1: api.zyins.v1.ListTokensResponse
	(*CreateTokenRequest)(nil),    // 2: api.zyins.v1.CreateTokenRequest
	(*CreateTokenResponse)(nil),   // 3: api.zyins.v1.CreateTokenResponse
	(*GetTokenRequest)(nil),       // 4: api.zyins.v1.GetTokenRequest
	(*DeleteTokenRequest)(nil),    // 5: api.zyins.v1.DeleteTokenRequest
	(*DeleteTokenResponse)(nil),   // 6: api.zyins.v1.DeleteTokenResponse
	(*RevokeTokenRequest)(nil),    // 7: api.zyins.v1.RevokeTokenRequest
	(*ReinstateTokenRequest)(nil), // 8: api.zyins.v1.ReinstateTokenRequest
	(*BanTokenRequest)(nil),       // 9: api.zyins.v1.BanTokenRequest
	(*RotateTokenRequest)(nil),    // 10: api.zyins.v1.RotateTokenRequest
	(*TokenDetail)(nil),           // 11: api.zyins.v1.TokenDetail
	(TokenStatus)(0),              // 12: api.zyins.v1.TokenStatus
}
var file_api_zyins_v1_tokens_proto_depIdxs = []int32{
	11, // 0: api.zyins.v1.ListTokensResponse.data:type_name -> api.zyins.v1.TokenDetail
	12, // 1: api.zyins.v1.TokenDetail.status:type_name -> api.zyins.v1.TokenStatus
	0,  // 2: api.zyins.v1.TokensService.List:input_type -> api.zyins.v1.ListTokensRequest
	2,  // 3: api.zyins.v1.TokensService.Create:input_type -> api.zyins.v1.CreateTokenRequest
	4,  // 4: api.zyins.v1.TokensService.Get:input_type -> api.zyins.v1.GetTokenRequest
	5,  // 5: api.zyins.v1.TokensService.Delete:input_type -> api.zyins.v1.DeleteTokenRequest
	7,  // 6: api.zyins.v1.TokensService.Revoke:input_type -> api.zyins.v1.RevokeTokenRequest
	8,  // 7: api.zyins.v1.TokensService.Reinstate:input_type -> api.zyins.v1.ReinstateTokenRequest
	9,  // 8: api.zyins.v1.TokensService.Ban:input_type -> api.zyins.v1.BanTokenRequest
	10, // 9: api.zyins.v1.TokensService.Rotate:input_type -> api.zyins.v1.RotateTokenRequest
	1,  // 10: api.zyins.v1.TokensService.List:output_type -> api.zyins.v1.ListTokensResponse
	3,  // 11: api.zyins.v1.TokensService.Create:output_type -> api.zyins.v1.CreateTokenResponse
	11, // 12: api.zyins.v1.TokensService.Get:output_type -> api.zyins.v1.TokenDetail
	6,  // 13: api.zyins.v1.TokensService.Delete:output_type -> api.zyins.v1.DeleteTokenResponse
	11, // 14: api.zyins.v1.TokensService.Revoke:output_type -> api.zyins.v1.TokenDetail
	11, // 15: api.zyins.v1.TokensService.Reinstate:output_type -> api.zyins.v1.TokenDetail
	11, // 16: api.zyins.v1.TokensService.Ban:output_type -> api.zyins.v1.TokenDetail
	3,  // 17: api.zyins.v1.TokensService.Rotate:output_type -> api.zyins.v1.CreateTokenResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_zyins_v1_tokens_proto_init() }
func file_api_zyins_v1_tokens_proto_init() {
	if File_api_zyins_v1_tokens_proto != nil {
		return
	}
	file_api_zyins_v1_common_proto_init()
	file_api_zyins_v1_tokens_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zyins_v1_tokens_proto_rawDesc), len(file_api_zyins_v1_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zyins_v1_tokens_proto_goTypes,
		DependencyIndexes: file_api_zyins_v1_tokens_proto_depIdxs,
		MessageInfos:      file_api_zyins_v1_tokens_proto_msgTypes,
	}.Build()
	File_api_zyins_v1_tokens_proto = out.File
	file_api_zyins_v1_tokens_proto_goTypes = nil
	file_api_zyins_v1_tokens_proto_depIdxs = nil
}
