// Package contract is the public-surface contract guard for the Go SDK.
//
// This package exists purely as a compile-time pin on the canonical
// names + signatures of every shipped public symbol. It re-references
// each guarded symbol so that ``go build ./contract`` and
// ``go vet ./...`` fail the moment a public name is renamed, removed,
// or has its signature drifted.
//
// This complements two pre-existing layers of drift detection:
//
//  1. packages/go/PUBLIC_API.txt — snapshot of every public symbol.
//     Captures ANY shape change; regenerated by
//     ``scripts/sdk-public-api.sh regenerate`` and diff-gated by CI
//     (.github/workflows/sdk-public-api.yml). The primary surface guard.
//  2. The mirrored TypeScript contract at packages/ts/src/__contract__.ts
//     (PR #366), which originally introduced this pattern.
//
// This file is the strongest tier: it makes the contract a build
// dependency. A rename never reaches main without contract.go
// re-pointing or the build failing.
//
// Maintenance: add a reference here only after the locked spec calls
// for the name. To "forward-lock" a name that the spec calls for but
// the SDK has not yet shipped, declare a ``var _ SomeFutureType`` line
// commented with ``// LOCK:`` and a tracking issue; the moment the
// type lands, uncomment the line and the build catches the canonical
// name.
package contract

import (
	"context"

	sdk "github.com/isa-sdk/sdk"
	"github.com/isa-sdk/sdk/proxy"
	"github.com/isa-sdk/sdk/rapidsign"
	"github.com/isa-sdk/sdk/zyins"
	zcases "github.com/isa-sdk/sdk/zyins/cases"
	"github.com/isa-sdk/sdk/zyins/reference"
)

// =========================================================================
// Tier 1 — Top-level Isa constructor + namespace factories.
// =========================================================================
//
// A rename, signature drift, or removal of any of these fails
// ``go build`` immediately. The factories are the entry points every
// integrator uses on first import; the locked spec names them
// explicitly.

var (
	_ func(string) (*sdk.Isa, error)                = sdk.WithBearer
	_ func(sdk.BearerOptions) (*sdk.Isa, error)     = sdk.WithBearerOptions
	_ func(sdk.LicenseOptions) (*sdk.Isa, error)    = sdk.WithLicense
	_ func(sdk.SessionOptions) (*sdk.Isa, error)    = sdk.WithSession
	_ func(map[string]string, string) string        = sdk.ResolveAPIVersion
)

// Isa struct field surface — every product namespace MUST remain
// reachable through the canonical field names. Touching this list is
// the contract-review trigger.
var _ = func(isa *sdk.Isa) (
	*zyins.Client,
	*rapidsign.Client,
	*sdk.WebhooksNamespace,
	*sdk.ProxyNamespace,
) {
	return isa.Zyins, isa.RapidSign, isa.Webhooks, isa.Proxy
}

// =========================================================================
// Tier 1 — Per-surface API-version map.
// =========================================================================
//
// BundledAPIVersions is the locked-spec per-surface pin map. A
// type-shape change (e.g. value type drift) breaks this line.

var _ map[string]string = sdk.BundledAPIVersions

// The zyins sub-package exposes the same map; both lines must compile.
var _ map[string]string = zyins.BundledAPIVersions

// =========================================================================
// Tier 1 — CaseStorage contract.
// =========================================================================
//
// Every consumer that plugs an adapter into LicenseOptions /
// BearerOptions / SessionOptions implements zcases.CaseStorage. The
// PutResult / CaseRecord round-trip is the wire shape.

var (
	_ zcases.CaseRecord    = zcases.CaseRecord{}
	_ zcases.PutResult     = zcases.PutResult{}
	_ error                = zcases.ErrNotFound
	_ error                = zcases.ErrUnsupported
)

// CaseStorage and DeleteableCaseStorage are interfaces; the
// ``var _ Iface = (*T)(nil)`` idiom would require a concrete
// implementation. We assert the interface shape directly by referring
// to the type — a removal fails the import.
var (
	_ = (*zcases.CaseStorage)(nil)
	_ = (*zcases.DeleteableCaseStorage)(nil)
	_ = (*zcases.Doer)(nil)
)

// NewZeroKnowledgeCaseStorage exists at the documented path.
var _ func(zcases.Doer) zcases.CaseStorage = func(d zcases.Doer) zcases.CaseStorage {
	return zcases.NewZeroKnowledgeCaseStorage(d)
}

// =========================================================================
// Tier 1 — Reference matcher surface.
// =========================================================================
//
// Per locked-spec docs/sdk-syntax-proposal.md §reference: the matcher
// surface is reachable through a ReferenceService bound to a
// DatasetBundleV3. The Sort vocabulary
// (SortMostCommonFirst / SortAlphabetical) is the documented enum.

var (
	_ zyins.ReferenceSort = zyins.SortMostCommonFirst
	_ zyins.ReferenceSort = zyins.SortAlphabetical
)

var _ = (*zyins.Concept)(nil)
var _ = (*zyins.ReferenceMatcher)(nil)

var _ func(s *zyins.ReferenceService) zyins.ReferenceMatcher = func(s *zyins.ReferenceService) zyins.ReferenceMatcher {
	return s.Medications()
}

// =========================================================================
// Tier 1 — Error hierarchy.
// =========================================================================
//
// Renames break ``errors.As`` user code. Each named subclass MUST
// remain catchable under its canonical name.

var (
	_ = (*zyins.Error)(nil)
	_ = (*zyins.AuthError)(nil)
	_ = (*zyins.ValidationError)(nil)
	_ = (*zyins.LicenseError)(nil)
	_ = (*zyins.RateLimitError)(nil)
	_ = (*zyins.IdempotencyConflictError)(nil)
	_ = (*zyins.ConfigError)(nil)
)

// IsaError is the root errors.As funnel.
var _ = (*zyins.IsaError)(nil)

// =========================================================================
// Tier 1 — Reference adapter surface (v3 datasets cutover).
// =========================================================================
//
// Per the locked spec at /tmp/v3-datasets-adapter-cutover-spec.md §2:
// three adapter interfaces — Autocorrector, MatchAlgorithm,
// AutocompleteAlgorithm — plus the typed default impls and the
// top-level factory accessors on *Isa. A rename of any of these names
// is a breaking change for SDK consumers.

var (
	_ = (*reference.Autocorrector)(nil)
	_ = (*reference.MatchAlgorithm)(nil)
	_ = (*reference.AutocompleteAlgorithm)(nil)

	_ *reference.DefaultAutocorrector         = reference.NewDefaultAutocorrector(nil)
	_ *reference.DefaultMatchAlgorithm        = reference.NewDefaultMatchAlgorithm()
	_ *reference.DefaultAutocompleteAlgorithm = reference.NewDefaultAutocompleteAlgorithm()

	// Functional-options constructors must remain variadic.
	_ func(map[string]string, ...reference.AutocorrectorOption) *reference.DefaultAutocorrector = reference.NewDefaultAutocorrector
	_ func(...reference.MatchAlgorithmOption) *reference.DefaultMatchAlgorithm                  = reference.NewDefaultMatchAlgorithm
	_ func(...reference.AutocompleteAlgorithmOption) *reference.DefaultAutocompleteAlgorithm    = reference.NewDefaultAutocompleteAlgorithm

	// Locked option helpers.
	_ func(string) reference.AutocorrectorOption                         = reference.WithAutocorrectorVersionTag
	_ func(reference.AutocorrectOnApplied) reference.AutocorrectorOption = reference.WithAutocorrectorOnApplied
	_ func(string) reference.MatchAlgorithmOption                        = reference.WithMatchAlgorithmVersionTag
	_ func(string) reference.AutocompleteAlgorithmOption                 = reference.WithAutocompleteAlgorithmVersionTag

	// Shared shape types — renames break consumer call sites.
	_ reference.Suggestion          = reference.Suggestion{}
	_ reference.CandidateConcept    = reference.CandidateConcept{}
	_ reference.MatchResult         = reference.MatchResult{}
	_ reference.AutocompleteOptions = reference.AutocompleteOptions{}
	_ reference.CorrectOptions      = reference.CorrectOptions{}
	_ reference.AutocorrectEvent    = reference.AutocorrectEvent{}
)

// Top-level Isa adapter accessors per the locked SDK syntax. A rename
// here fails the build immediately.
var (
	_ func(*sdk.Isa) sdk.AutocorrectorFactory         = (*sdk.Isa).Autocorrector
	_ func(*sdk.Isa) sdk.MatchAlgorithmFactory        = (*sdk.Isa).MatchAlgorithm
	_ func(*sdk.Isa) sdk.AutocompleteAlgorithmFactory = (*sdk.Isa).AutocompleteAlgorithm

	_ func(*sdk.Isa, reference.Autocorrector) *sdk.Isa         = (*sdk.Isa).WithAutocorrector
	_ func(*sdk.Isa, reference.MatchAlgorithm) *sdk.Isa        = (*sdk.Isa).WithMatchAlgorithm
	_ func(*sdk.Isa, reference.AutocompleteAlgorithm) *sdk.Isa = (*sdk.Isa).WithAutocompleteAlgorithm
)

// =========================================================================
// Tier 1 — Proxy namespace shape.
// =========================================================================
//
// The Proxy namespace exposes a single Call entry point.

var _ func(*sdk.ProxyNamespace, context.Context, proxy.CallOptions) ([]byte, error) =
	(*sdk.ProxyNamespace).Call
