// Code generated by scripts/gen-catalog/main.go — do not hand-edit; rerun the generator.
//
// Source data:
//   - insurance/v2_products.json

package catalog

// CarrierMetadata describes one carrier. States is empty until upstream
// publishes per-carrier licensure data.
type CarrierMetadata struct {
	Slug, DisplayName string
	// ProductIDs holds the prod_<uuid> identifiers for this carrier's products.
	// Resolve each via ByID to get the full Product value.
	ProductIDs []string
	States     []State
}

var carrierMetadata = map[string]CarrierMetadata{
	"aetna": {Slug: "aetna", DisplayName: "Aetna", ProductIDs: []string{"prod_2ebf0de6-7151-59cb-8a3a-745be5255aa0", "prod_8378b6bc-e99a-5f77-8f0d-cc978560c72f", "prod_d7b57156-3e83-506b-8936-0692c1193dc7"}},
	"aetna-accendo": {Slug: "aetna-accendo", DisplayName: "Aetna Accendo", ProductIDs: []string{"prod_c134cc26-08e2-5489-8e60-8bea89e89f49"}},
	"aflac": {Slug: "aflac", DisplayName: "Aflac", ProductIDs: []string{"prod_2eaabda5-ea10-5803-b9fd-f92c0261a9c9"}},
	"american-amicable": {Slug: "american-amicable", DisplayName: "American Amicable", ProductIDs: []string{"prod_1a546f99-9e24-4aec-b80d-99f8a0641230", "prod_444bd8e6-1253-5837-9f30-e3e4efe721b2", "prod_6b8e3fdb-79da-4e0c-81f5-534aaca277dd", "prod_76ea329c-3e29-539c-9cc4-fe8753bbf8c8", "prod_7f5a7c56-8ef1-5874-a3c6-6433b4c6c3c4", "prod_8bf67d18-391b-51c2-9333-cf557e81d1ff", "prod_a9725d37-f0c9-429b-94fb-c5c4d1fa1d53", "prod_b630f531-dd7b-48e2-8f2f-1b03b97ed2f9", "prod_d6147bbb-b210-5422-9ec4-41de0379e552", "prod_fbf0beb6-5933-5810-8973-675454c64e54"}},
	"american-home-life": {Slug: "american-home-life", DisplayName: "American Home Life", ProductIDs: []string{"prod_18005d37-9bee-588a-81e6-9f3ba641da35", "prod_9e575f61-4618-53cf-b321-6038b98c4ea5"}},
	"americo": {Slug: "americo", DisplayName: "Americo", ProductIDs: []string{"prod_14bbd5ef-adb9-575a-ba14-45da192bc0a3", "prod_9b379a0d-320e-50ac-bd2e-8519ea503286"}},
	"ameritas": {Slug: "ameritas", DisplayName: "Ameritas", ProductIDs: []string{"prod_6b476015-eeca-5f02-a259-36820bd47b98", "prod_e832f26e-f6e6-5009-8c13-d17e5bc6a02f"}},
	"baltimore-life": {Slug: "baltimore-life", DisplayName: "Baltimore Life", ProductIDs: []string{"prod_44937aff-cd7f-4484-b6d3-3dc84cd73491", "prod_4cda675a-9760-51ac-bb70-1e33e83502be"}},
	"banner": {Slug: "banner", DisplayName: "Banner", ProductIDs: []string{"prod_58edb7da-536d-51d3-8a23-ecb500d37de3"}},
	"betterlife": {Slug: "betterlife", DisplayName: "BetterLife", ProductIDs: []string{"prod_558a0ca1-c2a3-5007-916d-28dde3eaeabb", "prod_e0cbd195-3967-5127-b9d7-9d763f9812b9"}},
	"centrian": {Slug: "centrian", DisplayName: "Centrian", ProductIDs: []string{"prod_ad1bf475-7997-5d4b-9034-bf9d4f0a0494"}},
	"cica-life": {Slug: "cica-life", DisplayName: "CICA Life", ProductIDs: []string{"prod_0940211a-bc9b-509b-ae1a-6e279eed776b"}},
	"cigna": {Slug: "cigna", DisplayName: "Cigna", ProductIDs: []string{"prod_b11f7348-2716-5dae-b588-ed2a54ac4c04"}},
	"combined": {Slug: "combined", DisplayName: "Combined", ProductIDs: []string{"prod_50911138-79a1-4c20-911a-a37a3054e01a"}},
	"corebridge": {Slug: "corebridge", DisplayName: "Corebridge", ProductIDs: []string{"prod_72169acb-1a87-5848-9df0-96454c709b81", "prod_7eb671f1-781f-432d-b887-85195902c1cb", "prod_e49fed5b-0803-480f-9ac4-8774353681ab"}},
	"emc": {Slug: "emc", DisplayName: "EMC", ProductIDs: []string{"prod_e1bda62f-59ba-5770-b4a4-9a3df49243bf"}},
	"everest-ia-american": {Slug: "everest-ia-american", DisplayName: "Everest IA American", ProductIDs: []string{"prod_bb930420-5ed3-5d8a-94f5-a6d9d0571179"}},
	"family-benefit-life": {Slug: "family-benefit-life", DisplayName: "Family Benefit Life", ProductIDs: []string{"prod_8b224dea-1a89-55ed-8e76-b394d707da1b"}},
	"fidelity-life": {Slug: "fidelity-life", DisplayName: "Fidelity Life", ProductIDs: []string{"prod_10f36326-2bd4-5ae1-8463-e04ad594db6c", "prod_39f74284-c3a3-5ef4-a499-96c80246e57f", "prod_510ecb6e-5801-53b3-89aa-d578ead5b623", "prod_ddcffff2-12d0-4549-a6af-1eee7d73d646", "prod_e1c66430-dec1-571a-b96b-17231fe55c12"}},
	"first-guaranty-insurance": {Slug: "first-guaranty-insurance", DisplayName: "First Guaranty Insurance", ProductIDs: []string{"prod_f7143a73-aac8-55c7-9f7f-a69462cb5b7e"}},
	"foresters": {Slug: "foresters", DisplayName: "Foresters", ProductIDs: []string{"prod_797c9cc3-325f-5058-b092-ca811dfd89cf", "prod_82b87fc0-e3dc-5fb6-bf18-85035e6cb8cf", "prod_9577974b-a9f3-5da2-9855-1924074044dd", "prod_f5c30718-4681-599f-8110-b5aaacd778c7"}},
	"gerber": {Slug: "gerber", DisplayName: "Gerber", ProductIDs: []string{"prod_dc4e84b8-8099-51c9-ae31-37c78c0a8d39"}},
	"global-atlantic": {Slug: "global-atlantic", DisplayName: "Global Atlantic", ProductIDs: []string{"prod_52d6ba39-47d6-5527-bd4a-49bca391ab19"}},
	"gpm": {Slug: "gpm", DisplayName: "GPM", ProductIDs: []string{"prod_bb80c30b-eba4-5319-8ba6-13d807bfba9a"}},
	"gpm-life": {Slug: "gpm-life", DisplayName: "GPM Life", ProductIDs: []string{"prod_83b78dd8-a77b-558e-9b3b-c9cc5251c613"}},
	"gtl": {Slug: "gtl", DisplayName: "GTL", ProductIDs: []string{"prod_142e101a-749e-4e28-90ea-2f8fed3b6970", "prod_a8249c2b-5277-5113-8ecc-4d8b0f507662"}},
	"hero-life": {Slug: "hero-life", DisplayName: "Hero Life", ProductIDs: []string{"prod_7f6016d9-9f12-5f75-a57a-cd16ddffe99c"}},
	"illinois-mutual": {Slug: "illinois-mutual", DisplayName: "Illinois Mutual", ProductIDs: []string{"prod_e2aea5b2-316d-5150-8504-2e3c2a4e3276"}},
	"john-hancock": {Slug: "john-hancock", DisplayName: "John Hancock", ProductIDs: []string{"prod_0d293690-3896-530f-a94b-aa2cb72d30bd"}},
	"kansas-city-life": {Slug: "kansas-city-life", DisplayName: "Kansas City Life", ProductIDs: []string{"prod_65015b8a-d64d-55f1-9ca1-06588d8b073e"}},
	"kskj": {Slug: "kskj", DisplayName: "KSKJ", ProductIDs: []string{"prod_d93892e6-0035-5f82-8427-1bd9e49b1959"}},
	"liberty-bankers": {Slug: "liberty-bankers", DisplayName: "Liberty Bankers", ProductIDs: []string{"prod_fe3498ec-29a7-5dba-9da9-6a32cb3dc91e"}},
	"life-shield": {Slug: "life-shield", DisplayName: "Life Shield", ProductIDs: []string{"prod_d155e90c-cba1-51cf-9d9c-e6518fa13d37"}},
	"lincoln": {Slug: "lincoln", DisplayName: "Lincoln", ProductIDs: []string{"prod_45751b44-a561-54c2-9e1d-4120fdc09e7f", "prod_9071ccab-2830-59ed-8715-f2330215bf0d"}},
	"manhattan-life": {Slug: "manhattan-life", DisplayName: "Manhattan Life", ProductIDs: []string{"prod_5ba7fc1f-0bd8-5f49-827a-ca049312920f", "prod_afbfa67e-a41d-45be-bcbc-bf31e7de669f"}},
	"mutual-of-omaha": {Slug: "mutual-of-omaha", DisplayName: "Mutual of Omaha", ProductIDs: []string{"prod_1452309d-291d-54dc-aca7-cc313811a239", "prod_88e1ad8f-a3b3-52dd-89b7-8ae7e9d81eca", "prod_ab68ec62-2afe-561c-acd7-dab8eaf56846", "prod_cb26875d-f5b2-52f7-8f89-66cb3d779bf8"}},
	"nationwide": {Slug: "nationwide", DisplayName: "Nationwide", ProductIDs: []string{"prod_f8d141bf-d0b5-5a97-9226-4b1ab5380d47"}},
	"newbridge": {Slug: "newbridge", DisplayName: "Newbridge", ProductIDs: []string{"prod_007e74bf-671c-41cc-be27-28cfd75fd5d2"}},
	"north-american": {Slug: "north-american", DisplayName: "North American", ProductIDs: []string{"prod_29cffca2-ddfc-54de-a94b-65595b68adf3"}},
	"occidental-life": {Slug: "occidental-life", DisplayName: "Occidental Life", ProductIDs: []string{"prod_07bdd66e-7e3c-5f7f-9c8e-b4bb414dd9e2", "prod_0c5d1d8d-dd9e-59b8-a5c7-dddfd4b7da1a", "prod_4b038ed0-2aa2-58e6-9c62-9aa736e4d9b5", "prod_97d8f31d-764a-549c-9834-6691e1db06a8", "prod_b06445f5-5e02-5111-863b-5e1260b4524b", "prod_d2eeac7e-6aad-5eee-83e1-fd2aee0da64c", "prod_fbd566f8-72f6-5383-84e9-a84c517c8815"}},
	"oxford-life": {Slug: "oxford-life", DisplayName: "Oxford Life", ProductIDs: []string{"prod_a5a3a129-cf4d-57bf-a278-034b65348c11"}},
	"pekin": {Slug: "pekin", DisplayName: "Pekin", ProductIDs: []string{"prod_8e946869-fe0e-5f8c-a231-cc1671e4b2d4"}},
	"pioneer-american": {Slug: "pioneer-american", DisplayName: "Pioneer American", ProductIDs: []string{"prod_42cfd631-69ea-5711-858d-168503cb0680", "prod_ec518d73-777d-5976-b4fd-d2e0b6332c56"}},
	"prosperity": {Slug: "prosperity", DisplayName: "Prosperity", ProductIDs: []string{"prod_090de60e-d322-55d9-8ef5-a010e5275cc5"}},
	"protective-life": {Slug: "protective-life", DisplayName: "Protective Life", ProductIDs: []string{"prod_6a8bfb0c-15da-51f4-a267-6d237e125d97", "prod_b11965d0-4866-5e50-b348-d93e09832867"}},
	"prudential": {Slug: "prudential", DisplayName: "Prudential", ProductIDs: []string{"prod_3d619542-5829-5d2a-9450-6e2673e7cb94", "prod_80952375-cbed-5817-910c-07475af33604"}},
	"royal-arcanum": {Slug: "royal-arcanum", DisplayName: "Royal Arcanum", ProductIDs: []string{"prod_4d67b7ca-cc86-5849-8e32-5e22bea6cdce", "prod_bf77cdcd-078d-534c-a923-861ce722a0e8"}},
	"royal-neighbors": {Slug: "royal-neighbors", DisplayName: "Royal Neighbors", ProductIDs: []string{"prod_b039d938-ced2-4496-ad4d-f28b795b8089"}},
	"s-usa": {Slug: "s-usa", DisplayName: "S.USA", ProductIDs: []string{"prod_79a26030-6b45-416a-b97d-02e0200a4d39"}},
	"sagicor": {Slug: "sagicor", DisplayName: "Sagicor", ProductIDs: []string{"prod_3a9f8911-2d94-5f27-88b8-62dcc7d5727a"}},
	"sbli": {Slug: "sbli", DisplayName: "SBLI", ProductIDs: []string{"prod_09b94921-6ba1-5f17-92da-5750c2c0b12a", "prod_360fe967-f7e1-5ab4-8f1a-e56e9ef543ab"}},
	"securico-life": {Slug: "securico-life", DisplayName: "Securico Life", ProductIDs: []string{"prod_e2a56a6e-9d28-51d2-893f-b980998b7822"}},
	"security-national": {Slug: "security-national", DisplayName: "Security National", ProductIDs: []string{"prod_81f01f85-1d97-58b1-9892-f7fd66ac2152"}},
	"senior-life": {Slug: "senior-life", DisplayName: "Senior Life", ProductIDs: []string{"prod_ccebb3f4-2be4-5a64-8365-6e72faf5185d", "prod_ed4476ae-f668-4a64-96cc-d618c1f018b8"}},
	"sentinel-security": {Slug: "sentinel-security", DisplayName: "Sentinel Security", ProductIDs: []string{"prod_cac5f3fe-1d7a-5865-84cf-8000ff8bcfd7"}},
	"sons-of-norway": {Slug: "sons-of-norway", DisplayName: "Sons of Norway", ProductIDs: []string{"prod_2dec8fd4-8ead-4862-a51e-e51f7aae8ee5", "prod_9b00ed35-28a2-4ce6-a50e-914213419d6b"}},
	"transamerica": {Slug: "transamerica", DisplayName: "TransAmerica", ProductIDs: []string{"prod_18477e53-831f-47bf-829c-0237c23b6fb6", "prod_90d1b5da-5063-56e7-b737-d44b77126da2", "prod_bcfc35ae-30d7-5466-9267-06d09faa3319", "prod_e64af080-608b-5c34-ba46-166d008fa249"}},
	"trinity": {Slug: "trinity", DisplayName: "Trinity", ProductIDs: []string{"prod_19c56704-7c68-5320-9a8a-042c94ceba64"}},
	"united-farm-and-family": {Slug: "united-farm-and-family", DisplayName: "United Farm And Family", ProductIDs: []string{"prod_a6f48502-08be-5a6b-9934-d3cb3f470972"}},
	"united-home-life": {Slug: "united-home-life", DisplayName: "United Home Life", ProductIDs: []string{"prod_d851aa99-47f9-5400-a966-97a0b5a71bb3"}},
	"william-penn": {Slug: "william-penn", DisplayName: "William Penn", ProductIDs: []string{"prod_482585d7-6c1c-5042-b42b-09ef12933d1d"}},
}

var allCarriers = []string{
	"aetna",
	"aetna-accendo",
	"aflac",
	"american-amicable",
	"american-home-life",
	"americo",
	"ameritas",
	"baltimore-life",
	"banner",
	"betterlife",
	"centrian",
	"cica-life",
	"cigna",
	"combined",
	"corebridge",
	"emc",
	"everest-ia-american",
	"family-benefit-life",
	"fidelity-life",
	"first-guaranty-insurance",
	"foresters",
	"gerber",
	"global-atlantic",
	"gpm",
	"gpm-life",
	"gtl",
	"hero-life",
	"illinois-mutual",
	"john-hancock",
	"kansas-city-life",
	"kskj",
	"liberty-bankers",
	"life-shield",
	"lincoln",
	"manhattan-life",
	"mutual-of-omaha",
	"nationwide",
	"newbridge",
	"north-american",
	"occidental-life",
	"oxford-life",
	"pekin",
	"pioneer-american",
	"prosperity",
	"protective-life",
	"prudential",
	"royal-arcanum",
	"royal-neighbors",
	"s-usa",
	"sagicor",
	"sbli",
	"securico-life",
	"security-national",
	"senior-life",
	"sentinel-security",
	"sons-of-norway",
	"transamerica",
	"trinity",
	"united-farm-and-family",
	"united-home-life",
	"william-penn",
}

type carriersAPI struct{}

// Carriers is the catalog accessor.
var Carriers carriersAPI

// Values returns every carrier slug, sorted alphabetically.
func (carriersAPI) Values() []string { return append([]string(nil), allCarriers...) }

// Metadata returns the carrier metadata and whether slug is known.
func (carriersAPI) Metadata(slug string) (CarrierMetadata, bool) {
	m, ok := carrierMetadata[slug]
	return m, ok
}
