// Code generated by scripts/gen_catalog.py. Regenerate with that script.
//
// Source data:
//   - isa-platform/shared/schemas/api/isa/v1/common.proto

package catalog

// ErrorCode is the stable wire-form error identifier.
type ErrorCode string

const (
	// Upstream dependency returned an unusable response.
	ErrorCodeBadGateway ErrorCode = "bad_gateway"
	// State conflict (e.g. already activated, already revoked, document already signed).
	ErrorCodeConflict ErrorCode = "conflict"
	// Authenticated but lacking scope for this operation.
	ErrorCodeForbidden ErrorCode = "forbidden"
	// Upstream dependency did not respond within the budget.
	ErrorCodeGatewayTimeout ErrorCode = "gateway_timeout"
	// Unhandled server fault. Request ID identifies the log entry.
	ErrorCodeInternalError ErrorCode = "internal_error"
	// Bearer token or license signature does not validate.
	ErrorCodeInvalidToken ErrorCode = "invalid_token"
	// License is locked (too many device registrations or admin action).
	ErrorCodeLicenseLocked ErrorCode = "license_locked"
	// HTTP method not allowed on this path.
	ErrorCodeMethodNotAllowed ErrorCode = "method_not_allowed"
	// Resource does not exist or is not visible to the caller.
	ErrorCodeNotFound ErrorCode = "not_found"
	// Capability not yet implemented (e.g. PDF renderer not configured).
	ErrorCodeNotImplemented ErrorCode = "not_implemented"
	// Rate limit exceeded. `Retry-After` header is set.
	ErrorCodeRateLimitExceeded ErrorCode = "rate_limit_exceeded"
	// Service is intentionally unavailable (draining, maintenance).
	ErrorCodeServiceUnavailable ErrorCode = "service_unavailable"
	// Bearer token or license has expired. Client should refresh.
	ErrorCodeTokenExpired ErrorCode = "token_expired"
	// Authentication required or credentials invalid.
	ErrorCodeUnauthorized ErrorCode = "unauthorized"
	// Request body failed schema or domain validation. `param` is set.
	ErrorCodeValidationError ErrorCode = "validation_error"
)

var errorAdviceCodes = map[ErrorCode]string{
	"bad_gateway": "retry_with_backoff",
	"conflict": "reconcile_state",
	"forbidden": "check_scopes",
	"gateway_timeout": "retry_with_backoff",
	"internal_error": "retry_or_contact_support",
	"invalid_token": "reissue_session",
	"license_locked": "contact_support",
	"method_not_allowed": "check_http_method",
	"not_found": "verify_resource_id",
	"not_implemented": "check_feature_availability",
	"rate_limit_exceeded": "wait_and_retry",
	"service_unavailable": "retry_with_backoff",
	"token_expired": "refresh_session",
	"unauthorized": "authenticate_caller",
	"validation_error": "fix_request_body",
}

var errorDocURLs = map[ErrorCode]string{
	"bad_gateway": "https://docs.isaapi.com/errors/bad_gateway",
	"conflict": "https://docs.isaapi.com/errors/conflict",
	"forbidden": "https://docs.isaapi.com/errors/forbidden",
	"gateway_timeout": "https://docs.isaapi.com/errors/gateway_timeout",
	"internal_error": "https://docs.isaapi.com/errors/internal_error",
	"invalid_token": "https://docs.isaapi.com/errors/invalid_token",
	"license_locked": "https://docs.isaapi.com/errors/license_locked",
	"method_not_allowed": "https://docs.isaapi.com/errors/method_not_allowed",
	"not_found": "https://docs.isaapi.com/errors/not_found",
	"not_implemented": "https://docs.isaapi.com/errors/not_implemented",
	"rate_limit_exceeded": "https://docs.isaapi.com/errors/rate_limit_exceeded",
	"service_unavailable": "https://docs.isaapi.com/errors/service_unavailable",
	"token_expired": "https://docs.isaapi.com/errors/token_expired",
	"unauthorized": "https://docs.isaapi.com/errors/unauthorized",
	"validation_error": "https://docs.isaapi.com/errors/validation_error",
}

type errorsAPI struct{}

// Errors is the catalog accessor.
var Errors errorsAPI

// AdviceCode returns the machine-readable next-action identifier for c.
func (errorsAPI) AdviceCode(c ErrorCode) string { return errorAdviceCodes[c] }

// DocURL returns the canonical documentation URL for c.
func (errorsAPI) DocURL(c ErrorCode) string { return errorDocURLs[c] }
