// Code generated by scripts/gen_catalog.py. Regenerate with that script.
//
// Source data:
//   - isa-platform/shared/schemas/api/isa/v1/common.proto

package catalog

// Scope is the bearer-token scope identifier.
type Scope string

const (
	// send signer notification emails.
	ScopeRapidsignDocumentsNotify Scope = "rapidsign:documents:notify"
	// fetch signature state and signed PDFs.
	ScopeRapidsignDocumentsRead Scope = "rapidsign:documents:read"
	// submit signatures.
	ScopeRapidsignDocumentsSign Scope = "rapidsign:documents:sign"
	// create new documents.
	ScopeRapidsignDocumentsWrite Scope = "rapidsign:documents:write"
)

var scopeDescriptions = map[Scope]string{
	"rapidsign:documents:notify": "send signer notification emails.",
	"rapidsign:documents:read": "fetch signature state and signed PDFs.",
	"rapidsign:documents:sign": "submit signatures.",
	"rapidsign:documents:write": "create new documents.",
}

type scopesAPI struct{}

// Scopes is the catalog accessor.
var Scopes scopesAPI

// Description returns the documentation prose for s.
func (scopesAPI) Description(s Scope) string { return scopeDescriptions[s] }
