// Code generated by scripts/gen_catalog.py. Regenerate with that script.
//
// Source data:
//   - isa-platform/shared/go/events/registry.go

package catalog

// SignEvent is the EventBridge detail-type for RapidSign webhooks.
type SignEvent string

const (
	SignEventDocumentSigned SignEvent = "document.signed"
)

var signEventLabels = map[SignEvent]string{
	"document.signed": "DocumentSigned",
}

type signEventsAPI struct{}

// SignEvents is the catalog accessor.
var SignEvents signEventsAPI

// Label returns the PascalCase identifier for e.
func (signEventsAPI) Label(e SignEvent) string { return signEventLabels[e] }
