// Code generated by scripts/gen_catalog.py. Regenerate with that script.
//
// Source data:
//   - ISO 3166-2:US (50 states + DC + 5 inhabited territories)

package catalog

import "strings"

// State is the ISO 3166-2:US abbreviation.
type State string

const (
	StateAlabama State = "AL"
	StateAlaska State = "AK"
	StateArizona State = "AZ"
	StateArkansas State = "AR"
	StateCalifornia State = "CA"
	StateColorado State = "CO"
	StateConnecticut State = "CT"
	StateDelaware State = "DE"
	StateFlorida State = "FL"
	StateGeorgia State = "GA"
	StateHawaii State = "HI"
	StateIdaho State = "ID"
	StateIllinois State = "IL"
	StateIndiana State = "IN"
	StateIowa State = "IA"
	StateKansas State = "KS"
	StateKentucky State = "KY"
	StateLouisiana State = "LA"
	StateMaine State = "ME"
	StateMaryland State = "MD"
	StateMassachusetts State = "MA"
	StateMichigan State = "MI"
	StateMinnesota State = "MN"
	StateMississippi State = "MS"
	StateMissouri State = "MO"
	StateMontana State = "MT"
	StateNebraska State = "NE"
	StateNevada State = "NV"
	StateNewHampshire State = "NH"
	StateNewJersey State = "NJ"
	StateNewMexico State = "NM"
	StateNewYork State = "NY"
	StateNorthCarolina State = "NC"
	StateNorthDakota State = "ND"
	StateOhio State = "OH"
	StateOklahoma State = "OK"
	StateOregon State = "OR"
	StatePennsylvania State = "PA"
	StateRhodeIsland State = "RI"
	StateSouthCarolina State = "SC"
	StateSouthDakota State = "SD"
	StateTennessee State = "TN"
	StateTexas State = "TX"
	StateUtah State = "UT"
	StateVermont State = "VT"
	StateVirginia State = "VA"
	StateWashington State = "WA"
	StateWestVirginia State = "WV"
	StateWisconsin State = "WI"
	StateWyoming State = "WY"
	StateDistrictOfColumbia State = "DC"
	StateAmericanSamoa State = "AS"
	StateGuam State = "GU"
	StateNorthernMarianaIslands State = "MP"
	StatePuertoRico State = "PR"
	StateUnitedStatesVirginIslands State = "VI"
)

// StateMetadata describes one State.
type StateMetadata struct {
	Abbreviation string
	Name         string
	IsTerritory  bool
}

var stateMetadata = map[State]StateMetadata{
	"AL": {Abbreviation: "AL", Name: "Alabama", IsTerritory: false},
	"AK": {Abbreviation: "AK", Name: "Alaska", IsTerritory: false},
	"AZ": {Abbreviation: "AZ", Name: "Arizona", IsTerritory: false},
	"AR": {Abbreviation: "AR", Name: "Arkansas", IsTerritory: false},
	"CA": {Abbreviation: "CA", Name: "California", IsTerritory: false},
	"CO": {Abbreviation: "CO", Name: "Colorado", IsTerritory: false},
	"CT": {Abbreviation: "CT", Name: "Connecticut", IsTerritory: false},
	"DE": {Abbreviation: "DE", Name: "Delaware", IsTerritory: false},
	"FL": {Abbreviation: "FL", Name: "Florida", IsTerritory: false},
	"GA": {Abbreviation: "GA", Name: "Georgia", IsTerritory: false},
	"HI": {Abbreviation: "HI", Name: "Hawaii", IsTerritory: false},
	"ID": {Abbreviation: "ID", Name: "Idaho", IsTerritory: false},
	"IL": {Abbreviation: "IL", Name: "Illinois", IsTerritory: false},
	"IN": {Abbreviation: "IN", Name: "Indiana", IsTerritory: false},
	"IA": {Abbreviation: "IA", Name: "Iowa", IsTerritory: false},
	"KS": {Abbreviation: "KS", Name: "Kansas", IsTerritory: false},
	"KY": {Abbreviation: "KY", Name: "Kentucky", IsTerritory: false},
	"LA": {Abbreviation: "LA", Name: "Louisiana", IsTerritory: false},
	"ME": {Abbreviation: "ME", Name: "Maine", IsTerritory: false},
	"MD": {Abbreviation: "MD", Name: "Maryland", IsTerritory: false},
	"MA": {Abbreviation: "MA", Name: "Massachusetts", IsTerritory: false},
	"MI": {Abbreviation: "MI", Name: "Michigan", IsTerritory: false},
	"MN": {Abbreviation: "MN", Name: "Minnesota", IsTerritory: false},
	"MS": {Abbreviation: "MS", Name: "Mississippi", IsTerritory: false},
	"MO": {Abbreviation: "MO", Name: "Missouri", IsTerritory: false},
	"MT": {Abbreviation: "MT", Name: "Montana", IsTerritory: false},
	"NE": {Abbreviation: "NE", Name: "Nebraska", IsTerritory: false},
	"NV": {Abbreviation: "NV", Name: "Nevada", IsTerritory: false},
	"NH": {Abbreviation: "NH", Name: "New Hampshire", IsTerritory: false},
	"NJ": {Abbreviation: "NJ", Name: "New Jersey", IsTerritory: false},
	"NM": {Abbreviation: "NM", Name: "New Mexico", IsTerritory: false},
	"NY": {Abbreviation: "NY", Name: "New York", IsTerritory: false},
	"NC": {Abbreviation: "NC", Name: "North Carolina", IsTerritory: false},
	"ND": {Abbreviation: "ND", Name: "North Dakota", IsTerritory: false},
	"OH": {Abbreviation: "OH", Name: "Ohio", IsTerritory: false},
	"OK": {Abbreviation: "OK", Name: "Oklahoma", IsTerritory: false},
	"OR": {Abbreviation: "OR", Name: "Oregon", IsTerritory: false},
	"PA": {Abbreviation: "PA", Name: "Pennsylvania", IsTerritory: false},
	"RI": {Abbreviation: "RI", Name: "Rhode Island", IsTerritory: false},
	"SC": {Abbreviation: "SC", Name: "South Carolina", IsTerritory: false},
	"SD": {Abbreviation: "SD", Name: "South Dakota", IsTerritory: false},
	"TN": {Abbreviation: "TN", Name: "Tennessee", IsTerritory: false},
	"TX": {Abbreviation: "TX", Name: "Texas", IsTerritory: false},
	"UT": {Abbreviation: "UT", Name: "Utah", IsTerritory: false},
	"VT": {Abbreviation: "VT", Name: "Vermont", IsTerritory: false},
	"VA": {Abbreviation: "VA", Name: "Virginia", IsTerritory: false},
	"WA": {Abbreviation: "WA", Name: "Washington", IsTerritory: false},
	"WV": {Abbreviation: "WV", Name: "West Virginia", IsTerritory: false},
	"WI": {Abbreviation: "WI", Name: "Wisconsin", IsTerritory: false},
	"WY": {Abbreviation: "WY", Name: "Wyoming", IsTerritory: false},
	"DC": {Abbreviation: "DC", Name: "District of Columbia", IsTerritory: false},
	"AS": {Abbreviation: "AS", Name: "American Samoa", IsTerritory: true},
	"GU": {Abbreviation: "GU", Name: "Guam", IsTerritory: true},
	"MP": {Abbreviation: "MP", Name: "Northern Mariana Islands", IsTerritory: true},
	"PR": {Abbreviation: "PR", Name: "Puerto Rico", IsTerritory: true},
	"VI": {Abbreviation: "VI", Name: "United States Virgin Islands", IsTerritory: true},
}

var allStates = []State{
	"AL",
	"AK",
	"AZ",
	"AR",
	"CA",
	"CO",
	"CT",
	"DE",
	"FL",
	"GA",
	"HI",
	"ID",
	"IL",
	"IN",
	"IA",
	"KS",
	"KY",
	"LA",
	"ME",
	"MD",
	"MA",
	"MI",
	"MN",
	"MS",
	"MO",
	"MT",
	"NE",
	"NV",
	"NH",
	"NJ",
	"NM",
	"NY",
	"NC",
	"ND",
	"OH",
	"OK",
	"OR",
	"PA",
	"RI",
	"SC",
	"SD",
	"TN",
	"TX",
	"UT",
	"VT",
	"VA",
	"WA",
	"WV",
	"WI",
	"WY",
	"DC",
	"AS",
	"GU",
	"MP",
	"PR",
	"VI",
}

var stateByName = map[string]State{
	"alabama": "AL",
	"alaska": "AK",
	"arizona": "AZ",
	"arkansas": "AR",
	"california": "CA",
	"colorado": "CO",
	"connecticut": "CT",
	"delaware": "DE",
	"florida": "FL",
	"georgia": "GA",
	"hawaii": "HI",
	"idaho": "ID",
	"illinois": "IL",
	"indiana": "IN",
	"iowa": "IA",
	"kansas": "KS",
	"kentucky": "KY",
	"louisiana": "LA",
	"maine": "ME",
	"maryland": "MD",
	"massachusetts": "MA",
	"michigan": "MI",
	"minnesota": "MN",
	"mississippi": "MS",
	"missouri": "MO",
	"montana": "MT",
	"nebraska": "NE",
	"nevada": "NV",
	"new hampshire": "NH",
	"new jersey": "NJ",
	"new mexico": "NM",
	"new york": "NY",
	"north carolina": "NC",
	"north dakota": "ND",
	"ohio": "OH",
	"oklahoma": "OK",
	"oregon": "OR",
	"pennsylvania": "PA",
	"rhode island": "RI",
	"south carolina": "SC",
	"south dakota": "SD",
	"tennessee": "TN",
	"texas": "TX",
	"utah": "UT",
	"vermont": "VT",
	"virginia": "VA",
	"washington": "WA",
	"west virginia": "WV",
	"wisconsin": "WI",
	"wyoming": "WY",
	"district of columbia": "DC",
	"american samoa": "AS",
	"guam": "GU",
	"northern mariana islands": "MP",
	"puerto rico": "PR",
	"united states virgin islands": "VI",
}

type statesAPI struct{}

// States is the catalog accessor.
var States statesAPI

// Values returns every State, sorted by name.
func (statesAPI) Values() []State { return append([]State(nil), allStates...) }

// Metadata returns the StateMetadata for s and whether s is known.
func (statesAPI) Metadata(s State) (StateMetadata, bool) {
	m, ok := stateMetadata[s]
	return m, ok
}

// ByAbbreviation resolves by abbreviation or full name (case-insensitive).
func (statesAPI) ByAbbreviation(s string) (State, bool) {
	up := strings.ToUpper(strings.TrimSpace(s))
	if _, ok := stateMetadata[State(up)]; ok { return State(up), true }
	if v, ok := stateByName[strings.ToLower(strings.TrimSpace(s))]; ok { return v, true }
	return "", false
}
