// Package api.isa.v1 holds the shared protobuf definitions reused across
// every ISA platform API surface (ZyINS, RapidSign, Proxy, future
// services). Per the SDK-consolidation plan, types that previously lived
// in `api.zyins.v1` and `api.rapidsign.v1` as duplicates have moved
// here so a single source of truth describes the platform-wide error
// model, OAuth-style scopes, and the shared health/readiness contract
// (see health.proto in this package).
//
// common.proto holds the RFC 7807 error model (ProblemDetails + ErrorCode)
// and the bearer-token Scope enumeration shared across products. The
// per-product JSON response Envelope type remains in each service's
// `common.proto` (e.g. api.zyins.v1.Envelope). Per-product enumerations
// (ProductClass, AccountStatus, LicenseStatus, ...) also stay in the
// owning service because they describe domain state, not platform
// contracts.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/isa/v1/common.proto

package isav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode enumerates the stable error codes consumers may switch on.
// Values are lowercase snake_case at the wire level. Additions are
// non-breaking; renames are forbidden.
//
// This is the union of every error code previously defined per service.
// Values 0-8 matched both legacy catalogs. From 9 onward the numeric
// assignments follow the former ZyINS layout (including LICENSE_LOCKED at
// 9). Legacy RapidSign emitted RATE_LIMIT_EXCEEDED as 9 and
// NOT_IMPLEMENTED as 10; those semantics now wire as 10 and 15
// respectively. Pre-1.0 consolidation: treat any cross-service numeric
// error code migration as an explicit consumer update, not a silent
// rename. New services must add missing codes here rather than locally.
type ErrorCode int32

const (
	// Default zero value. Never emitted by the server; indicates a proto
	// deserialization defect on the client side.
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Authentication required or credentials invalid.
	ErrorCode_ERROR_CODE_UNAUTHORIZED ErrorCode = 1
	// Bearer token or license has expired. Client should refresh.
	ErrorCode_ERROR_CODE_TOKEN_EXPIRED ErrorCode = 2
	// Bearer token or license signature does not validate.
	ErrorCode_ERROR_CODE_INVALID_TOKEN ErrorCode = 3
	// Authenticated but lacking scope for this operation.
	ErrorCode_ERROR_CODE_FORBIDDEN ErrorCode = 4
	// Resource does not exist or is not visible to the caller.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 5
	// HTTP method not allowed on this path.
	ErrorCode_ERROR_CODE_METHOD_NOT_ALLOWED ErrorCode = 6
	// State conflict (e.g. already activated, already revoked,
	// document already signed).
	ErrorCode_ERROR_CODE_CONFLICT ErrorCode = 7
	// Request body failed schema or domain validation. `param` is set.
	ErrorCode_ERROR_CODE_VALIDATION_ERROR ErrorCode = 8
	// License is locked (too many device registrations or admin action).
	ErrorCode_ERROR_CODE_LICENSE_LOCKED ErrorCode = 9
	// Rate limit exceeded. `Retry-After` header is set.
	ErrorCode_ERROR_CODE_RATE_LIMIT_EXCEEDED ErrorCode = 10
	// Unhandled server fault. Request ID identifies the log entry.
	ErrorCode_ERROR_CODE_INTERNAL_ERROR ErrorCode = 11
	// Upstream dependency returned an unusable response.
	ErrorCode_ERROR_CODE_BAD_GATEWAY ErrorCode = 12
	// Upstream dependency did not respond within the budget.
	ErrorCode_ERROR_CODE_GATEWAY_TIMEOUT ErrorCode = 13
	// Service is intentionally unavailable (draining, maintenance).
	ErrorCode_ERROR_CODE_SERVICE_UNAVAILABLE ErrorCode = 14
	// Capability not yet implemented (e.g. PDF renderer not configured).
	ErrorCode_ERROR_CODE_NOT_IMPLEMENTED ErrorCode = 15
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_UNAUTHORIZED",
		2:  "ERROR_CODE_TOKEN_EXPIRED",
		3:  "ERROR_CODE_INVALID_TOKEN",
		4:  "ERROR_CODE_FORBIDDEN",
		5:  "ERROR_CODE_NOT_FOUND",
		6:  "ERROR_CODE_METHOD_NOT_ALLOWED",
		7:  "ERROR_CODE_CONFLICT",
		8:  "ERROR_CODE_VALIDATION_ERROR",
		9:  "ERROR_CODE_LICENSE_LOCKED",
		10: "ERROR_CODE_RATE_LIMIT_EXCEEDED",
		11: "ERROR_CODE_INTERNAL_ERROR",
		12: "ERROR_CODE_BAD_GATEWAY",
		13: "ERROR_CODE_GATEWAY_TIMEOUT",
		14: "ERROR_CODE_SERVICE_UNAVAILABLE",
		15: "ERROR_CODE_NOT_IMPLEMENTED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_UNAUTHORIZED":        1,
		"ERROR_CODE_TOKEN_EXPIRED":       2,
		"ERROR_CODE_INVALID_TOKEN":       3,
		"ERROR_CODE_FORBIDDEN":           4,
		"ERROR_CODE_NOT_FOUND":           5,
		"ERROR_CODE_METHOD_NOT_ALLOWED":  6,
		"ERROR_CODE_CONFLICT":            7,
		"ERROR_CODE_VALIDATION_ERROR":    8,
		"ERROR_CODE_LICENSE_LOCKED":      9,
		"ERROR_CODE_RATE_LIMIT_EXCEEDED": 10,
		"ERROR_CODE_INTERNAL_ERROR":      11,
		"ERROR_CODE_BAD_GATEWAY":         12,
		"ERROR_CODE_GATEWAY_TIMEOUT":     13,
		"ERROR_CODE_SERVICE_UNAVAILABLE": 14,
		"ERROR_CODE_NOT_IMPLEMENTED":     15,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_isa_v1_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_isa_v1_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_isa_v1_common_proto_rawDescGZIP(), []int{0}
}

// Scope enumerates the bearer-token scopes recognized across the ISA
// platform. Enum member names gained a `RAPIDSIGN_` prefix so additional
// services can add scopes without colliding; wire integers for the four
// RapidSign scopes are unchanged from the legacy `SCOPE_DOCUMENTS_*`
// assignments. Generated symbol names therefore change — migrate callers
// when regenerating SDKs.
type Scope int32

const (
	// Default zero value. Never emitted.
	Scope_SCOPE_UNSPECIFIED Scope = 0
	// `rapidsign:documents:write` — create new documents.
	Scope_SCOPE_RAPIDSIGN_DOCUMENTS_WRITE Scope = 1
	// `rapidsign:documents:read` — fetch signature state and signed PDFs.
	Scope_SCOPE_RAPIDSIGN_DOCUMENTS_READ Scope = 2
	// `rapidsign:documents:sign` — submit signatures.
	Scope_SCOPE_RAPIDSIGN_DOCUMENTS_SIGN Scope = 3
	// `rapidsign:documents:notify` — send signer notification emails.
	Scope_SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY Scope = 4
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_UNSPECIFIED",
		1: "SCOPE_RAPIDSIGN_DOCUMENTS_WRITE",
		2: "SCOPE_RAPIDSIGN_DOCUMENTS_READ",
		3: "SCOPE_RAPIDSIGN_DOCUMENTS_SIGN",
		4: "SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY",
	}
	Scope_value = map[string]int32{
		"SCOPE_UNSPECIFIED":                0,
		"SCOPE_RAPIDSIGN_DOCUMENTS_WRITE":  1,
		"SCOPE_RAPIDSIGN_DOCUMENTS_READ":   2,
		"SCOPE_RAPIDSIGN_DOCUMENTS_SIGN":   3,
		"SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY": 4,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_api_isa_v1_common_proto_enumTypes[1].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_api_isa_v1_common_proto_enumTypes[1]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_api_isa_v1_common_proto_rawDescGZIP(), []int{1}
}

// ProblemDetails is the RFC 7807 error body extended with three
// machine-readable fields per ADR-012. Programmatic consumers MUST
// switch on `code`; `type` is preserved for RFC compliance but is not
// the match surface.
type ProblemDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A URI reference that identifies the problem type per RFC 7807.
	// Stable across API versions but not the primary match key — use
	// `code` instead.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Short human-readable summary. May change without notice.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// HTTP status code.
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// Stable machine-readable error code. Never renamed once shipped;
	// deprecated codes are dual-written for 6 months alongside
	// replacements.
	Code ErrorCode `protobuf:"varint,4,opt,name=code,proto3,enum=api.isa.v1.ErrorCode" json:"code,omitempty"`
	// Human-readable explanation specific to this occurrence.
	Detail string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	// Request path that generated this error.
	Instance string `protobuf:"bytes,6,opt,name=instance,proto3" json:"instance,omitempty"`
	// Unique request identifier for support and debugging.
	RequestId string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// JSON-pointer-style path to the field that failed validation.
	// Omitted entirely for non-validation errors.
	Param string `protobuf:"bytes,8,opt,name=param,proto3" json:"param,omitempty"`
	// Link to the docs page explaining this error and its remediation.
	DocUrl        string `protobuf:"bytes,9,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemDetails) Reset() {
	*x = ProblemDetails{}
	mi := &file_api_isa_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemDetails) ProtoMessage() {}

func (x *ProblemDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_isa_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemDetails.ProtoReflect.Descriptor instead.
func (*ProblemDetails) Descriptor() ([]byte, []int) {
	return file_api_isa_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ProblemDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProblemDetails) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProblemDetails) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProblemDetails) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ProblemDetails) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ProblemDetails) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ProblemDetails) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProblemDetails) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *ProblemDetails) GetDocUrl() string {
	if x != nil {
		return x.DocUrl
	}
	return ""
}

var File_api_isa_v1_common_proto protoreflect.FileDescriptor

const file_api_isa_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x17api/isa/v1/common.proto\x12\n" +
	"api.isa.v1\"\xff\x01\n" +
	"\x0eProblemDetails\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12)\n" +
	"\x04code\x18\x04 \x01(\x0e2\x15.api.isa.v1.ErrorCodeR\x04code\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\x12\x1a\n" +
	"\binstance\x18\x06 \x01(\tR\binstance\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x14\n" +
	"\x05param\x18\b \x01(\tR\x05param\x12\x17\n" +
	"\adoc_url\x18\t \x01(\tR\x06docUrl*\xf3\x03\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x01\x12\x1c\n" +
	"\x18ERROR_CODE_TOKEN_EXPIRED\x10\x02\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_TOKEN\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x04\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x05\x12!\n" +
	"\x1dERROR_CODE_METHOD_NOT_ALLOWED\x10\x06\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\a\x12\x1f\n" +
	"\x1bERROR_CODE_VALIDATION_ERROR\x10\b\x12\x1d\n" +
	"\x19ERROR_CODE_LICENSE_LOCKED\x10\t\x12\"\n" +
	"\x1eERROR_CODE_RATE_LIMIT_EXCEEDED\x10\n" +
	"\x12\x1d\n" +
	"\x19ERROR_CODE_INTERNAL_ERROR\x10\v\x12\x1a\n" +
	"\x16ERROR_CODE_BAD_GATEWAY\x10\f\x12\x1e\n" +
	"\x1aERROR_CODE_GATEWAY_TIMEOUT\x10\r\x12\"\n" +
	"\x1eERROR_CODE_SERVICE_UNAVAILABLE\x10\x0e\x12\x1e\n" +
	"\x1aERROR_CODE_NOT_IMPLEMENTED\x10\x0f*\xb1\x01\n" +
	"\x05Scope\x12\x15\n" +
	"\x11SCOPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSCOPE_RAPIDSIGN_DOCUMENTS_WRITE\x10\x01\x12\"\n" +
	"\x1eSCOPE_RAPIDSIGN_DOCUMENTS_READ\x10\x02\x12\"\n" +
	"\x1eSCOPE_RAPIDSIGN_DOCUMENTS_SIGN\x10\x03\x12$\n" +
	" SCOPE_RAPIDSIGN_DOCUMENTS_NOTIFY\x10\x04B\xb7\x01\n" +
	"\x0ecom.api.isa.v1B\vCommonProtoP\x01ZEgithub.com/isa-sdk/sdk/core/api/isa/v1;isav1\xa2\x02\x03AIX\xaa\x02\x12IsaSdk.Core.Api.V1\xca\x02\x0eSah\\Isa\\Api\\V1\xe2\x02\x13Sah\\Isa\\Api\\V1\\Meta\xea\x02\fApi::Isa::V1b\x06proto3"

var (
	file_api_isa_v1_common_proto_rawDescOnce sync.Once
	file_api_isa_v1_common_proto_rawDescData []byte
)

func file_api_isa_v1_common_proto_rawDescGZIP() []byte {
	file_api_isa_v1_common_proto_rawDescOnce.Do(func() {
		file_api_isa_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_isa_v1_common_proto_rawDesc), len(file_api_isa_v1_common_proto_rawDesc)))
	})
	return file_api_isa_v1_common_proto_rawDescData
}

var file_api_isa_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_isa_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_isa_v1_common_proto_goTypes = []any{
	(ErrorCode)(0),         // 0: api.isa.v1.ErrorCode
	(Scope)(0),             // 1: api.isa.v1.Scope
	(*ProblemDetails)(nil), // 2: api.isa.v1.ProblemDetails
}
var file_api_isa_v1_common_proto_depIdxs = []int32{
	0, // 0: api.isa.v1.ProblemDetails.code:type_name -> api.isa.v1.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_isa_v1_common_proto_init() }
func file_api_isa_v1_common_proto_init() {
	if File_api_isa_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_isa_v1_common_proto_rawDesc), len(file_api_isa_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_isa_v1_common_proto_goTypes,
		DependencyIndexes: file_api_isa_v1_common_proto_depIdxs,
		EnumInfos:         file_api_isa_v1_common_proto_enumTypes,
		MessageInfos:      file_api_isa_v1_common_proto_msgTypes,
	}.Build()
	File_api_isa_v1_common_proto = out.File
	file_api_isa_v1_common_proto_goTypes = nil
	file_api_isa_v1_common_proto_depIdxs = nil
}
