// health.proto defines the shared observability surface every ISA
// platform service exposes: a liveness probe (`/health`) and a
// readiness probe (`/ready`).
//
// The liveness probe reports in-process state only. It MUST NOT touch
// the database, the cache, or any network dependency; a failure means
// the process should be restarted.
//
// The readiness probe reports whether the service can serve real
// traffic right now. The shared ReadinessResponse below carries the
// canonical two typed probes (fields 3–4), a keyed map for additional
// downstream checks (field 5), and the evaluation timestamp (field 6).
// Service-specific handlers populate the typed slots with whichever
// dependencies they probe; wire numbers stay stable across products.
//
// Both endpoints return HTTP 200 with a typed response body when
// healthy. A failing liveness or readiness check returns HTTP 503 with
// a ProblemDetails body (see common.proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/isa/v1/health.proto

package isav1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServingStatus enumerates the probe outcomes shared by the liveness
// and readiness responses. Wire values are lowercase
// (`serving`, `not_serving`, `unknown`).
type ServingStatus int32

const (
	// Default zero value. Never emitted by the server; indicates a proto
	// deserialization defect on the client side.
	ServingStatus_SERVING_STATUS_UNSPECIFIED ServingStatus = 0
	// Component is healthy and accepting traffic.
	ServingStatus_SERVING_STATUS_SERVING ServingStatus = 1
	// Component is unhealthy; the overall probe returns 503 via
	// ProblemDetails when any required component is in this state.
	ServingStatus_SERVING_STATUS_NOT_SERVING ServingStatus = 2
	// Component state could not be determined within the probe budget
	// (e.g. timeout without a definitive success or failure).
	ServingStatus_SERVING_STATUS_UNKNOWN ServingStatus = 3
)

// Enum value maps for ServingStatus.
var (
	ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
		3: "SERVING_STATUS_UNKNOWN",
	}
	ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
		"SERVING_STATUS_UNKNOWN":     3,
	}
)

func (x ServingStatus) Enum() *ServingStatus {
	p := new(ServingStatus)
	*p = x
	return p
}

func (x ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_isa_v1_health_proto_enumTypes[0].Descriptor()
}

func (ServingStatus) Type() protoreflect.EnumType {
	return &file_api_isa_v1_health_proto_enumTypes[0]
}

func (x ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServingStatus.Descriptor instead.
func (ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_isa_v1_health_proto_rawDescGZIP(), []int{0}
}

// Status enumerates the probe outcomes. Exists inside the message so
// the wire type is unambiguously scoped to the liveness contract.
type LivenessResponse_Status int32

const (
	// Default zero value. Never emitted.
	LivenessResponse_STATUS_UNSPECIFIED LivenessResponse_Status = 0
	// Process is alive (liveness) or ready to serve traffic (readiness).
	LivenessResponse_STATUS_OK LivenessResponse_Status = 1
)

// Enum value maps for LivenessResponse_Status.
var (
	LivenessResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
	}
	LivenessResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
	}
)

func (x LivenessResponse_Status) Enum() *LivenessResponse_Status {
	p := new(LivenessResponse_Status)
	*p = x
	return p
}

func (x LivenessResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LivenessResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_isa_v1_health_proto_enumTypes[1].Descriptor()
}

func (LivenessResponse_Status) Type() protoreflect.EnumType {
	return &file_api_isa_v1_health_proto_enumTypes[1]
}

func (x LivenessResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LivenessResponse_Status.Descriptor instead.
func (LivenessResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_isa_v1_health_proto_rawDescGZIP(), []int{5, 0}
}

// GetHealthRequest is the empty request body for GET /health.
type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_api_isa_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_isa_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_isa_v1_health_proto_rawDescGZIP(), []int{0}
}

// HealthResponse reports liveness (in-process state only). Emitted with
// HTTP 200; a failing probe returns ProblemDetails on HTTP 503 instead.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall liveness status. On HTTP 200 this is always `SERVING`.
	Status ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.isa.v1.ServingStatus" json:"status,omitempty"`
	// Semantic version of the running binary (e.g. `1.42.0`). Matches
	// the git tag when deployed from a release; empty for local builds.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Full git commit SHA the binary was built from. Echoed into logs
	// and used by support to correlate behaviour with a revision.
	BuildSha string `protobuf:"bytes,3,opt,name=build_sha,json=buildSha,proto3" json:"build_sha,omitempty"`
	// Wall-clock time at which the process started accepting requests.
	// Paired with the current time to compute uptime client-side.
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_isa_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_isa_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_isa_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetBuildSha() string {
	if x != nil {
		return x.BuildSha
	}
	return ""
}

func (x *HealthResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// GetReadinessRequest is the empty request body for GET /ready.
type GetReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadinessRequest) Reset() {
	*x = GetReadinessRequest{}
	mi := &file_api_isa_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadinessRequest) ProtoMessage() {}

func (x *GetReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_isa_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadinessRequest.ProtoReflect.Descriptor instead.
func (*GetReadinessRequest) Descriptor() ([]byte, []int) {
	return file_api_isa_v1_health_proto_rawDescGZIP(), []int{2}
}

// ReadinessResponse is the shared readiness body. Field numbers 1–6
// match the historical ZyINS layout so existing binary decoders stay
// compatible; JSON field names for the two typed probes may differ from
// legacy RapidSign (`storage` / `emailer`) — callers must migrate to the
// unified keys (`db` / `cache`) alongside this consolidation.
type ReadinessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall readiness decision. True iff every required sub-probe
	// returned `SERVING`. A single `NOT_SERVING` among the required
	// probes flips this to false and the endpoint returns 503.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Overall status mirror of `ready` using the shared enum. Clients
	// that switch on `ServingStatus` across endpoints should read this
	// field; `ready` is retained for simple boolean checks.
	Status ServingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=api.isa.v1.ServingStatus" json:"status,omitempty"`
	// Primary dependency probe (ZyINS: database pool; RapidSign: document
	// storage). Same wire type across products; name reflects the ZyINS
	// canonical field label.
	Db *ProbeResult `protobuf:"bytes,3,opt,name=db,proto3" json:"db,omitempty"`
	// Secondary dependency probe (ZyINS: cache; RapidSign: emailer).
	Cache *ProbeResult `protobuf:"bytes,4,opt,name=cache,proto3" json:"cache,omitempty"`
	// Additional downstream probes keyed by logical service name (e.g.
	// `accounts`, `billing`, `eapp`). Order is not significant.
	DownstreamServices map[string]*ProbeResult `protobuf:"bytes,5,rep,name=downstream_services,json=downstreamServices,proto3" json:"downstream_services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Wall-clock time at which this readiness evaluation ran.
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_api_isa_v1_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_isa_v1_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_api_isa_v1_health_proto_rawDescGZIP(), []int{3}
}

func (x *ReadinessResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadinessResponse) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNSPECIFIED
}

func (x *ReadinessResponse) GetDb() *ProbeResult {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *ReadinessResponse) GetCache() *ProbeResult {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *ReadinessResponse) GetDownstreamServices() map[string]*ProbeResult {
	if x != nil {
		return x.DownstreamServices
	}
	return nil
}

func (x *ReadinessResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

// ProbeResult is the per-dependency readiness outcome. Carried inside
// every readiness response across the platform.
type ProbeResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current serving status of this dependency.
	Status ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.isa.v1.ServingStatus" json:"status,omitempty"`
	// Observed round-trip latency of the probe in milliseconds. Zero
	// when the probe could not complete (status == NOT_SERVING with a
	// synchronous failure or UNKNOWN with a timeout).
	LatencyMs int64 `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Human-readable explanation when `status` is not `SERVING`. Empty
	// on a healthy probe. Intended for operator dashboards; programmatic
	// consumers must switch on `status`, not parse this string.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Wall-clock time at which this specific probe was evaluated.
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_api_isa_v1_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_isa_v1_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_api_isa_v1_health_proto_rawDescGZIP(), []int{4}
}

func (x *ProbeResult) GetStatus() ServingStatus {
	if x != nil {
		return x.Status
	}
	return ServingStatus_SERVING_STATUS_UNSPECIFIED
}

func (x *ProbeResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ProbeResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProbeResult) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

// LivenessResponse is the minimal success body for GET /health and GET
// /ready per the platform health/readiness contract. Body is exactly
// {"status":"ok"}.
type LivenessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Liveness/readiness state. Only `ok` is ever emitted on success; a
	// failing probe returns ProblemDetails on HTTP 503 instead.
	Status        LivenessResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=api.isa.v1.LivenessResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessResponse) Reset() {
	*x = LivenessResponse{}
	mi := &file_api_isa_v1_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResponse) ProtoMessage() {}

func (x *LivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_isa_v1_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResponse.ProtoReflect.Descriptor instead.
func (*LivenessResponse) Descriptor() ([]byte, []int) {
	return file_api_isa_v1_health_proto_rawDescGZIP(), []int{5}
}

func (x *LivenessResponse) GetStatus() LivenessResponse_Status {
	if x != nil {
		return x.Status
	}
	return LivenessResponse_STATUS_UNSPECIFIED
}

var File_api_isa_v1_health_proto protoreflect.FileDescriptor

const file_api_isa_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x17api/isa/v1/health.proto\x12\n" +
	"api.isa.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10GetHealthRequest\"\xb5\x01\n" +
	"\x0eHealthResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.api.isa.v1.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tbuild_sha\x18\x03 \x01(\tR\bbuildSha\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x15\n" +
	"\x13GetReadinessRequest\"\xb7\x03\n" +
	"\x11ReadinessResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.api.isa.v1.ServingStatusR\x06status\x12'\n" +
	"\x02db\x18\x03 \x01(\v2\x17.api.isa.v1.ProbeResultR\x02db\x12-\n" +
	"\x05cache\x18\x04 \x01(\v2\x17.api.isa.v1.ProbeResultR\x05cache\x12f\n" +
	"\x13downstream_services\x18\x05 \x03(\v25.api.isa.v1.ReadinessResponse.DownstreamServicesEntryR\x12downstreamServices\x129\n" +
	"\n" +
	"checked_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x1a^\n" +
	"\x17DownstreamServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.api.isa.v1.ProbeResultR\x05value:\x028\x01\"\xb4\x01\n" +
	"\vProbeResult\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.api.isa.v1.ServingStatusR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x129\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\x80\x01\n" +
	"\x10LivenessResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.api.isa.v1.LivenessResponse.StatusR\x06status\"/\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01*\x87\x01\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\x1a\n" +
	"\x16SERVING_STATUS_UNKNOWN\x10\x032\xc7\x01\n" +
	"\rHealthService\x12V\n" +
	"\tGetHealth\x12\x1c.api.isa.v1.GetHealthRequest\x1a\x1a.api.isa.v1.HealthResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/health\x12^\n" +
	"\fGetReadiness\x12\x1f.api.isa.v1.GetReadinessRequest\x1a\x1d.api.isa.v1.ReadinessResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/readyB\xb7\x01\n" +
	"\x0ecom.api.isa.v1B\vHealthProtoP\x01ZEgithub.com/isa-sdk/sdk/core/api/isa/v1;isav1\xa2\x02\x03AIX\xaa\x02\x12IsaSdk.Core.Api.V1\xca\x02\x0eSah\\Isa\\Api\\V1\xe2\x02\x13Sah\\Isa\\Api\\V1\\Meta\xea\x02\fApi::Isa::V1b\x06proto3"

var (
	file_api_isa_v1_health_proto_rawDescOnce sync.Once
	file_api_isa_v1_health_proto_rawDescData []byte
)

func file_api_isa_v1_health_proto_rawDescGZIP() []byte {
	file_api_isa_v1_health_proto_rawDescOnce.Do(func() {
		file_api_isa_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_isa_v1_health_proto_rawDesc), len(file_api_isa_v1_health_proto_rawDesc)))
	})
	return file_api_isa_v1_health_proto_rawDescData
}

var file_api_isa_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_isa_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_isa_v1_health_proto_goTypes = []any{
	(ServingStatus)(0),            // 0: api.isa.v1.ServingStatus
	(LivenessResponse_Status)(0),  // 1: api.isa.v1.LivenessResponse.Status
	(*GetHealthRequest)(nil),      // 2: api.isa.v1.GetHealthRequest
	(*HealthResponse)(nil),        // 3: api.isa.v1.HealthResponse
	(*GetReadinessRequest)(nil),   // 4: api.isa.v1.GetReadinessRequest
	(*ReadinessResponse)(nil),     // 5: api.isa.v1.ReadinessResponse
	(*ProbeResult)(nil),           // 6: api.isa.v1.ProbeResult
	(*LivenessResponse)(nil),      // 7: api.isa.v1.LivenessResponse
	nil,                           // 8: api.isa.v1.ReadinessResponse.DownstreamServicesEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_isa_v1_health_proto_depIdxs = []int32{
	0,  // 0: api.isa.v1.HealthResponse.status:type_name -> api.isa.v1.ServingStatus
	9,  // 1: api.isa.v1.HealthResponse.started_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.isa.v1.ReadinessResponse.status:type_name -> api.isa.v1.ServingStatus
	6,  // 3: api.isa.v1.ReadinessResponse.db:type_name -> api.isa.v1.ProbeResult
	6,  // 4: api.isa.v1.ReadinessResponse.cache:type_name -> api.isa.v1.ProbeResult
	8,  // 5: api.isa.v1.ReadinessResponse.downstream_services:type_name -> api.isa.v1.ReadinessResponse.DownstreamServicesEntry
	9,  // 6: api.isa.v1.ReadinessResponse.checked_at:type_name -> google.protobuf.Timestamp
	0,  // 7: api.isa.v1.ProbeResult.status:type_name -> api.isa.v1.ServingStatus
	9,  // 8: api.isa.v1.ProbeResult.checked_at:type_name -> google.protobuf.Timestamp
	1,  // 9: api.isa.v1.LivenessResponse.status:type_name -> api.isa.v1.LivenessResponse.Status
	6,  // 10: api.isa.v1.ReadinessResponse.DownstreamServicesEntry.value:type_name -> api.isa.v1.ProbeResult
	2,  // 11: api.isa.v1.HealthService.GetHealth:input_type -> api.isa.v1.GetHealthRequest
	4,  // 12: api.isa.v1.HealthService.GetReadiness:input_type -> api.isa.v1.GetReadinessRequest
	3,  // 13: api.isa.v1.HealthService.GetHealth:output_type -> api.isa.v1.HealthResponse
	5,  // 14: api.isa.v1.HealthService.GetReadiness:output_type -> api.isa.v1.ReadinessResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_isa_v1_health_proto_init() }
func file_api_isa_v1_health_proto_init() {
	if File_api_isa_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_isa_v1_health_proto_rawDesc), len(file_api_isa_v1_health_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_isa_v1_health_proto_goTypes,
		DependencyIndexes: file_api_isa_v1_health_proto_depIdxs,
		EnumInfos:         file_api_isa_v1_health_proto_enumTypes,
		MessageInfos:      file_api_isa_v1_health_proto_msgTypes,
	}.Build()
	File_api_isa_v1_health_proto = out.File
	file_api_isa_v1_health_proto_goTypes = nil
	file_api_isa_v1_health_proto_depIdxs = nil
}
