//go:build ignore
// +build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
)

// Discovery mirrors the sibling generators (TS/Python/PHP/C#): the platform
// repo is four levels up from this script (packages/go/scripts/gen-catalog ->
// packages/go -> platform root); the engine repo that holds v2_products.json is
// one level above the platform repo. All three are overridable so the generator
// runs identically on a laptop, in the parity harness, and in CI — never bound
// to one developer's absolute paths.
//   SDK_CATALOG_OUT_DIR — where to write the generated catalog package.
//   SDK_PLATFORM_REPO    — isa-platform root (holds shared/schemas, shared/go).
//   SDK_INSURANCE_REPO   — engine repo root (holds v2_*.json).
var (
	outDir   = envOr("SDK_CATALOG_OUT_DIR", filepath.Join(platformRepoDefault(), "packages", "go", "catalog"))
	platRepo = envOr("SDK_PLATFORM_REPO", platformRepoDefault())
	insRepo  = envOr("SDK_INSURANCE_REPO", filepath.Clean(filepath.Join(platformRepoDefault(), "..")))
)

var gaps []string

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// platformRepoDefault resolves the isa-platform root from this script's own
// source location so the generator is path-independent. Falls back to the
// working directory when the caller location is unavailable.
func platformRepoDefault() string {
	if _, file, _, ok := runtime.Caller(0); ok {
		// file = <platform>/packages/go/scripts/gen-catalog/main.go
		return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", "..", ".."))
	}
	if wd, err := os.Getwd(); err == nil {
		return wd
	}
	return "."
}

func main() {
	os.MkdirAll(outDir, 0o755)
	genStates()
	genProductsAndCarriers()
	genMedications()
	genScopesAndErrors()
	genSignEvents()
	genIndex()
	if len(gaps) > 0 {
		fmt.Fprintln(os.Stderr, "gaps:")
		for _, g := range gaps {
			fmt.Fprintln(os.Stderr, "  -", g)
		}
	}
	fmt.Fprintln(os.Stderr, "done")
}

func header(sources []string) string {
	var b strings.Builder
	b.WriteString("// Code " + "generated by scripts/gen-catalog/main.go — do not hand-edit; rerun the generator.\n//\n")
	b.WriteString("// Source data:\n")
	for _, s := range sources {
		b.WriteString("//   - " + s + "\n")
	}
	b.WriteString("\npackage catalog\n\n")
	return b.String()
}

func writeFile(name, content string) {
	p := filepath.Join(outDir, name)
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		panic(err)
	}
	fmt.Fprintln(os.Stderr, "wrote", p)
}

// preserveOrFail handles a missing product data source without ever shipping an
// empty catalog. v2_products.json lives in the engine repo, which CI runners do
// not check out, so a clean build legitimately misses it. In that case the
// committed catalog is the source of truth — it carries the real prod_<uuid> ids
// and IS the published artifact — so preserve it untouched. Overwriting it with
// an empty stub is the isa-sdk@1.0.1 launch-blocker. With nothing committed to
// preserve, fail loud rather than let an empty catalog reach a registry.
func preserveOrFail(names []string, label string) {
	var missing []string
	for _, n := range names {
		if _, err := os.Stat(filepath.Join(outDir, n)); err != nil {
			missing = append(missing, n)
		}
	}
	if len(missing) > 0 {
		fmt.Fprintf(os.Stderr,
			"FATAL: %s: v2_products.json not found AND no committed catalog to preserve (%s). "+
				"Refusing to emit an empty product catalog. Run where %s exists, or commit a populated catalog first.\n",
			label, strings.Join(missing, ", "), filepath.Join(insRepo, "v2_products.json"))
		os.Exit(1)
	}
	gaps = append(gaps, label+": v2_products.json not found — preserving committed catalog.")
	for _, n := range names {
		fmt.Fprintln(os.Stderr, "preserved committed", filepath.Join(outDir, n))
	}
}

func pascal(s string) string {
	re := regexp.MustCompile(`[^a-zA-Z0-9]+`)
	parts := re.Split(s, -1)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(strings.ToLower(p[1:]))
		}
	}
	id := b.String()
	if id != "" && id[0] >= '0' && id[0] <= '9' {
		id = "X" + id
	}
	return id
}

func slugify(s string) string {
	out := strings.ToLower(s)
	out = regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(out, "-")
	return strings.Trim(out, "-")
}

func tryJSON(p string, dst any) bool {
	f, err := os.ReadFile(p)
	if err != nil {
		return false
	}
	if err := json.Unmarshal(f, dst); err != nil {
		fmt.Fprintln(os.Stderr, "parse", p, err)
		return false
	}
	return true
}

func tryText(p string) (string, bool) {
	f, err := os.ReadFile(p)
	if err != nil {
		return "", false
	}
	return string(f), true
}

func quoted(in []string) string {
	if len(in) == 0 {
		return "nil"
	}
	parts := make([]string, len(in))
	for i, s := range in {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func productSlice(in []string) string {
	if len(in) == 0 {
		return "nil"
	}
	parts := make([]string, len(in))
	for i, s := range in {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return "[]Product{" + strings.Join(parts, ", ") + "}"
}

// ---------- States ----------

type stateRow struct {
	Name, Abbr string
	T          bool
}

var statesTable = []stateRow{
	{"Alabama", "AL", false}, {"Alaska", "AK", false}, {"Arizona", "AZ", false}, {"Arkansas", "AR", false},
	{"California", "CA", false}, {"Colorado", "CO", false}, {"Connecticut", "CT", false}, {"Delaware", "DE", false},
	{"Florida", "FL", false}, {"Georgia", "GA", false}, {"Hawaii", "HI", false}, {"Idaho", "ID", false},
	{"Illinois", "IL", false}, {"Indiana", "IN", false}, {"Iowa", "IA", false}, {"Kansas", "KS", false},
	{"Kentucky", "KY", false}, {"Louisiana", "LA", false}, {"Maine", "ME", false}, {"Maryland", "MD", false},
	{"Massachusetts", "MA", false}, {"Michigan", "MI", false}, {"Minnesota", "MN", false}, {"Mississippi", "MS", false},
	{"Missouri", "MO", false}, {"Montana", "MT", false}, {"Nebraska", "NE", false}, {"Nevada", "NV", false},
	{"New Hampshire", "NH", false}, {"New Jersey", "NJ", false}, {"New Mexico", "NM", false}, {"New York", "NY", false},
	{"North Carolina", "NC", false}, {"North Dakota", "ND", false}, {"Ohio", "OH", false}, {"Oklahoma", "OK", false},
	{"Oregon", "OR", false}, {"Pennsylvania", "PA", false}, {"Rhode Island", "RI", false}, {"South Carolina", "SC", false},
	{"South Dakota", "SD", false}, {"Tennessee", "TN", false}, {"Texas", "TX", false}, {"Utah", "UT", false},
	{"Vermont", "VT", false}, {"Virginia", "VA", false}, {"Washington", "WA", false}, {"West Virginia", "WV", false},
	{"Wisconsin", "WI", false}, {"Wyoming", "WY", false}, {"District of Columbia", "DC", false},
	{"American Samoa", "AS", true}, {"Guam", "GU", true}, {"Northern Mariana Islands", "MP", true},
	{"Puerto Rico", "PR", true}, {"United States Virgin Islands", "VI", true},
}

func genStates() {
	sources := []string{"ISO 3166-2:US (50 states + DC + 5 inhabited territories)"}
	var b strings.Builder
	b.WriteString(strings.Replace(header(sources), "package catalog\n\n", "package catalog\n\nimport \"strings\"\n\n", 1))
	b.WriteString("// State is the ISO 3166-2:US abbreviation.\ntype State string\n\nconst (\n")
	for _, s := range statesTable {
		fmt.Fprintf(&b, "\tState%s State = %q\n", pascal(s.Name), s.Abbr)
	}
	b.WriteString(")\n\n// StateMetadata describes one State.\ntype StateMetadata struct {\n\tAbbreviation string\n\tName         string\n\tIsTerritory  bool\n}\n\n")
	b.WriteString("var stateMetadata = map[State]StateMetadata{\n")
	for _, s := range statesTable {
		fmt.Fprintf(&b, "\t%q: {Abbreviation: %q, Name: %q, IsTerritory: %t},\n", s.Abbr, s.Abbr, s.Name, s.T)
	}
	b.WriteString("}\n\nvar allStates = []State{\n")
	for _, s := range statesTable {
		fmt.Fprintf(&b, "\t%q,\n", s.Abbr)
	}
	b.WriteString("}\n\nvar stateByName = map[string]State{\n")
	for _, s := range statesTable {
		fmt.Fprintf(&b, "\t%q: %q,\n", strings.ToLower(s.Name), s.Abbr)
	}
	b.WriteString("}\n\ntype statesAPI struct{}\n\n// States is the catalog accessor.\nvar States statesAPI\n\n")
	b.WriteString("// Values returns every State, sorted by name.\nfunc (statesAPI) Values() []State { return append([]State(nil), allStates...) }\n\n")
	b.WriteString("// Metadata returns the StateMetadata for s and whether s is known.\nfunc (statesAPI) Metadata(s State) (StateMetadata, bool) {\n\tm, ok := stateMetadata[s]\n\treturn m, ok\n}\n\n")
	b.WriteString("// ByAbbreviation resolves by abbreviation or full name (case-insensitive).\nfunc (statesAPI) ByAbbreviation(s string) (State, bool) {\n\tup := strings.ToUpper(strings.TrimSpace(s))\n\tif _, ok := stateMetadata[State(up)]; ok { return State(up), true }\n\tif v, ok := stateByName[strings.ToLower(strings.TrimSpace(s))]; ok { return v, true }\n\treturn \"\", false\n}\n")
	writeFile("states.go", b.String())
}

// ---------- Products + Carriers ----------

type prod struct {
	ID, Slug, Class, CarrierDisplay, CarrierSlug, Name string
}

func fieldName(ident, cls string) string {
	prefix := cls + "-"
	stripped := ident
	if strings.HasPrefix(ident, prefix) {
		stripped = ident[len(prefix):]
	}
	return pascal(stripped)
}

func genProductsAndCarriers() {
	sources := []string{"insurance/v2_products.json"}
	var raw map[string][]map[string]any
	if !tryJSON(filepath.Join(insRepo, "v2_products.json"), &raw) {
		preserveOrFail([]string{"products.go", "carriers.go"}, "products")
		return
	}

	classOrder := []string{"fex", "medsup", "preneed", "term"}
	byClass := map[string][]prod{}
	for _, cls := range classOrder {
		byClass[cls] = nil
	}
	for cls, list := range raw {
		for _, p := range list {
			rawID, _ := p["id"].(string)
			ident, _ := p["identifier"].(string)
			name, _ := p["name"].(string)
			car, _ := p["carrier"].(string)
			if rawID == "" {
				fmt.Fprintf(os.Stderr, "ERROR: product %q in class %q has no id — failing loud\n", ident, cls)
				os.Exit(1)
			}
			byClass[cls] = append(byClass[cls], prod{
				ID:             "prod_" + rawID,
				Slug:           ident,
				Class:          cls,
				CarrierDisplay: car,
				CarrierSlug:    slugify(car),
				Name:           name,
			})
		}
	}
	for _, cls := range classOrder {
		sort.Slice(byClass[cls], func(i, j int) bool { return byClass[cls][i].Slug < byClass[cls][j].Slug })
	}

	classPascal := map[string]string{"fex": "Fex", "medsup": "Medsup", "preneed": "Preneed", "term": "Term"}
	total := 0
	for _, cls := range classOrder {
		total += len(byClass[cls])
	}

	var b strings.Builder
	b.WriteString(header(sources))
	b.WriteString(`// Product is a typed catalog entry for one carrier-product combination.
//
// The Id field (prod_<uuid>) is the only stable identity: it is the wire value
// for the v3 prequalify products[] filter, the catalog index key, and the ByID
// lookup key. Name and Carrier are mutable display data — never use them as
// identity. Slugs do not appear on this type.
type Product struct {
	// Id is the opaque product identifier (prod_<uuid>). Stable across carrier
	// renames; the sole wire value the server's products[] filter accepts.
	Id string
	// Name is the human-readable display name. Mutable — do not use as identity.
	Name string
	// Class is the coarse product family wire token (fex, medsup, preneed, term).
	Class string
	// Carrier is the carrier display name.
	Carrier string
}

`)
	// Emit named family types with unexported fields and exported accessor methods.
	// This is the immutability contract: callers use Products.Fex.AetnaAccendo()
	// (a method returning a by-value copy) instead of a mutable exported field.
	for _, cls := range classOrder {
		cp := classPascal[cls]
		typeName := cp + "Products"
		fmt.Fprintf(&b, "// %s is the read-only accessor for the %s product family.\n// Access products via the provided methods; each returns a by-value copy.\ntype %s struct{\n", typeName, strings.ToLower(cls), typeName)
		for _, p := range byClass[cls] {
			fn := fieldName(p.Slug, cls)
			uf := strings.ToLower(fn[:1]) + fn[1:]
			fmt.Fprintf(&b, "\t%s Product\n", uf)
		}
		b.WriteString("}\n\n")
		for _, p := range byClass[cls] {
			fn := fieldName(p.Slug, cls)
			uf := strings.ToLower(fn[:1]) + fn[1:]
			fmt.Fprintf(&b, "// %s returns the Product value for %s.\nfunc (f %s) %s() Product { return f.%s }\n\n", fn, p.Name, typeName, fn, uf)
		}
	}
	b.WriteString(`// productsAccessor is the immutable Products catalog accessor.
// Access family groups as Products.Fex, Products.Medsup, etc.
// Access individual products via family methods: Products.Fex.AetnaAccendo().
// All accessors return by-value copies; the underlying catalog data is immutable.
type productsAccessor struct {
	// Fex is the final expense product family accessor.
	Fex FexProducts
	// Medsup is the Medicare supplement product family accessor.
	Medsup MedsupProducts
	// Preneed is the preneed product family accessor.
	Preneed PreneedProducts
	// Term is the term life product family accessor.
	Term TermProducts
}

// Products is the nested catalog of all known products, grouped by family.
//
// Access individual products as Products.Fex.AetnaAccendo(), etc. Each accessor
// returns a by-value copy; the underlying catalog data cannot be mutated.
// Use ByID to resolve a prod_<uuid> identifier back to its Product value.
var Products = productsAccessor{
`)
	for _, cls := range classOrder {
		cp := classPascal[cls]
		typeName := cp + "Products"
		fmt.Fprintf(&b, "\t%s: %s{\n", cp, typeName)
		for _, p := range byClass[cls] {
			fn := fieldName(p.Slug, cls)
			uf := strings.ToLower(fn[:1]) + fn[1:]
			fmt.Fprintf(&b, "\t\t%s: Product{Id: %q, Name: %q, Class: %q, Carrier: %q},\n",
				uf, p.ID, p.Name, p.Class, p.CarrierDisplay)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	// byID is built from literal values (not from Products) so it cannot be desynced by mutations.
	fmt.Fprintf(&b, "// byID is the frozen id→Product reverse-lookup map built at package init.\n// It is built from the same literal data as Products, independent of the Products var.\nvar byID = func() map[string]Product {\n\tm := make(map[string]Product, %d)\n", total)
	for _, cls := range classOrder {
		for _, p := range byClass[cls] {
			fmt.Fprintf(&b, "\tm[%q] = Product{Id: %q, Name: %q, Class: %q, Carrier: %q}\n",
				p.ID, p.ID, p.Name, p.Class, p.CarrierDisplay)
		}
	}
	b.WriteString("\treturn m\n}()\n\n")

	b.WriteString("// ByID returns the Product with the given prod_<uuid> identifier and whether it\n")
	b.WriteString("// was found. It is the only supported catalog lookup: slugs and display names\n")
	b.WriteString("// are not stable identity and are not indexed.\n")
	b.WriteString("func ByID(id string) (Product, bool) {\n\tv, ok := byID[id]\n\treturn v, ok\n}\n\n")

	// productsAll snapshot — built at init from literal values so ProductsAll() is also desync-proof.
	fmt.Fprintf(&b, "// productsAll is the pre-computed by-value snapshot used by ProductsAll.\nvar productsAll = func() []Product {\n\tout := make([]Product, 0, %d)\n", total)
	for _, cls := range classOrder {
		for _, p := range byClass[cls] {
			fmt.Fprintf(&b, "\tout = append(out, Product{Id: %q, Name: %q, Class: %q, Carrier: %q})\n",
				p.ID, p.Name, p.Class, p.CarrierDisplay)
		}
	}
	b.WriteString("\treturn out\n}()\n\n")

	fmt.Fprintf(&b, "// ProductsAll returns every Product in the catalog, in family + alphabetical order.\nfunc ProductsAll() []Product {\n\tout := make([]Product, %d)\n\tcopy(out, productsAll)\n\treturn out\n}\n", total)
	writeFile("products.go", b.String())

	// Carriers
	byCar := map[string]*struct {
		Slug, Disp string
		IDs        []string
	}{}
	for _, cls := range classOrder {
		for _, p := range byClass[cls] {
			c, ok := byCar[p.CarrierSlug]
			if !ok {
				c = &struct {
					Slug, Disp string
					IDs        []string
				}{Slug: p.CarrierSlug, Disp: p.CarrierDisplay}
				byCar[p.CarrierSlug] = c
			}
			c.IDs = append(c.IDs, p.ID)
		}
	}
	carrierSlugs := make([]string, 0, len(byCar))
	for k := range byCar {
		carrierSlugs = append(carrierSlugs, k)
	}
	sort.Strings(carrierSlugs)
	var cv strings.Builder
	cv.WriteString(header(sources))
	cv.WriteString(`// CarrierMetadata describes one carrier. States is empty until upstream
// publishes per-carrier licensure data.
type CarrierMetadata struct {
	Slug, DisplayName string
	// ProductIDs holds the prod_<uuid> identifiers for this carrier's products.
	// Resolve each via ByID to get the full Product value.
	ProductIDs []string
	States     []State
}

`)
	cv.WriteString("var carrierMetadata = map[string]CarrierMetadata{\n")
	for _, s := range carrierSlugs {
		e := byCar[s]
		cv.WriteString(fmt.Sprintf("\t%q: {Slug: %q, DisplayName: %q, ProductIDs: %s},\n",
			e.Slug, e.Slug, e.Disp, quoted(e.IDs)))
	}
	cv.WriteString("}\n\nvar allCarriers = []string{\n")
	for _, s := range carrierSlugs {
		fmt.Fprintf(&cv, "\t%q,\n", s)
	}
	cv.WriteString("}\n\ntype carriersAPI struct{}\n\n// Carriers is the catalog accessor.\nvar Carriers carriersAPI\n\n")
	cv.WriteString("// Values returns every carrier slug, sorted alphabetically.\nfunc (carriersAPI) Values() []string { return append([]string(nil), allCarriers...) }\n\n")
	cv.WriteString("// Metadata returns the carrier metadata and whether slug is known.\nfunc (carriersAPI) Metadata(slug string) (CarrierMetadata, bool) {\n\tm, ok := carrierMetadata[slug]\n\treturn m, ok\n}\n")
	writeFile("carriers.go", cv.String())
}

// ---------- Medications ----------

func genMedications() {
	sources := []string{"insurance/v2_medications.json"}
	var meds []map[string]any
	if !tryJSON(filepath.Join(insRepo, "v2_medications.json"), &meds) {
		gaps = append(gaps, "medications missing")
		writeFile("medications.go", header(sources)+"type MedicationUseMetadata struct { DisplayName string; Medications []string }\nvar medicationUseMetadata = map[string]MedicationUseMetadata{}\nvar allMedicationUses = []string{}\ntype medicationUsesAPI struct{}\nvar MedicationUses medicationUsesAPI\nfunc (medicationUsesAPI) Values() []string { return nil }\nfunc (medicationUsesAPI) Metadata(string) (MedicationUseMetadata, bool) { return MedicationUseMetadata{}, false }\n")
		return
	}
	uses := map[string]map[string]bool{}
	for _, m := range meds {
		name, _ := m["name"].(string)
		if name == "" {
			continue
		}
		us, _ := m["uses"].([]any)
		for _, u := range us {
			um, ok := u.(map[string]any)
			if !ok {
				continue
			}
			cond, _ := um["condition"].(string)
			if cond == "" {
				continue
			}
			if uses[cond] == nil {
				uses[cond] = map[string]bool{}
			}
			uses[cond][name] = true
		}
	}
	names := make([]string, 0, len(uses))
	for k := range uses {
		names = append(names, k)
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString(header(sources))
	b.WriteString("// MedicationUseMetadata lists the medications recorded as treating one\n// canonical condition (engine wire format).\ntype MedicationUseMetadata struct {\n\tDisplayName string\n\tMedications []string\n}\n\n")
	b.WriteString("var medicationUseMetadata = map[string]MedicationUseMetadata{\n")
	for _, u := range names {
		ml := make([]string, 0, len(uses[u]))
		for m := range uses[u] {
			ml = append(ml, m)
		}
		sort.Strings(ml)
		fmt.Fprintf(&b, "\t%q: {DisplayName: %q, Medications: %s},\n", u, u, quoted(ml))
	}
	b.WriteString("}\n\nvar allMedicationUses = []string{\n")
	for _, u := range names {
		fmt.Fprintf(&b, "\t%q,\n", u)
	}
	b.WriteString("}\n\ntype medicationUsesAPI struct{}\n\n// MedicationUses is the catalog accessor.\nvar MedicationUses medicationUsesAPI\n\n")
	b.WriteString("// Values returns every use name, sorted alphabetically.\nfunc (medicationUsesAPI) Values() []string { return append([]string(nil), allMedicationUses...) }\n\n")
	b.WriteString("// Metadata returns the metadata for use and whether use is known.\nfunc (medicationUsesAPI) Metadata(use string) (MedicationUseMetadata, bool) {\n\tm, ok := medicationUseMetadata[use]\n\treturn m, ok\n}\n")
	writeFile("medications.go", b.String())
}

// ---------- Scopes + Errors ----------

func genScopesAndErrors() {
	sources := []string{"isa-platform/shared/schemas/api/isa/v1/common.proto"}
	text, ok := tryText(filepath.Join(platRepo, "shared/schemas/api/isa/v1/common.proto"))
	if !ok {
		gaps = append(gaps, "common.proto missing")
		writeFile("scopes.go", header(sources)+"type Scope string\nvar scopeDescriptions = map[Scope]string{}\ntype scopesAPI struct{}\nvar Scopes scopesAPI\nfunc (scopesAPI) Description(s Scope) string { return scopeDescriptions[s] }\n")
		writeFile("errors.go", header(sources)+"type ErrorCode string\nvar errorAdviceCodes = map[ErrorCode]string{}\nvar errorDocURLs = map[ErrorCode]string{}\ntype errorsAPI struct{}\nvar Errors errorsAPI\nfunc (errorsAPI) AdviceCode(c ErrorCode) string { return errorAdviceCodes[c] }\nfunc (errorsAPI) DocURL(c ErrorCode) string { return errorDocURLs[c] }\n")
		return
	}
	writeFile("scopes.go", buildScopes(text, sources))
	writeFile("errors.go", buildErrors(text, sources))
}

type entry struct{ Enum, Wire, Doc string }

func parseScopeEnum(body string) []entry {
	out := []entry{}
	lines := strings.Split(body, "\n")
	var pb strings.Builder
	for _, raw := range lines {
		t := strings.TrimSpace(raw)
		if strings.HasPrefix(t, "//") {
			pb.WriteString(" ")
			pb.WriteString(strings.TrimSpace(strings.TrimPrefix(t, "//")))
			continue
		}
		m := regexp.MustCompile(`^(SCOPE_[A-Z0-9_]+)\s*=\s*\d+;`).FindStringSubmatch(t)
		if len(m) == 2 {
			if m[1] == "SCOPE_UNSPECIFIED" {
				pb.Reset()
				continue
			}
			pending := pb.String()
			wm := regexp.MustCompile("`([^`]+)`").FindStringSubmatch(pending)
			if len(wm) < 2 {
				pb.Reset()
				continue
			}
			wire := wm[1]
			doc := strings.TrimSpace(regexp.MustCompile("`[^`]+`\\s*—?\\s*").ReplaceAllString(pending, ""))
			out = append(out, entry{Enum: pascal(strings.ReplaceAll(wire, ":", " ")), Wire: wire, Doc: doc})
			pb.Reset()
		} else if t == "" {
			pb.Reset()
		}
	}
	return out
}

func buildScopes(text string, sources []string) string {
	m := regexp.MustCompile(`(?ms)enum Scope \{(.*?)\}\s*$`).FindStringSubmatch(text)
	scopes := []entry{}
	if len(m) == 2 {
		scopes = parseScopeEnum(m[1])
	}
	sort.Slice(scopes, func(i, j int) bool { return scopes[i].Wire < scopes[j].Wire })
	var b strings.Builder
	b.WriteString(header(sources))
	b.WriteString("// Scope is the bearer-token scope identifier.\ntype Scope string\n\n")
	if len(scopes) > 0 {
		b.WriteString("const (\n")
		for _, s := range scopes {
			fmt.Fprintf(&b, "\t// %s\n\tScope%s Scope = %q\n", s.Doc, s.Enum, s.Wire)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("var scopeDescriptions = map[Scope]string{\n")
	for _, s := range scopes {
		fmt.Fprintf(&b, "\t%q: %q,\n", s.Wire, s.Doc)
	}
	b.WriteString("}\n\ntype scopesAPI struct{}\n\n// Scopes is the catalog accessor.\nvar Scopes scopesAPI\n\n// Description returns the documentation prose for s.\nfunc (scopesAPI) Description(s Scope) string { return scopeDescriptions[s] }\n")
	return b.String()
}

func parseErrorEnum(body string) []entry {
	out := []entry{}
	lines := strings.Split(body, "\n")
	var pb strings.Builder
	for _, raw := range lines {
		t := strings.TrimSpace(raw)
		if strings.HasPrefix(t, "//") {
			pb.WriteString(" ")
			pb.WriteString(strings.TrimSpace(strings.TrimPrefix(t, "//")))
			continue
		}
		m := regexp.MustCompile(`^ERROR_CODE_([A-Z0-9_]+)\s*=\s*\d+;`).FindStringSubmatch(t)
		if len(m) == 2 {
			if m[1] == "UNSPECIFIED" {
				pb.Reset()
				continue
			}
			out = append(out, entry{Enum: pascal(m[1]), Wire: strings.ToLower(m[1]), Doc: strings.TrimSpace(pb.String())})
			pb.Reset()
		} else if t == "" {
			pb.Reset()
		}
	}
	return out
}

func buildErrors(text string, sources []string) string {
	m := regexp.MustCompile(`(?ms)enum ErrorCode \{(.*?)\}`).FindStringSubmatch(text)
	codes := []entry{}
	if len(m) == 2 {
		codes = parseErrorEnum(m[1])
	}
	sort.Slice(codes, func(i, j int) bool { return codes[i].Wire < codes[j].Wire })
	advice := map[string]string{
		"validation_error": "fix_request_body", "idempotency_conflict": "retry_with_new_key",
		"rate_limit_exceeded": "wait_and_retry", "token_expired": "refresh_session",
		"invalid_token": "reissue_session", "license_locked": "contact_support",
		"forbidden": "check_scopes", "not_found": "verify_resource_id",
		"method_not_allowed": "check_http_method", "conflict": "reconcile_state",
		"unauthorized": "authenticate_caller", "internal_error": "retry_or_contact_support",
		"bad_gateway": "retry_with_backoff", "gateway_timeout": "retry_with_backoff",
		"service_unavailable": "retry_with_backoff", "not_implemented": "check_feature_availability",
	}
	var b strings.Builder
	b.WriteString(header(sources))
	b.WriteString("// ErrorCode is the stable wire-form error identifier.\ntype ErrorCode string\n\n")
	if len(codes) > 0 {
		b.WriteString("const (\n")
		for _, c := range codes {
			fmt.Fprintf(&b, "\t// %s\n\tErrorCode%s ErrorCode = %q\n", c.Doc, c.Enum, c.Wire)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("var errorAdviceCodes = map[ErrorCode]string{\n")
	for _, c := range codes {
		a := advice[c.Wire]
		if a == "" {
			a = "see_docs"
		}
		fmt.Fprintf(&b, "\t%q: %q,\n", c.Wire, a)
	}
	b.WriteString("}\n\nvar errorDocURLs = map[ErrorCode]string{\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "\t%q: \"https://docs.isaapi.com/errors/%s\",\n", c.Wire, c.Wire)
	}
	b.WriteString("}\n\ntype errorsAPI struct{}\n\n// Errors is the catalog accessor.\nvar Errors errorsAPI\n\n")
	b.WriteString("// AdviceCode returns the machine-readable next-action identifier for c.\nfunc (errorsAPI) AdviceCode(c ErrorCode) string { return errorAdviceCodes[c] }\n\n")
	b.WriteString("// DocURL returns the canonical documentation URL for c.\nfunc (errorsAPI) DocURL(c ErrorCode) string { return errorDocURLs[c] }\n")
	return b.String()
}

// ---------- SignEvents ----------

func genSignEvents() {
	sources := []string{"isa-platform/shared/go/events/registry.go"}
	text, ok := tryText(filepath.Join(platRepo, "shared/go/events/registry.go"))
	if !ok {
		gaps = append(gaps, "registry.go missing")
		writeFile("sign_events.go", header(sources)+"type SignEvent string\nvar signEventLabels = map[SignEvent]string{}\ntype signEventsAPI struct{}\nvar SignEvents signEventsAPI\nfunc (signEventsAPI) Label(e SignEvent) string { return signEventLabels[e] }\n")
		return
	}
	re := regexp.MustCompile(`EventType[A-Za-z0-9]+\s+EventType\s*=\s*"([^"]+)"`)
	type ev struct{ Enum, Wire string }
	out := []ev{}
	for _, m := range re.FindAllStringSubmatch(text, -1) {
		w := m[1]
		if !strings.HasPrefix(w, "document.") && !strings.HasPrefix(w, "signer.") {
			continue
		}
		var en strings.Builder
		for _, p := range strings.Split(w, ".") {
			en.WriteString(pascal(p))
		}
		out = append(out, ev{Enum: en.String(), Wire: w})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Wire < out[j].Wire })
	var b strings.Builder
	b.WriteString(header(sources))
	b.WriteString("// SignEvent is the EventBridge detail-type for RapidSign webhooks.\ntype SignEvent string\n\n")
	if len(out) > 0 {
		b.WriteString("const (\n")
		for _, e := range out {
			fmt.Fprintf(&b, "\tSignEvent%s SignEvent = %q\n", e.Enum, e.Wire)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString("var signEventLabels = map[SignEvent]string{\n")
	for _, e := range out {
		fmt.Fprintf(&b, "\t%q: %q,\n", e.Wire, e.Enum)
	}
	b.WriteString("}\n\ntype signEventsAPI struct{}\n\n// SignEvents is the catalog accessor.\nvar SignEvents signEventsAPI\n\n// Label returns the PascalCase identifier for e.\nfunc (signEventsAPI) Label(e SignEvent) string { return signEventLabels[e] }\n")
	writeFile("sign_events.go", b.String())
}

// ---------- Index ----------

func genIndex() {
	writeFile("doc.go", "// Package catalog exposes the auto-" + "generated catalogs of Products,\n// States, Carriers, MedicationUses, Scopes, SignEvents, and ErrorCodes.\n//\n// Sources are regenerated from the platform's reference data; do not\n// hand-edit. The empty-but-typed shape is honored for any source the\n// generator could not resolve.\npackage catalog\n")
}
