// accounts.proto defines the account, subscription-plan, and plan-rate
// management surface for the ZyINS Unified API. All routes are mounted
// under `zyins.isaapi.com/v1`.
//
// Accounts are the billing/service owners of API tokens (see
// tokens.proto). Each account is assigned exactly one SubscriptionPlan,
// which is billed per-endpoint via PlanRate entries. Authentication is
// BearerAuth on every RPC; create/update RPCs additionally require the
// admin scope, carried in the generated OpenAPI via the merge overlay
// (shared/schemas/overlays/zyins-v1.yaml) rather than inline annotations.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/zyins/v1/accounts.proto

package zyinsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/isa-sdk/sdk/zyins/api/zyins/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountsServiceName is the fully-qualified name of the AccountsService service.
	AccountsServiceName = "api.zyins.v1.AccountsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountsServiceCreateAccountProcedure is the fully-qualified name of the AccountsService's
	// CreateAccount RPC.
	AccountsServiceCreateAccountProcedure = "/api.zyins.v1.AccountsService/CreateAccount"
	// AccountsServiceGetAccountProcedure is the fully-qualified name of the AccountsService's
	// GetAccount RPC.
	AccountsServiceGetAccountProcedure = "/api.zyins.v1.AccountsService/GetAccount"
	// AccountsServiceListAccountsProcedure is the fully-qualified name of the AccountsService's
	// ListAccounts RPC.
	AccountsServiceListAccountsProcedure = "/api.zyins.v1.AccountsService/ListAccounts"
	// AccountsServiceUpdateAccountPlanProcedure is the fully-qualified name of the AccountsService's
	// UpdateAccountPlan RPC.
	AccountsServiceUpdateAccountPlanProcedure = "/api.zyins.v1.AccountsService/UpdateAccountPlan"
	// AccountsServiceGetPlanProcedure is the fully-qualified name of the AccountsService's GetPlan RPC.
	AccountsServiceGetPlanProcedure = "/api.zyins.v1.AccountsService/GetPlan"
	// AccountsServiceListPlansProcedure is the fully-qualified name of the AccountsService's ListPlans
	// RPC.
	AccountsServiceListPlansProcedure = "/api.zyins.v1.AccountsService/ListPlans"
	// AccountsServiceCreatePlanProcedure is the fully-qualified name of the AccountsService's
	// CreatePlan RPC.
	AccountsServiceCreatePlanProcedure = "/api.zyins.v1.AccountsService/CreatePlan"
	// AccountsServiceGetPlanRatesProcedure is the fully-qualified name of the AccountsService's
	// GetPlanRates RPC.
	AccountsServiceGetPlanRatesProcedure = "/api.zyins.v1.AccountsService/GetPlanRates"
	// AccountsServiceSetPlanRateProcedure is the fully-qualified name of the AccountsService's
	// SetPlanRate RPC.
	AccountsServiceSetPlanRateProcedure = "/api.zyins.v1.AccountsService/SetPlanRate"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	accountsServiceServiceDescriptor                 = v1.File_api_zyins_v1_accounts_proto.Services().ByName("AccountsService")
	accountsServiceCreateAccountMethodDescriptor     = accountsServiceServiceDescriptor.Methods().ByName("CreateAccount")
	accountsServiceGetAccountMethodDescriptor        = accountsServiceServiceDescriptor.Methods().ByName("GetAccount")
	accountsServiceListAccountsMethodDescriptor      = accountsServiceServiceDescriptor.Methods().ByName("ListAccounts")
	accountsServiceUpdateAccountPlanMethodDescriptor = accountsServiceServiceDescriptor.Methods().ByName("UpdateAccountPlan")
	accountsServiceGetPlanMethodDescriptor           = accountsServiceServiceDescriptor.Methods().ByName("GetPlan")
	accountsServiceListPlansMethodDescriptor         = accountsServiceServiceDescriptor.Methods().ByName("ListPlans")
	accountsServiceCreatePlanMethodDescriptor        = accountsServiceServiceDescriptor.Methods().ByName("CreatePlan")
	accountsServiceGetPlanRatesMethodDescriptor      = accountsServiceServiceDescriptor.Methods().ByName("GetPlanRates")
	accountsServiceSetPlanRateMethodDescriptor       = accountsServiceServiceDescriptor.Methods().ByName("SetPlanRate")
)

// AccountsServiceClient is a client for the api.zyins.v1.AccountsService service.
type AccountsServiceClient interface {
	// CreateAccount provisions a new billing/service account. The caller
	// supplies the account id (externally assigned, e.g. from the identity
	// provider); the server rejects duplicates with CONFLICT.
	CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.AccountDetail], error)
	// GetAccount returns a single account by id.
	GetAccount(context.Context, *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.AccountDetail], error)
	// ListAccounts returns every account visible to the caller. Admin
	// surface; non-admin callers receive only their own account.
	ListAccounts(context.Context, *connect.Request[v1.ListAccountsRequest]) (*connect.Response[v1.ListAccountsResponse], error)
	// UpdateAccountPlan reassigns the subscription plan for an account.
	// Effective immediately; no proration is performed at this layer.
	UpdateAccountPlan(context.Context, *connect.Request[v1.UpdateAccountPlanRequest]) (*connect.Response[v1.AccountDetail], error)
	// GetPlan returns a single subscription plan by id.
	GetPlan(context.Context, *connect.Request[v1.GetPlanRequest]) (*connect.Response[v1.PlanDetail], error)
	// ListPlans returns every subscription plan available to assign.
	ListPlans(context.Context, *connect.Request[v1.ListPlansRequest]) (*connect.Response[v1.ListPlansResponse], error)
	// CreatePlan provisions a new subscription plan. Admin surface.
	CreatePlan(context.Context, *connect.Request[v1.CreatePlanRequest]) (*connect.Response[v1.PlanDetail], error)
	// GetPlanRates returns every per-metric rate configured for a plan.
	GetPlanRates(context.Context, *connect.Request[v1.GetPlanRatesRequest]) (*connect.Response[v1.ListPlanRatesResponse], error)
	// SetPlanRate upserts the rate for a single metric on a plan. Admin
	// surface; changes apply at `effective_at`.
	SetPlanRate(context.Context, *connect.Request[v1.SetPlanRateRequest]) (*connect.Response[v1.SetPlanRateResponse], error)
}

// NewAccountsServiceClient constructs a client for the api.zyins.v1.AccountsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &accountsServiceClient{
		createAccount: connect.NewClient[v1.CreateAccountRequest, v1.AccountDetail](
			httpClient,
			baseURL+AccountsServiceCreateAccountProcedure,
			connect.WithSchema(accountsServiceCreateAccountMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAccount: connect.NewClient[v1.GetAccountRequest, v1.AccountDetail](
			httpClient,
			baseURL+AccountsServiceGetAccountProcedure,
			connect.WithSchema(accountsServiceGetAccountMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listAccounts: connect.NewClient[v1.ListAccountsRequest, v1.ListAccountsResponse](
			httpClient,
			baseURL+AccountsServiceListAccountsProcedure,
			connect.WithSchema(accountsServiceListAccountsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateAccountPlan: connect.NewClient[v1.UpdateAccountPlanRequest, v1.AccountDetail](
			httpClient,
			baseURL+AccountsServiceUpdateAccountPlanProcedure,
			connect.WithSchema(accountsServiceUpdateAccountPlanMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getPlan: connect.NewClient[v1.GetPlanRequest, v1.PlanDetail](
			httpClient,
			baseURL+AccountsServiceGetPlanProcedure,
			connect.WithSchema(accountsServiceGetPlanMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listPlans: connect.NewClient[v1.ListPlansRequest, v1.ListPlansResponse](
			httpClient,
			baseURL+AccountsServiceListPlansProcedure,
			connect.WithSchema(accountsServiceListPlansMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createPlan: connect.NewClient[v1.CreatePlanRequest, v1.PlanDetail](
			httpClient,
			baseURL+AccountsServiceCreatePlanProcedure,
			connect.WithSchema(accountsServiceCreatePlanMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getPlanRates: connect.NewClient[v1.GetPlanRatesRequest, v1.ListPlanRatesResponse](
			httpClient,
			baseURL+AccountsServiceGetPlanRatesProcedure,
			connect.WithSchema(accountsServiceGetPlanRatesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setPlanRate: connect.NewClient[v1.SetPlanRateRequest, v1.SetPlanRateResponse](
			httpClient,
			baseURL+AccountsServiceSetPlanRateProcedure,
			connect.WithSchema(accountsServiceSetPlanRateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountsServiceClient implements AccountsServiceClient.
type accountsServiceClient struct {
	createAccount     *connect.Client[v1.CreateAccountRequest, v1.AccountDetail]
	getAccount        *connect.Client[v1.GetAccountRequest, v1.AccountDetail]
	listAccounts      *connect.Client[v1.ListAccountsRequest, v1.ListAccountsResponse]
	updateAccountPlan *connect.Client[v1.UpdateAccountPlanRequest, v1.AccountDetail]
	getPlan           *connect.Client[v1.GetPlanRequest, v1.PlanDetail]
	listPlans         *connect.Client[v1.ListPlansRequest, v1.ListPlansResponse]
	createPlan        *connect.Client[v1.CreatePlanRequest, v1.PlanDetail]
	getPlanRates      *connect.Client[v1.GetPlanRatesRequest, v1.ListPlanRatesResponse]
	setPlanRate       *connect.Client[v1.SetPlanRateRequest, v1.SetPlanRateResponse]
}

// CreateAccount calls api.zyins.v1.AccountsService.CreateAccount.
func (c *accountsServiceClient) CreateAccount(ctx context.Context, req *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.AccountDetail], error) {
	return c.createAccount.CallUnary(ctx, req)
}

// GetAccount calls api.zyins.v1.AccountsService.GetAccount.
func (c *accountsServiceClient) GetAccount(ctx context.Context, req *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.AccountDetail], error) {
	return c.getAccount.CallUnary(ctx, req)
}

// ListAccounts calls api.zyins.v1.AccountsService.ListAccounts.
func (c *accountsServiceClient) ListAccounts(ctx context.Context, req *connect.Request[v1.ListAccountsRequest]) (*connect.Response[v1.ListAccountsResponse], error) {
	return c.listAccounts.CallUnary(ctx, req)
}

// UpdateAccountPlan calls api.zyins.v1.AccountsService.UpdateAccountPlan.
func (c *accountsServiceClient) UpdateAccountPlan(ctx context.Context, req *connect.Request[v1.UpdateAccountPlanRequest]) (*connect.Response[v1.AccountDetail], error) {
	return c.updateAccountPlan.CallUnary(ctx, req)
}

// GetPlan calls api.zyins.v1.AccountsService.GetPlan.
func (c *accountsServiceClient) GetPlan(ctx context.Context, req *connect.Request[v1.GetPlanRequest]) (*connect.Response[v1.PlanDetail], error) {
	return c.getPlan.CallUnary(ctx, req)
}

// ListPlans calls api.zyins.v1.AccountsService.ListPlans.
func (c *accountsServiceClient) ListPlans(ctx context.Context, req *connect.Request[v1.ListPlansRequest]) (*connect.Response[v1.ListPlansResponse], error) {
	return c.listPlans.CallUnary(ctx, req)
}

// CreatePlan calls api.zyins.v1.AccountsService.CreatePlan.
func (c *accountsServiceClient) CreatePlan(ctx context.Context, req *connect.Request[v1.CreatePlanRequest]) (*connect.Response[v1.PlanDetail], error) {
	return c.createPlan.CallUnary(ctx, req)
}

// GetPlanRates calls api.zyins.v1.AccountsService.GetPlanRates.
func (c *accountsServiceClient) GetPlanRates(ctx context.Context, req *connect.Request[v1.GetPlanRatesRequest]) (*connect.Response[v1.ListPlanRatesResponse], error) {
	return c.getPlanRates.CallUnary(ctx, req)
}

// SetPlanRate calls api.zyins.v1.AccountsService.SetPlanRate.
func (c *accountsServiceClient) SetPlanRate(ctx context.Context, req *connect.Request[v1.SetPlanRateRequest]) (*connect.Response[v1.SetPlanRateResponse], error) {
	return c.setPlanRate.CallUnary(ctx, req)
}

// AccountsServiceHandler is an implementation of the api.zyins.v1.AccountsService service.
type AccountsServiceHandler interface {
	// CreateAccount provisions a new billing/service account. The caller
	// supplies the account id (externally assigned, e.g. from the identity
	// provider); the server rejects duplicates with CONFLICT.
	CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.AccountDetail], error)
	// GetAccount returns a single account by id.
	GetAccount(context.Context, *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.AccountDetail], error)
	// ListAccounts returns every account visible to the caller. Admin
	// surface; non-admin callers receive only their own account.
	ListAccounts(context.Context, *connect.Request[v1.ListAccountsRequest]) (*connect.Response[v1.ListAccountsResponse], error)
	// UpdateAccountPlan reassigns the subscription plan for an account.
	// Effective immediately; no proration is performed at this layer.
	UpdateAccountPlan(context.Context, *connect.Request[v1.UpdateAccountPlanRequest]) (*connect.Response[v1.AccountDetail], error)
	// GetPlan returns a single subscription plan by id.
	GetPlan(context.Context, *connect.Request[v1.GetPlanRequest]) (*connect.Response[v1.PlanDetail], error)
	// ListPlans returns every subscription plan available to assign.
	ListPlans(context.Context, *connect.Request[v1.ListPlansRequest]) (*connect.Response[v1.ListPlansResponse], error)
	// CreatePlan provisions a new subscription plan. Admin surface.
	CreatePlan(context.Context, *connect.Request[v1.CreatePlanRequest]) (*connect.Response[v1.PlanDetail], error)
	// GetPlanRates returns every per-metric rate configured for a plan.
	GetPlanRates(context.Context, *connect.Request[v1.GetPlanRatesRequest]) (*connect.Response[v1.ListPlanRatesResponse], error)
	// SetPlanRate upserts the rate for a single metric on a plan. Admin
	// surface; changes apply at `effective_at`.
	SetPlanRate(context.Context, *connect.Request[v1.SetPlanRateRequest]) (*connect.Response[v1.SetPlanRateResponse], error)
}

// NewAccountsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountsServiceHandler(svc AccountsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountsServiceCreateAccountHandler := connect.NewUnaryHandler(
		AccountsServiceCreateAccountProcedure,
		svc.CreateAccount,
		connect.WithSchema(accountsServiceCreateAccountMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceGetAccountHandler := connect.NewUnaryHandler(
		AccountsServiceGetAccountProcedure,
		svc.GetAccount,
		connect.WithSchema(accountsServiceGetAccountMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceListAccountsHandler := connect.NewUnaryHandler(
		AccountsServiceListAccountsProcedure,
		svc.ListAccounts,
		connect.WithSchema(accountsServiceListAccountsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceUpdateAccountPlanHandler := connect.NewUnaryHandler(
		AccountsServiceUpdateAccountPlanProcedure,
		svc.UpdateAccountPlan,
		connect.WithSchema(accountsServiceUpdateAccountPlanMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceGetPlanHandler := connect.NewUnaryHandler(
		AccountsServiceGetPlanProcedure,
		svc.GetPlan,
		connect.WithSchema(accountsServiceGetPlanMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceListPlansHandler := connect.NewUnaryHandler(
		AccountsServiceListPlansProcedure,
		svc.ListPlans,
		connect.WithSchema(accountsServiceListPlansMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceCreatePlanHandler := connect.NewUnaryHandler(
		AccountsServiceCreatePlanProcedure,
		svc.CreatePlan,
		connect.WithSchema(accountsServiceCreatePlanMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceGetPlanRatesHandler := connect.NewUnaryHandler(
		AccountsServiceGetPlanRatesProcedure,
		svc.GetPlanRates,
		connect.WithSchema(accountsServiceGetPlanRatesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	accountsServiceSetPlanRateHandler := connect.NewUnaryHandler(
		AccountsServiceSetPlanRateProcedure,
		svc.SetPlanRate,
		connect.WithSchema(accountsServiceSetPlanRateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.zyins.v1.AccountsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountsServiceCreateAccountProcedure:
			accountsServiceCreateAccountHandler.ServeHTTP(w, r)
		case AccountsServiceGetAccountProcedure:
			accountsServiceGetAccountHandler.ServeHTTP(w, r)
		case AccountsServiceListAccountsProcedure:
			accountsServiceListAccountsHandler.ServeHTTP(w, r)
		case AccountsServiceUpdateAccountPlanProcedure:
			accountsServiceUpdateAccountPlanHandler.ServeHTTP(w, r)
		case AccountsServiceGetPlanProcedure:
			accountsServiceGetPlanHandler.ServeHTTP(w, r)
		case AccountsServiceListPlansProcedure:
			accountsServiceListPlansHandler.ServeHTTP(w, r)
		case AccountsServiceCreatePlanProcedure:
			accountsServiceCreatePlanHandler.ServeHTTP(w, r)
		case AccountsServiceGetPlanRatesProcedure:
			accountsServiceGetPlanRatesHandler.ServeHTTP(w, r)
		case AccountsServiceSetPlanRateProcedure:
			accountsServiceSetPlanRateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountsServiceHandler struct{}

func (UnimplementedAccountsServiceHandler) CreateAccount(context.Context, *connect.Request[v1.CreateAccountRequest]) (*connect.Response[v1.AccountDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.CreateAccount is not implemented"))
}

func (UnimplementedAccountsServiceHandler) GetAccount(context.Context, *connect.Request[v1.GetAccountRequest]) (*connect.Response[v1.AccountDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.GetAccount is not implemented"))
}

func (UnimplementedAccountsServiceHandler) ListAccounts(context.Context, *connect.Request[v1.ListAccountsRequest]) (*connect.Response[v1.ListAccountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.ListAccounts is not implemented"))
}

func (UnimplementedAccountsServiceHandler) UpdateAccountPlan(context.Context, *connect.Request[v1.UpdateAccountPlanRequest]) (*connect.Response[v1.AccountDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.UpdateAccountPlan is not implemented"))
}

func (UnimplementedAccountsServiceHandler) GetPlan(context.Context, *connect.Request[v1.GetPlanRequest]) (*connect.Response[v1.PlanDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.GetPlan is not implemented"))
}

func (UnimplementedAccountsServiceHandler) ListPlans(context.Context, *connect.Request[v1.ListPlansRequest]) (*connect.Response[v1.ListPlansResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.ListPlans is not implemented"))
}

func (UnimplementedAccountsServiceHandler) CreatePlan(context.Context, *connect.Request[v1.CreatePlanRequest]) (*connect.Response[v1.PlanDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.CreatePlan is not implemented"))
}

func (UnimplementedAccountsServiceHandler) GetPlanRates(context.Context, *connect.Request[v1.GetPlanRatesRequest]) (*connect.Response[v1.ListPlanRatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.GetPlanRates is not implemented"))
}

func (UnimplementedAccountsServiceHandler) SetPlanRate(context.Context, *connect.Request[v1.SetPlanRateRequest]) (*connect.Response[v1.SetPlanRateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.AccountsService.SetPlanRate is not implemented"))
}
