// cases.proto defines the account-scoped case persistence surface for the
// ZyINS Unified API. A "case" is an immutable, content-addressable
// snapshot of an underwriting evaluation (input + optional results +
// product list) that can be linked to from outside the API — the
// canonical agent-facing URL is `https://bestplanpro.com/?case=<hash>`.
//
// All routes are mounted under `zyins.isaapi.com/v1`. Every operation is
// account-scoped: the calling token determines `account_id`, every read
// filters by `account_id`, and there is no cross-account visibility at
// the query layer. Storage backs onto PostgreSQL (`store.CaseRepository`)
// with content-hash deduplication; large payloads spill to S3 with the
// row carrying an `s3_key` reference.
//
// Companion guides for integrators live in `api/guides/cases.md`. This
// file is the wire contract; the guides explain the dedup model, the
// readonly semantics, and the email helper.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/zyins/v1/cases.proto

package zyinsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/isa-sdk/sdk/zyins/api/zyins/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CasesServiceName is the fully-qualified name of the CasesService service.
	CasesServiceName = "api.zyins.v1.CasesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CasesServiceCreateCaseProcedure is the fully-qualified name of the CasesService's CreateCase RPC.
	CasesServiceCreateCaseProcedure = "/api.zyins.v1.CasesService/CreateCase"
	// CasesServiceGetCaseProcedure is the fully-qualified name of the CasesService's GetCase RPC.
	CasesServiceGetCaseProcedure = "/api.zyins.v1.CasesService/GetCase"
	// CasesServiceListCasesProcedure is the fully-qualified name of the CasesService's ListCases RPC.
	CasesServiceListCasesProcedure = "/api.zyins.v1.CasesService/ListCases"
	// CasesServiceEmailCaseProcedure is the fully-qualified name of the CasesService's EmailCase RPC.
	CasesServiceEmailCaseProcedure = "/api.zyins.v1.CasesService/EmailCase"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	casesServiceServiceDescriptor          = v1.File_api_zyins_v1_cases_proto.Services().ByName("CasesService")
	casesServiceCreateCaseMethodDescriptor = casesServiceServiceDescriptor.Methods().ByName("CreateCase")
	casesServiceGetCaseMethodDescriptor    = casesServiceServiceDescriptor.Methods().ByName("GetCase")
	casesServiceListCasesMethodDescriptor  = casesServiceServiceDescriptor.Methods().ByName("ListCases")
	casesServiceEmailCaseMethodDescriptor  = casesServiceServiceDescriptor.Methods().ByName("EmailCase")
)

// CasesServiceClient is a client for the api.zyins.v1.CasesService service.
type CasesServiceClient interface {
	// CreateCase persists a case snapshot and returns its short hash.
	// Idempotent on the canonical content hash: identical inputs return
	// the existing hash without creating a duplicate row.
	CreateCase(context.Context, *connect.Request[v1.CreateCaseRequest]) (*connect.Response[v1.CaseDetail], error)
	// GetCase returns a single case by short hash. Filters by the calling
	// account; cases owned by other accounts are reported as `not_found`.
	GetCase(context.Context, *connect.Request[v1.GetCaseRequest]) (*connect.Response[v1.CaseDetail], error)
	// ListCases returns the calling account's cases in descending creation
	// order. Cursor-paginated per ADR-024.
	ListCases(context.Context, *connect.Request[v1.ListCasesRequest]) (*connect.Response[v1.ListCasesResponse], error)
	// EmailCase sends a stored case to a recipient via the platform's
	// email transport. The body of the email is the rendered case link
	// plus an optional caller-supplied note. Idempotent on
	// `Idempotency-Key`.
	EmailCase(context.Context, *connect.Request[v1.EmailCaseRequest]) (*connect.Response[v1.EmailCaseResponse], error)
}

// NewCasesServiceClient constructs a client for the api.zyins.v1.CasesService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCasesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CasesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &casesServiceClient{
		createCase: connect.NewClient[v1.CreateCaseRequest, v1.CaseDetail](
			httpClient,
			baseURL+CasesServiceCreateCaseProcedure,
			connect.WithSchema(casesServiceCreateCaseMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getCase: connect.NewClient[v1.GetCaseRequest, v1.CaseDetail](
			httpClient,
			baseURL+CasesServiceGetCaseProcedure,
			connect.WithSchema(casesServiceGetCaseMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listCases: connect.NewClient[v1.ListCasesRequest, v1.ListCasesResponse](
			httpClient,
			baseURL+CasesServiceListCasesProcedure,
			connect.WithSchema(casesServiceListCasesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		emailCase: connect.NewClient[v1.EmailCaseRequest, v1.EmailCaseResponse](
			httpClient,
			baseURL+CasesServiceEmailCaseProcedure,
			connect.WithSchema(casesServiceEmailCaseMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// casesServiceClient implements CasesServiceClient.
type casesServiceClient struct {
	createCase *connect.Client[v1.CreateCaseRequest, v1.CaseDetail]
	getCase    *connect.Client[v1.GetCaseRequest, v1.CaseDetail]
	listCases  *connect.Client[v1.ListCasesRequest, v1.ListCasesResponse]
	emailCase  *connect.Client[v1.EmailCaseRequest, v1.EmailCaseResponse]
}

// CreateCase calls api.zyins.v1.CasesService.CreateCase.
func (c *casesServiceClient) CreateCase(ctx context.Context, req *connect.Request[v1.CreateCaseRequest]) (*connect.Response[v1.CaseDetail], error) {
	return c.createCase.CallUnary(ctx, req)
}

// GetCase calls api.zyins.v1.CasesService.GetCase.
func (c *casesServiceClient) GetCase(ctx context.Context, req *connect.Request[v1.GetCaseRequest]) (*connect.Response[v1.CaseDetail], error) {
	return c.getCase.CallUnary(ctx, req)
}

// ListCases calls api.zyins.v1.CasesService.ListCases.
func (c *casesServiceClient) ListCases(ctx context.Context, req *connect.Request[v1.ListCasesRequest]) (*connect.Response[v1.ListCasesResponse], error) {
	return c.listCases.CallUnary(ctx, req)
}

// EmailCase calls api.zyins.v1.CasesService.EmailCase.
func (c *casesServiceClient) EmailCase(ctx context.Context, req *connect.Request[v1.EmailCaseRequest]) (*connect.Response[v1.EmailCaseResponse], error) {
	return c.emailCase.CallUnary(ctx, req)
}

// CasesServiceHandler is an implementation of the api.zyins.v1.CasesService service.
type CasesServiceHandler interface {
	// CreateCase persists a case snapshot and returns its short hash.
	// Idempotent on the canonical content hash: identical inputs return
	// the existing hash without creating a duplicate row.
	CreateCase(context.Context, *connect.Request[v1.CreateCaseRequest]) (*connect.Response[v1.CaseDetail], error)
	// GetCase returns a single case by short hash. Filters by the calling
	// account; cases owned by other accounts are reported as `not_found`.
	GetCase(context.Context, *connect.Request[v1.GetCaseRequest]) (*connect.Response[v1.CaseDetail], error)
	// ListCases returns the calling account's cases in descending creation
	// order. Cursor-paginated per ADR-024.
	ListCases(context.Context, *connect.Request[v1.ListCasesRequest]) (*connect.Response[v1.ListCasesResponse], error)
	// EmailCase sends a stored case to a recipient via the platform's
	// email transport. The body of the email is the rendered case link
	// plus an optional caller-supplied note. Idempotent on
	// `Idempotency-Key`.
	EmailCase(context.Context, *connect.Request[v1.EmailCaseRequest]) (*connect.Response[v1.EmailCaseResponse], error)
}

// NewCasesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCasesServiceHandler(svc CasesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	casesServiceCreateCaseHandler := connect.NewUnaryHandler(
		CasesServiceCreateCaseProcedure,
		svc.CreateCase,
		connect.WithSchema(casesServiceCreateCaseMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	casesServiceGetCaseHandler := connect.NewUnaryHandler(
		CasesServiceGetCaseProcedure,
		svc.GetCase,
		connect.WithSchema(casesServiceGetCaseMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	casesServiceListCasesHandler := connect.NewUnaryHandler(
		CasesServiceListCasesProcedure,
		svc.ListCases,
		connect.WithSchema(casesServiceListCasesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	casesServiceEmailCaseHandler := connect.NewUnaryHandler(
		CasesServiceEmailCaseProcedure,
		svc.EmailCase,
		connect.WithSchema(casesServiceEmailCaseMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.zyins.v1.CasesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CasesServiceCreateCaseProcedure:
			casesServiceCreateCaseHandler.ServeHTTP(w, r)
		case CasesServiceGetCaseProcedure:
			casesServiceGetCaseHandler.ServeHTTP(w, r)
		case CasesServiceListCasesProcedure:
			casesServiceListCasesHandler.ServeHTTP(w, r)
		case CasesServiceEmailCaseProcedure:
			casesServiceEmailCaseHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCasesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCasesServiceHandler struct{}

func (UnimplementedCasesServiceHandler) CreateCase(context.Context, *connect.Request[v1.CreateCaseRequest]) (*connect.Response[v1.CaseDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.CasesService.CreateCase is not implemented"))
}

func (UnimplementedCasesServiceHandler) GetCase(context.Context, *connect.Request[v1.GetCaseRequest]) (*connect.Response[v1.CaseDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.CasesService.GetCase is not implemented"))
}

func (UnimplementedCasesServiceHandler) ListCases(context.Context, *connect.Request[v1.ListCasesRequest]) (*connect.Response[v1.ListCasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.CasesService.ListCases is not implemented"))
}

func (UnimplementedCasesServiceHandler) EmailCase(context.Context, *connect.Request[v1.EmailCaseRequest]) (*connect.Response[v1.EmailCaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.CasesService.EmailCase is not implemented"))
}
