// email.proto defines the account-scoped transactional email enqueue
// surface for the ZyINS Unified API. Mounted at
// `zyins.isaapi.com/v1/email/enqueue`.
//
// The send path is asynchronous: the handler validates and persists the
// payload to `email_queue`, and a worker drains the queue through the
// configured transport (Postmark for credentials/transactional, Resend
// for rapidsign signer notifications). The response confirms enqueue,
// not delivery.
//
// Per-account isolation: every row carries the calling account; cross-
// account queue inspection is not exposed.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/zyins/v1/email.proto

package zyinsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/isa-sdk/sdk/zyins/api/zyins/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EmailServiceName is the fully-qualified name of the EmailService service.
	EmailServiceName = "api.zyins.v1.EmailService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EmailServiceEnqueueEmailProcedure is the fully-qualified name of the EmailService's EnqueueEmail
	// RPC.
	EmailServiceEnqueueEmailProcedure = "/api.zyins.v1.EmailService/EnqueueEmail"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	emailServiceServiceDescriptor            = v1.File_api_zyins_v1_email_proto.Services().ByName("EmailService")
	emailServiceEnqueueEmailMethodDescriptor = emailServiceServiceDescriptor.Methods().ByName("EnqueueEmail")
)

// EmailServiceClient is a client for the api.zyins.v1.EmailService service.
type EmailServiceClient interface {
	// EnqueueEmail validates an outbound email and persists it to the
	// queue table. Returns 202 with the queued envelope on success.
	EnqueueEmail(context.Context, *connect.Request[v1.EnqueueEmailRequest]) (*connect.Response[v1.EnqueueEmailResponse], error)
}

// NewEmailServiceClient constructs a client for the api.zyins.v1.EmailService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEmailServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EmailServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &emailServiceClient{
		enqueueEmail: connect.NewClient[v1.EnqueueEmailRequest, v1.EnqueueEmailResponse](
			httpClient,
			baseURL+EmailServiceEnqueueEmailProcedure,
			connect.WithSchema(emailServiceEnqueueEmailMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// emailServiceClient implements EmailServiceClient.
type emailServiceClient struct {
	enqueueEmail *connect.Client[v1.EnqueueEmailRequest, v1.EnqueueEmailResponse]
}

// EnqueueEmail calls api.zyins.v1.EmailService.EnqueueEmail.
func (c *emailServiceClient) EnqueueEmail(ctx context.Context, req *connect.Request[v1.EnqueueEmailRequest]) (*connect.Response[v1.EnqueueEmailResponse], error) {
	return c.enqueueEmail.CallUnary(ctx, req)
}

// EmailServiceHandler is an implementation of the api.zyins.v1.EmailService service.
type EmailServiceHandler interface {
	// EnqueueEmail validates an outbound email and persists it to the
	// queue table. Returns 202 with the queued envelope on success.
	EnqueueEmail(context.Context, *connect.Request[v1.EnqueueEmailRequest]) (*connect.Response[v1.EnqueueEmailResponse], error)
}

// NewEmailServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEmailServiceHandler(svc EmailServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	emailServiceEnqueueEmailHandler := connect.NewUnaryHandler(
		EmailServiceEnqueueEmailProcedure,
		svc.EnqueueEmail,
		connect.WithSchema(emailServiceEnqueueEmailMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.zyins.v1.EmailService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EmailServiceEnqueueEmailProcedure:
			emailServiceEnqueueEmailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEmailServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEmailServiceHandler struct{}

func (UnimplementedEmailServiceHandler) EnqueueEmail(context.Context, *connect.Request[v1.EnqueueEmailRequest]) (*connect.Response[v1.EnqueueEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.EmailService.EnqueueEmail is not implemented"))
}
