// licenses.proto defines the BPP license-lifecycle surface for ZyINS
// (signup, activation, validation, lock/unlock, refresh, deactivate).
//
// Two surfaces coexist and this file covers both:
//
//   1. Legacy `/v1/licenses/*` endpoints — server-to-server, deprecated.
//      They take credentials in the request body, accept Bearer or
//      ServiceToken auth, and are being sunset per ADR-023.
//
//   2. Singular `/v1/license/*` endpoints (ADR-013) — authenticated-self.
//      The caller is identified by the auth context (LicenseAuth header
//      + X-Device-ID + X-Device-Signature); the body carries no
//      credentials. Phase 2 of the BPP migration moves clients here
//      and adds LicenseHMAC (ADR-018) as the preferred credential.
//
// The LicenseHMAC security scheme is new to the ZyINS API with this PR.
// Endpoint handlers in the server already accept it (PR #253); this PR
// exposes it to consumers via the generated OpenAPI.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/zyins/v1/licenses.proto

package zyinsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/isa-sdk/sdk/zyins/api/zyins/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LicensesServiceName is the fully-qualified name of the LicensesService service.
	LicensesServiceName = "api.zyins.v1.LicensesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LicensesServiceCreateOrderProcedure is the fully-qualified name of the LicensesService's
	// CreateOrder RPC.
	LicensesServiceCreateOrderProcedure = "/api.zyins.v1.LicensesService/CreateOrder"
	// LicensesServiceValidateProcedure is the fully-qualified name of the LicensesService's Validate
	// RPC.
	LicensesServiceValidateProcedure = "/api.zyins.v1.LicensesService/Validate"
	// LicensesServiceLockProcedure is the fully-qualified name of the LicensesService's Lock RPC.
	LicensesServiceLockProcedure = "/api.zyins.v1.LicensesService/Lock"
	// LicensesServiceUnlockProcedure is the fully-qualified name of the LicensesService's Unlock RPC.
	LicensesServiceUnlockProcedure = "/api.zyins.v1.LicensesService/Unlock"
	// LicensesServiceGetKeyProcedure is the fully-qualified name of the LicensesService's GetKey RPC.
	LicensesServiceGetKeyProcedure = "/api.zyins.v1.LicensesService/GetKey"
	// LicensesServiceRefreshDevicesProcedure is the fully-qualified name of the LicensesService's
	// RefreshDevices RPC.
	LicensesServiceRefreshDevicesProcedure = "/api.zyins.v1.LicensesService/RefreshDevices"
	// LicensesServiceUpdateQuantityProcedure is the fully-qualified name of the LicensesService's
	// UpdateQuantity RPC.
	LicensesServiceUpdateQuantityProcedure = "/api.zyins.v1.LicensesService/UpdateQuantity"
	// LicensesServiceGetLegacyStatusProcedure is the fully-qualified name of the LicensesService's
	// GetLegacyStatus RPC.
	LicensesServiceGetLegacyStatusProcedure = "/api.zyins.v1.LicensesService/GetLegacyStatus"
	// LicensesServicePublicActivateProcedure is the fully-qualified name of the LicensesService's
	// PublicActivate RPC.
	LicensesServicePublicActivateProcedure = "/api.zyins.v1.LicensesService/PublicActivate"
	// LicensesServicePublicDeactivateProcedure is the fully-qualified name of the LicensesService's
	// PublicDeactivate RPC.
	LicensesServicePublicDeactivateProcedure = "/api.zyins.v1.LicensesService/PublicDeactivate"
	// LicensesServicePublicCheckProcedure is the fully-qualified name of the LicensesService's
	// PublicCheck RPC.
	LicensesServicePublicCheckProcedure = "/api.zyins.v1.LicensesService/PublicCheck"
	// LicensesServiceGetSelfStatusProcedure is the fully-qualified name of the LicensesService's
	// GetSelfStatus RPC.
	LicensesServiceGetSelfStatusProcedure = "/api.zyins.v1.LicensesService/GetSelfStatus"
	// LicensesServiceLockSelfProcedure is the fully-qualified name of the LicensesService's LockSelf
	// RPC.
	LicensesServiceLockSelfProcedure = "/api.zyins.v1.LicensesService/LockSelf"
	// LicensesServiceUnlockSelfProcedure is the fully-qualified name of the LicensesService's
	// UnlockSelf RPC.
	LicensesServiceUnlockSelfProcedure = "/api.zyins.v1.LicensesService/UnlockSelf"
	// LicensesServiceRefreshSelfProcedure is the fully-qualified name of the LicensesService's
	// RefreshSelf RPC.
	LicensesServiceRefreshSelfProcedure = "/api.zyins.v1.LicensesService/RefreshSelf"
	// LicensesServiceDeactivateSelfProcedure is the fully-qualified name of the LicensesService's
	// DeactivateSelf RPC.
	LicensesServiceDeactivateSelfProcedure = "/api.zyins.v1.LicensesService/DeactivateSelf"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	licensesServiceServiceDescriptor                = v1.File_api_zyins_v1_licenses_proto.Services().ByName("LicensesService")
	licensesServiceCreateOrderMethodDescriptor      = licensesServiceServiceDescriptor.Methods().ByName("CreateOrder")
	licensesServiceValidateMethodDescriptor         = licensesServiceServiceDescriptor.Methods().ByName("Validate")
	licensesServiceLockMethodDescriptor             = licensesServiceServiceDescriptor.Methods().ByName("Lock")
	licensesServiceUnlockMethodDescriptor           = licensesServiceServiceDescriptor.Methods().ByName("Unlock")
	licensesServiceGetKeyMethodDescriptor           = licensesServiceServiceDescriptor.Methods().ByName("GetKey")
	licensesServiceRefreshDevicesMethodDescriptor   = licensesServiceServiceDescriptor.Methods().ByName("RefreshDevices")
	licensesServiceUpdateQuantityMethodDescriptor   = licensesServiceServiceDescriptor.Methods().ByName("UpdateQuantity")
	licensesServiceGetLegacyStatusMethodDescriptor  = licensesServiceServiceDescriptor.Methods().ByName("GetLegacyStatus")
	licensesServicePublicActivateMethodDescriptor   = licensesServiceServiceDescriptor.Methods().ByName("PublicActivate")
	licensesServicePublicDeactivateMethodDescriptor = licensesServiceServiceDescriptor.Methods().ByName("PublicDeactivate")
	licensesServicePublicCheckMethodDescriptor      = licensesServiceServiceDescriptor.Methods().ByName("PublicCheck")
	licensesServiceGetSelfStatusMethodDescriptor    = licensesServiceServiceDescriptor.Methods().ByName("GetSelfStatus")
	licensesServiceLockSelfMethodDescriptor         = licensesServiceServiceDescriptor.Methods().ByName("LockSelf")
	licensesServiceUnlockSelfMethodDescriptor       = licensesServiceServiceDescriptor.Methods().ByName("UnlockSelf")
	licensesServiceRefreshSelfMethodDescriptor      = licensesServiceServiceDescriptor.Methods().ByName("RefreshSelf")
	licensesServiceDeactivateSelfMethodDescriptor   = licensesServiceServiceDescriptor.Methods().ByName("DeactivateSelf")
)

// LicensesServiceClient is a client for the api.zyins.v1.LicensesService service.
type LicensesServiceClient interface {
	// CreateOrder creates a license order and returns its BPP keycode.
	// Legacy server-to-server endpoint; new clients use PublicActivate.
	CreateOrder(context.Context, *connect.Request[v1.CreateLicenseOrderRequest]) (*connect.Response[v1.CreateLicenseOrderResponse], error)
	// Validate verifies a license given credentials in the body. Used by
	// server-to-server integrations; BPP clients use CheckPublic instead.
	Validate(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.ValidateLicenseResponse], error)
	// Lock locks a license order by credentials. Admin surface; not used
	// by end-user clients.
	Lock(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseLockResponse], error)
	// Unlock unlocks a license order by credentials. Admin surface.
	Unlock(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseUnlockResponse], error)
	// GetKey returns the deterministic license key and keycode for an
	// order given credentials. Legacy; prefer PublicActivate for new
	// clients, which returns the key as part of activation.
	GetKey(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseKeyResponse], error)
	// RefreshDevices clears every anti-piracy device record for an order,
	// allowing re-activation on new devices. Admin surface.
	RefreshDevices(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseRefreshResponse], error)
	// UpdateQuantity updates max_activations for an order.
	UpdateQuantity(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseQuantityResponse], error)
	// GetLegacyStatus returns order status, max activations, and active
	// activation count. Deprecated; new clients use GetSelfStatus.
	GetLegacyStatus(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LegacyLicenseStatusResponse], error)
	// PublicActivate activates a license for a new device. No auth header;
	// the email + keycode in the body ARE the credentials, and the response
	// contains the generated license key plus a pre-built Authorization
	// header for subsequent requests.
	PublicActivate(context.Context, *connect.Request[v1.PublicActivateRequest]) (*connect.Response[v1.PublicActivateResponse], error)
	// PublicDeactivate deactivates a license. Resets anti-piracy device
	// state, marks the activation inactive, and sets order status inactive.
	PublicDeactivate(context.Context, *connect.Request[v1.PublicDeactivateRequest]) (*connect.Response[v1.PublicDeactivateResponse], error)
	// PublicCheck performs a lightweight phone-home validation and returns
	// the license status without requiring authentication.
	PublicCheck(context.Context, *connect.Request[v1.PublicCheckRequest]) (*connect.Response[v1.PublicCheckResponse], error)
	// GetSelfStatus returns the status of the license identified by the
	// auth context (LicenseAuth + X-Device-ID + X-Device-Signature under
	// the legacy scheme, or LicenseHMAC + X-Keycode + X-Email +
	// X-Timestamp + X-Device-ID under the new scheme). The singular
	// "/v1/license" endpoint per ADR-013.
	GetSelfStatus(context.Context, *connect.Request[v1.GetSelfStatusRequest]) (*connect.Response[v1.LicenseActivationResponse], error)
	// LockSelf locks the authenticated license.
	LockSelf(context.Context, *connect.Request[v1.LockSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error)
	// UnlockSelf unlocks the authenticated license.
	UnlockSelf(context.Context, *connect.Request[v1.UnlockSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error)
	// RefreshSelf extends the validity period of the authenticated license.
	RefreshSelf(context.Context, *connect.Request[v1.RefreshSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error)
	// DeactivateSelf deactivates the authenticated license. The license
	// key becomes invalid after deactivation.
	DeactivateSelf(context.Context, *connect.Request[v1.DeactivateSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error)
}

// NewLicensesServiceClient constructs a client for the api.zyins.v1.LicensesService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLicensesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LicensesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &licensesServiceClient{
		createOrder: connect.NewClient[v1.CreateLicenseOrderRequest, v1.CreateLicenseOrderResponse](
			httpClient,
			baseURL+LicensesServiceCreateOrderProcedure,
			connect.WithSchema(licensesServiceCreateOrderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		validate: connect.NewClient[v1.LicenseCredentialsRequest, v1.ValidateLicenseResponse](
			httpClient,
			baseURL+LicensesServiceValidateProcedure,
			connect.WithSchema(licensesServiceValidateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		lock: connect.NewClient[v1.LicenseCredentialsRequest, v1.LicenseLockResponse](
			httpClient,
			baseURL+LicensesServiceLockProcedure,
			connect.WithSchema(licensesServiceLockMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		unlock: connect.NewClient[v1.LicenseCredentialsRequest, v1.LicenseUnlockResponse](
			httpClient,
			baseURL+LicensesServiceUnlockProcedure,
			connect.WithSchema(licensesServiceUnlockMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getKey: connect.NewClient[v1.LicenseCredentialsRequest, v1.LicenseKeyResponse](
			httpClient,
			baseURL+LicensesServiceGetKeyProcedure,
			connect.WithSchema(licensesServiceGetKeyMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		refreshDevices: connect.NewClient[v1.LicenseCredentialsRequest, v1.LicenseRefreshResponse](
			httpClient,
			baseURL+LicensesServiceRefreshDevicesProcedure,
			connect.WithSchema(licensesServiceRefreshDevicesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateQuantity: connect.NewClient[v1.LicenseCredentialsRequest, v1.LicenseQuantityResponse](
			httpClient,
			baseURL+LicensesServiceUpdateQuantityProcedure,
			connect.WithSchema(licensesServiceUpdateQuantityMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getLegacyStatus: connect.NewClient[v1.LicenseCredentialsRequest, v1.LegacyLicenseStatusResponse](
			httpClient,
			baseURL+LicensesServiceGetLegacyStatusProcedure,
			connect.WithSchema(licensesServiceGetLegacyStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		publicActivate: connect.NewClient[v1.PublicActivateRequest, v1.PublicActivateResponse](
			httpClient,
			baseURL+LicensesServicePublicActivateProcedure,
			connect.WithSchema(licensesServicePublicActivateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		publicDeactivate: connect.NewClient[v1.PublicDeactivateRequest, v1.PublicDeactivateResponse](
			httpClient,
			baseURL+LicensesServicePublicDeactivateProcedure,
			connect.WithSchema(licensesServicePublicDeactivateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		publicCheck: connect.NewClient[v1.PublicCheckRequest, v1.PublicCheckResponse](
			httpClient,
			baseURL+LicensesServicePublicCheckProcedure,
			connect.WithSchema(licensesServicePublicCheckMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getSelfStatus: connect.NewClient[v1.GetSelfStatusRequest, v1.LicenseActivationResponse](
			httpClient,
			baseURL+LicensesServiceGetSelfStatusProcedure,
			connect.WithSchema(licensesServiceGetSelfStatusMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		lockSelf: connect.NewClient[v1.LockSelfRequest, v1.LicenseSelfStatusResponse](
			httpClient,
			baseURL+LicensesServiceLockSelfProcedure,
			connect.WithSchema(licensesServiceLockSelfMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		unlockSelf: connect.NewClient[v1.UnlockSelfRequest, v1.LicenseSelfStatusResponse](
			httpClient,
			baseURL+LicensesServiceUnlockSelfProcedure,
			connect.WithSchema(licensesServiceUnlockSelfMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		refreshSelf: connect.NewClient[v1.RefreshSelfRequest, v1.LicenseSelfStatusResponse](
			httpClient,
			baseURL+LicensesServiceRefreshSelfProcedure,
			connect.WithSchema(licensesServiceRefreshSelfMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deactivateSelf: connect.NewClient[v1.DeactivateSelfRequest, v1.LicenseSelfStatusResponse](
			httpClient,
			baseURL+LicensesServiceDeactivateSelfProcedure,
			connect.WithSchema(licensesServiceDeactivateSelfMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// licensesServiceClient implements LicensesServiceClient.
type licensesServiceClient struct {
	createOrder      *connect.Client[v1.CreateLicenseOrderRequest, v1.CreateLicenseOrderResponse]
	validate         *connect.Client[v1.LicenseCredentialsRequest, v1.ValidateLicenseResponse]
	lock             *connect.Client[v1.LicenseCredentialsRequest, v1.LicenseLockResponse]
	unlock           *connect.Client[v1.LicenseCredentialsRequest, v1.LicenseUnlockResponse]
	getKey           *connect.Client[v1.LicenseCredentialsRequest, v1.LicenseKeyResponse]
	refreshDevices   *connect.Client[v1.LicenseCredentialsRequest, v1.LicenseRefreshResponse]
	updateQuantity   *connect.Client[v1.LicenseCredentialsRequest, v1.LicenseQuantityResponse]
	getLegacyStatus  *connect.Client[v1.LicenseCredentialsRequest, v1.LegacyLicenseStatusResponse]
	publicActivate   *connect.Client[v1.PublicActivateRequest, v1.PublicActivateResponse]
	publicDeactivate *connect.Client[v1.PublicDeactivateRequest, v1.PublicDeactivateResponse]
	publicCheck      *connect.Client[v1.PublicCheckRequest, v1.PublicCheckResponse]
	getSelfStatus    *connect.Client[v1.GetSelfStatusRequest, v1.LicenseActivationResponse]
	lockSelf         *connect.Client[v1.LockSelfRequest, v1.LicenseSelfStatusResponse]
	unlockSelf       *connect.Client[v1.UnlockSelfRequest, v1.LicenseSelfStatusResponse]
	refreshSelf      *connect.Client[v1.RefreshSelfRequest, v1.LicenseSelfStatusResponse]
	deactivateSelf   *connect.Client[v1.DeactivateSelfRequest, v1.LicenseSelfStatusResponse]
}

// CreateOrder calls api.zyins.v1.LicensesService.CreateOrder.
func (c *licensesServiceClient) CreateOrder(ctx context.Context, req *connect.Request[v1.CreateLicenseOrderRequest]) (*connect.Response[v1.CreateLicenseOrderResponse], error) {
	return c.createOrder.CallUnary(ctx, req)
}

// Validate calls api.zyins.v1.LicensesService.Validate.
func (c *licensesServiceClient) Validate(ctx context.Context, req *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.ValidateLicenseResponse], error) {
	return c.validate.CallUnary(ctx, req)
}

// Lock calls api.zyins.v1.LicensesService.Lock.
func (c *licensesServiceClient) Lock(ctx context.Context, req *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseLockResponse], error) {
	return c.lock.CallUnary(ctx, req)
}

// Unlock calls api.zyins.v1.LicensesService.Unlock.
func (c *licensesServiceClient) Unlock(ctx context.Context, req *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseUnlockResponse], error) {
	return c.unlock.CallUnary(ctx, req)
}

// GetKey calls api.zyins.v1.LicensesService.GetKey.
func (c *licensesServiceClient) GetKey(ctx context.Context, req *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseKeyResponse], error) {
	return c.getKey.CallUnary(ctx, req)
}

// RefreshDevices calls api.zyins.v1.LicensesService.RefreshDevices.
func (c *licensesServiceClient) RefreshDevices(ctx context.Context, req *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseRefreshResponse], error) {
	return c.refreshDevices.CallUnary(ctx, req)
}

// UpdateQuantity calls api.zyins.v1.LicensesService.UpdateQuantity.
func (c *licensesServiceClient) UpdateQuantity(ctx context.Context, req *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseQuantityResponse], error) {
	return c.updateQuantity.CallUnary(ctx, req)
}

// GetLegacyStatus calls api.zyins.v1.LicensesService.GetLegacyStatus.
func (c *licensesServiceClient) GetLegacyStatus(ctx context.Context, req *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LegacyLicenseStatusResponse], error) {
	return c.getLegacyStatus.CallUnary(ctx, req)
}

// PublicActivate calls api.zyins.v1.LicensesService.PublicActivate.
func (c *licensesServiceClient) PublicActivate(ctx context.Context, req *connect.Request[v1.PublicActivateRequest]) (*connect.Response[v1.PublicActivateResponse], error) {
	return c.publicActivate.CallUnary(ctx, req)
}

// PublicDeactivate calls api.zyins.v1.LicensesService.PublicDeactivate.
func (c *licensesServiceClient) PublicDeactivate(ctx context.Context, req *connect.Request[v1.PublicDeactivateRequest]) (*connect.Response[v1.PublicDeactivateResponse], error) {
	return c.publicDeactivate.CallUnary(ctx, req)
}

// PublicCheck calls api.zyins.v1.LicensesService.PublicCheck.
func (c *licensesServiceClient) PublicCheck(ctx context.Context, req *connect.Request[v1.PublicCheckRequest]) (*connect.Response[v1.PublicCheckResponse], error) {
	return c.publicCheck.CallUnary(ctx, req)
}

// GetSelfStatus calls api.zyins.v1.LicensesService.GetSelfStatus.
func (c *licensesServiceClient) GetSelfStatus(ctx context.Context, req *connect.Request[v1.GetSelfStatusRequest]) (*connect.Response[v1.LicenseActivationResponse], error) {
	return c.getSelfStatus.CallUnary(ctx, req)
}

// LockSelf calls api.zyins.v1.LicensesService.LockSelf.
func (c *licensesServiceClient) LockSelf(ctx context.Context, req *connect.Request[v1.LockSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error) {
	return c.lockSelf.CallUnary(ctx, req)
}

// UnlockSelf calls api.zyins.v1.LicensesService.UnlockSelf.
func (c *licensesServiceClient) UnlockSelf(ctx context.Context, req *connect.Request[v1.UnlockSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error) {
	return c.unlockSelf.CallUnary(ctx, req)
}

// RefreshSelf calls api.zyins.v1.LicensesService.RefreshSelf.
func (c *licensesServiceClient) RefreshSelf(ctx context.Context, req *connect.Request[v1.RefreshSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error) {
	return c.refreshSelf.CallUnary(ctx, req)
}

// DeactivateSelf calls api.zyins.v1.LicensesService.DeactivateSelf.
func (c *licensesServiceClient) DeactivateSelf(ctx context.Context, req *connect.Request[v1.DeactivateSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error) {
	return c.deactivateSelf.CallUnary(ctx, req)
}

// LicensesServiceHandler is an implementation of the api.zyins.v1.LicensesService service.
type LicensesServiceHandler interface {
	// CreateOrder creates a license order and returns its BPP keycode.
	// Legacy server-to-server endpoint; new clients use PublicActivate.
	CreateOrder(context.Context, *connect.Request[v1.CreateLicenseOrderRequest]) (*connect.Response[v1.CreateLicenseOrderResponse], error)
	// Validate verifies a license given credentials in the body. Used by
	// server-to-server integrations; BPP clients use CheckPublic instead.
	Validate(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.ValidateLicenseResponse], error)
	// Lock locks a license order by credentials. Admin surface; not used
	// by end-user clients.
	Lock(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseLockResponse], error)
	// Unlock unlocks a license order by credentials. Admin surface.
	Unlock(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseUnlockResponse], error)
	// GetKey returns the deterministic license key and keycode for an
	// order given credentials. Legacy; prefer PublicActivate for new
	// clients, which returns the key as part of activation.
	GetKey(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseKeyResponse], error)
	// RefreshDevices clears every anti-piracy device record for an order,
	// allowing re-activation on new devices. Admin surface.
	RefreshDevices(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseRefreshResponse], error)
	// UpdateQuantity updates max_activations for an order.
	UpdateQuantity(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseQuantityResponse], error)
	// GetLegacyStatus returns order status, max activations, and active
	// activation count. Deprecated; new clients use GetSelfStatus.
	GetLegacyStatus(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LegacyLicenseStatusResponse], error)
	// PublicActivate activates a license for a new device. No auth header;
	// the email + keycode in the body ARE the credentials, and the response
	// contains the generated license key plus a pre-built Authorization
	// header for subsequent requests.
	PublicActivate(context.Context, *connect.Request[v1.PublicActivateRequest]) (*connect.Response[v1.PublicActivateResponse], error)
	// PublicDeactivate deactivates a license. Resets anti-piracy device
	// state, marks the activation inactive, and sets order status inactive.
	PublicDeactivate(context.Context, *connect.Request[v1.PublicDeactivateRequest]) (*connect.Response[v1.PublicDeactivateResponse], error)
	// PublicCheck performs a lightweight phone-home validation and returns
	// the license status without requiring authentication.
	PublicCheck(context.Context, *connect.Request[v1.PublicCheckRequest]) (*connect.Response[v1.PublicCheckResponse], error)
	// GetSelfStatus returns the status of the license identified by the
	// auth context (LicenseAuth + X-Device-ID + X-Device-Signature under
	// the legacy scheme, or LicenseHMAC + X-Keycode + X-Email +
	// X-Timestamp + X-Device-ID under the new scheme). The singular
	// "/v1/license" endpoint per ADR-013.
	GetSelfStatus(context.Context, *connect.Request[v1.GetSelfStatusRequest]) (*connect.Response[v1.LicenseActivationResponse], error)
	// LockSelf locks the authenticated license.
	LockSelf(context.Context, *connect.Request[v1.LockSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error)
	// UnlockSelf unlocks the authenticated license.
	UnlockSelf(context.Context, *connect.Request[v1.UnlockSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error)
	// RefreshSelf extends the validity period of the authenticated license.
	RefreshSelf(context.Context, *connect.Request[v1.RefreshSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error)
	// DeactivateSelf deactivates the authenticated license. The license
	// key becomes invalid after deactivation.
	DeactivateSelf(context.Context, *connect.Request[v1.DeactivateSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error)
}

// NewLicensesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLicensesServiceHandler(svc LicensesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	licensesServiceCreateOrderHandler := connect.NewUnaryHandler(
		LicensesServiceCreateOrderProcedure,
		svc.CreateOrder,
		connect.WithSchema(licensesServiceCreateOrderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceValidateHandler := connect.NewUnaryHandler(
		LicensesServiceValidateProcedure,
		svc.Validate,
		connect.WithSchema(licensesServiceValidateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceLockHandler := connect.NewUnaryHandler(
		LicensesServiceLockProcedure,
		svc.Lock,
		connect.WithSchema(licensesServiceLockMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceUnlockHandler := connect.NewUnaryHandler(
		LicensesServiceUnlockProcedure,
		svc.Unlock,
		connect.WithSchema(licensesServiceUnlockMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceGetKeyHandler := connect.NewUnaryHandler(
		LicensesServiceGetKeyProcedure,
		svc.GetKey,
		connect.WithSchema(licensesServiceGetKeyMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceRefreshDevicesHandler := connect.NewUnaryHandler(
		LicensesServiceRefreshDevicesProcedure,
		svc.RefreshDevices,
		connect.WithSchema(licensesServiceRefreshDevicesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceUpdateQuantityHandler := connect.NewUnaryHandler(
		LicensesServiceUpdateQuantityProcedure,
		svc.UpdateQuantity,
		connect.WithSchema(licensesServiceUpdateQuantityMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceGetLegacyStatusHandler := connect.NewUnaryHandler(
		LicensesServiceGetLegacyStatusProcedure,
		svc.GetLegacyStatus,
		connect.WithSchema(licensesServiceGetLegacyStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServicePublicActivateHandler := connect.NewUnaryHandler(
		LicensesServicePublicActivateProcedure,
		svc.PublicActivate,
		connect.WithSchema(licensesServicePublicActivateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServicePublicDeactivateHandler := connect.NewUnaryHandler(
		LicensesServicePublicDeactivateProcedure,
		svc.PublicDeactivate,
		connect.WithSchema(licensesServicePublicDeactivateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServicePublicCheckHandler := connect.NewUnaryHandler(
		LicensesServicePublicCheckProcedure,
		svc.PublicCheck,
		connect.WithSchema(licensesServicePublicCheckMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceGetSelfStatusHandler := connect.NewUnaryHandler(
		LicensesServiceGetSelfStatusProcedure,
		svc.GetSelfStatus,
		connect.WithSchema(licensesServiceGetSelfStatusMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceLockSelfHandler := connect.NewUnaryHandler(
		LicensesServiceLockSelfProcedure,
		svc.LockSelf,
		connect.WithSchema(licensesServiceLockSelfMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceUnlockSelfHandler := connect.NewUnaryHandler(
		LicensesServiceUnlockSelfProcedure,
		svc.UnlockSelf,
		connect.WithSchema(licensesServiceUnlockSelfMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceRefreshSelfHandler := connect.NewUnaryHandler(
		LicensesServiceRefreshSelfProcedure,
		svc.RefreshSelf,
		connect.WithSchema(licensesServiceRefreshSelfMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	licensesServiceDeactivateSelfHandler := connect.NewUnaryHandler(
		LicensesServiceDeactivateSelfProcedure,
		svc.DeactivateSelf,
		connect.WithSchema(licensesServiceDeactivateSelfMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.zyins.v1.LicensesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LicensesServiceCreateOrderProcedure:
			licensesServiceCreateOrderHandler.ServeHTTP(w, r)
		case LicensesServiceValidateProcedure:
			licensesServiceValidateHandler.ServeHTTP(w, r)
		case LicensesServiceLockProcedure:
			licensesServiceLockHandler.ServeHTTP(w, r)
		case LicensesServiceUnlockProcedure:
			licensesServiceUnlockHandler.ServeHTTP(w, r)
		case LicensesServiceGetKeyProcedure:
			licensesServiceGetKeyHandler.ServeHTTP(w, r)
		case LicensesServiceRefreshDevicesProcedure:
			licensesServiceRefreshDevicesHandler.ServeHTTP(w, r)
		case LicensesServiceUpdateQuantityProcedure:
			licensesServiceUpdateQuantityHandler.ServeHTTP(w, r)
		case LicensesServiceGetLegacyStatusProcedure:
			licensesServiceGetLegacyStatusHandler.ServeHTTP(w, r)
		case LicensesServicePublicActivateProcedure:
			licensesServicePublicActivateHandler.ServeHTTP(w, r)
		case LicensesServicePublicDeactivateProcedure:
			licensesServicePublicDeactivateHandler.ServeHTTP(w, r)
		case LicensesServicePublicCheckProcedure:
			licensesServicePublicCheckHandler.ServeHTTP(w, r)
		case LicensesServiceGetSelfStatusProcedure:
			licensesServiceGetSelfStatusHandler.ServeHTTP(w, r)
		case LicensesServiceLockSelfProcedure:
			licensesServiceLockSelfHandler.ServeHTTP(w, r)
		case LicensesServiceUnlockSelfProcedure:
			licensesServiceUnlockSelfHandler.ServeHTTP(w, r)
		case LicensesServiceRefreshSelfProcedure:
			licensesServiceRefreshSelfHandler.ServeHTTP(w, r)
		case LicensesServiceDeactivateSelfProcedure:
			licensesServiceDeactivateSelfHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLicensesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLicensesServiceHandler struct{}

func (UnimplementedLicensesServiceHandler) CreateOrder(context.Context, *connect.Request[v1.CreateLicenseOrderRequest]) (*connect.Response[v1.CreateLicenseOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.CreateOrder is not implemented"))
}

func (UnimplementedLicensesServiceHandler) Validate(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.ValidateLicenseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.Validate is not implemented"))
}

func (UnimplementedLicensesServiceHandler) Lock(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseLockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.Lock is not implemented"))
}

func (UnimplementedLicensesServiceHandler) Unlock(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseUnlockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.Unlock is not implemented"))
}

func (UnimplementedLicensesServiceHandler) GetKey(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.GetKey is not implemented"))
}

func (UnimplementedLicensesServiceHandler) RefreshDevices(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseRefreshResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.RefreshDevices is not implemented"))
}

func (UnimplementedLicensesServiceHandler) UpdateQuantity(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LicenseQuantityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.UpdateQuantity is not implemented"))
}

func (UnimplementedLicensesServiceHandler) GetLegacyStatus(context.Context, *connect.Request[v1.LicenseCredentialsRequest]) (*connect.Response[v1.LegacyLicenseStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.GetLegacyStatus is not implemented"))
}

func (UnimplementedLicensesServiceHandler) PublicActivate(context.Context, *connect.Request[v1.PublicActivateRequest]) (*connect.Response[v1.PublicActivateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.PublicActivate is not implemented"))
}

func (UnimplementedLicensesServiceHandler) PublicDeactivate(context.Context, *connect.Request[v1.PublicDeactivateRequest]) (*connect.Response[v1.PublicDeactivateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.PublicDeactivate is not implemented"))
}

func (UnimplementedLicensesServiceHandler) PublicCheck(context.Context, *connect.Request[v1.PublicCheckRequest]) (*connect.Response[v1.PublicCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.PublicCheck is not implemented"))
}

func (UnimplementedLicensesServiceHandler) GetSelfStatus(context.Context, *connect.Request[v1.GetSelfStatusRequest]) (*connect.Response[v1.LicenseActivationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.GetSelfStatus is not implemented"))
}

func (UnimplementedLicensesServiceHandler) LockSelf(context.Context, *connect.Request[v1.LockSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.LockSelf is not implemented"))
}

func (UnimplementedLicensesServiceHandler) UnlockSelf(context.Context, *connect.Request[v1.UnlockSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.UnlockSelf is not implemented"))
}

func (UnimplementedLicensesServiceHandler) RefreshSelf(context.Context, *connect.Request[v1.RefreshSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.RefreshSelf is not implemented"))
}

func (UnimplementedLicensesServiceHandler) DeactivateSelf(context.Context, *connect.Request[v1.DeactivateSelfRequest]) (*connect.Response[v1.LicenseSelfStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.LicensesService.DeactivateSelf is not implemented"))
}
