// preferences.proto defines the account-scoped whitelabel-preferences
// persistence surface for the ZyINS Unified API. Mounted at
// `zyins.isaapi.com/v2/preferences/{backup,restore}`.
//
// CRITICAL ROUND-TRIP CONTRACT
//
// Backup and restore are byte-identical inverses. What the caller writes
// is exactly what they read back: the `prefs` payload bytes returned by
// RestorePreferences MUST equal the bytes the caller most recently sent
// to BackupPreferences for the same `(email, keycode)` identity tuple.
// Asymmetric shapes between the two operations are forbidden — adding a
// computed field on restore that isn't accepted on backup is a contract
// break.
//
// This is enforced by unit tests: any change to either handler that
// breaks round-trip identity fails CI.
//
// SCHEMA POSTURE
//
// The server controls the field set; the customer fills it in. New
// fields are added by extending `WhitelabelPreferences` here and
// regenerating. Unknown fields on the wire are rejected
// (`additional_properties: false` in OpenAPI). This is account-scoped
// persistence, not a generic blob store: every field has a typed home.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/zyins/v1/preferences.proto

package zyinsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/isa-sdk/sdk/zyins/api/zyins/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PreferencesServiceName is the fully-qualified name of the PreferencesService service.
	PreferencesServiceName = "api.zyins.v1.PreferencesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PreferencesServiceBackupPreferencesProcedure is the fully-qualified name of the
	// PreferencesService's BackupPreferences RPC.
	PreferencesServiceBackupPreferencesProcedure = "/api.zyins.v1.PreferencesService/BackupPreferences"
	// PreferencesServiceRestorePreferencesProcedure is the fully-qualified name of the
	// PreferencesService's RestorePreferences RPC.
	PreferencesServiceRestorePreferencesProcedure = "/api.zyins.v1.PreferencesService/RestorePreferences"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	preferencesServiceServiceDescriptor                  = v1.File_api_zyins_v1_preferences_proto.Services().ByName("PreferencesService")
	preferencesServiceBackupPreferencesMethodDescriptor  = preferencesServiceServiceDescriptor.Methods().ByName("BackupPreferences")
	preferencesServiceRestorePreferencesMethodDescriptor = preferencesServiceServiceDescriptor.Methods().ByName("RestorePreferences")
)

// PreferencesServiceClient is a client for the api.zyins.v1.PreferencesService service.
type PreferencesServiceClient interface {
	// BackupPreferences upserts the calling account's preferences. The
	// request body and the future restore response carry an identical
	// `prefs` payload — see the round-trip contract in this file's
	// header.
	BackupPreferences(context.Context, *connect.Request[v1.BackupPreferencesRequest]) (*connect.Response[v1.PreferencesEnvelope], error)
	// RestorePreferences returns the calling account's most recently
	// backed-up preferences. Returns an empty `prefs` (not 404) when the
	// account has never written preferences.
	RestorePreferences(context.Context, *connect.Request[v1.RestorePreferencesRequest]) (*connect.Response[v1.PreferencesEnvelope], error)
}

// NewPreferencesServiceClient constructs a client for the api.zyins.v1.PreferencesService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPreferencesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PreferencesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &preferencesServiceClient{
		backupPreferences: connect.NewClient[v1.BackupPreferencesRequest, v1.PreferencesEnvelope](
			httpClient,
			baseURL+PreferencesServiceBackupPreferencesProcedure,
			connect.WithSchema(preferencesServiceBackupPreferencesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		restorePreferences: connect.NewClient[v1.RestorePreferencesRequest, v1.PreferencesEnvelope](
			httpClient,
			baseURL+PreferencesServiceRestorePreferencesProcedure,
			connect.WithSchema(preferencesServiceRestorePreferencesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// preferencesServiceClient implements PreferencesServiceClient.
type preferencesServiceClient struct {
	backupPreferences  *connect.Client[v1.BackupPreferencesRequest, v1.PreferencesEnvelope]
	restorePreferences *connect.Client[v1.RestorePreferencesRequest, v1.PreferencesEnvelope]
}

// BackupPreferences calls api.zyins.v1.PreferencesService.BackupPreferences.
func (c *preferencesServiceClient) BackupPreferences(ctx context.Context, req *connect.Request[v1.BackupPreferencesRequest]) (*connect.Response[v1.PreferencesEnvelope], error) {
	return c.backupPreferences.CallUnary(ctx, req)
}

// RestorePreferences calls api.zyins.v1.PreferencesService.RestorePreferences.
func (c *preferencesServiceClient) RestorePreferences(ctx context.Context, req *connect.Request[v1.RestorePreferencesRequest]) (*connect.Response[v1.PreferencesEnvelope], error) {
	return c.restorePreferences.CallUnary(ctx, req)
}

// PreferencesServiceHandler is an implementation of the api.zyins.v1.PreferencesService service.
type PreferencesServiceHandler interface {
	// BackupPreferences upserts the calling account's preferences. The
	// request body and the future restore response carry an identical
	// `prefs` payload — see the round-trip contract in this file's
	// header.
	BackupPreferences(context.Context, *connect.Request[v1.BackupPreferencesRequest]) (*connect.Response[v1.PreferencesEnvelope], error)
	// RestorePreferences returns the calling account's most recently
	// backed-up preferences. Returns an empty `prefs` (not 404) when the
	// account has never written preferences.
	RestorePreferences(context.Context, *connect.Request[v1.RestorePreferencesRequest]) (*connect.Response[v1.PreferencesEnvelope], error)
}

// NewPreferencesServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPreferencesServiceHandler(svc PreferencesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	preferencesServiceBackupPreferencesHandler := connect.NewUnaryHandler(
		PreferencesServiceBackupPreferencesProcedure,
		svc.BackupPreferences,
		connect.WithSchema(preferencesServiceBackupPreferencesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	preferencesServiceRestorePreferencesHandler := connect.NewUnaryHandler(
		PreferencesServiceRestorePreferencesProcedure,
		svc.RestorePreferences,
		connect.WithSchema(preferencesServiceRestorePreferencesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.zyins.v1.PreferencesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PreferencesServiceBackupPreferencesProcedure:
			preferencesServiceBackupPreferencesHandler.ServeHTTP(w, r)
		case PreferencesServiceRestorePreferencesProcedure:
			preferencesServiceRestorePreferencesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPreferencesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPreferencesServiceHandler struct{}

func (UnimplementedPreferencesServiceHandler) BackupPreferences(context.Context, *connect.Request[v1.BackupPreferencesRequest]) (*connect.Response[v1.PreferencesEnvelope], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.PreferencesService.BackupPreferences is not implemented"))
}

func (UnimplementedPreferencesServiceHandler) RestorePreferences(context.Context, *connect.Request[v1.RestorePreferencesRequest]) (*connect.Response[v1.PreferencesEnvelope], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.PreferencesService.RestorePreferences is not implemented"))
}
