// tokens.proto defines the API-token management surface for the ZyINS
// Unified API. Every RPC here is authenticated with BearerAuth (ADR-013);
// tokens are the credential type used to call the public compute surface
// (prequalify, quote, datasets). All routes are mounted under
// `zyins.isaapi.com/v1/tokens`.
//
// Token values are returned in plaintext only on Create and Rotate;
// every other response returns a redacted `hint` (last four characters)
// plus metadata.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/zyins/v1/tokens.proto

package zyinsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/isa-sdk/sdk/zyins/api/zyins/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TokensServiceName is the fully-qualified name of the TokensService service.
	TokensServiceName = "api.zyins.v1.TokensService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TokensServiceListProcedure is the fully-qualified name of the TokensService's List RPC.
	TokensServiceListProcedure = "/api.zyins.v1.TokensService/List"
	// TokensServiceCreateProcedure is the fully-qualified name of the TokensService's Create RPC.
	TokensServiceCreateProcedure = "/api.zyins.v1.TokensService/Create"
	// TokensServiceGetProcedure is the fully-qualified name of the TokensService's Get RPC.
	TokensServiceGetProcedure = "/api.zyins.v1.TokensService/Get"
	// TokensServiceDeleteProcedure is the fully-qualified name of the TokensService's Delete RPC.
	TokensServiceDeleteProcedure = "/api.zyins.v1.TokensService/Delete"
	// TokensServiceRevokeProcedure is the fully-qualified name of the TokensService's Revoke RPC.
	TokensServiceRevokeProcedure = "/api.zyins.v1.TokensService/Revoke"
	// TokensServiceReinstateProcedure is the fully-qualified name of the TokensService's Reinstate RPC.
	TokensServiceReinstateProcedure = "/api.zyins.v1.TokensService/Reinstate"
	// TokensServiceBanProcedure is the fully-qualified name of the TokensService's Ban RPC.
	TokensServiceBanProcedure = "/api.zyins.v1.TokensService/Ban"
	// TokensServiceRotateProcedure is the fully-qualified name of the TokensService's Rotate RPC.
	TokensServiceRotateProcedure = "/api.zyins.v1.TokensService/Rotate"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	tokensServiceServiceDescriptor         = v1.File_api_zyins_v1_tokens_proto.Services().ByName("TokensService")
	tokensServiceListMethodDescriptor      = tokensServiceServiceDescriptor.Methods().ByName("List")
	tokensServiceCreateMethodDescriptor    = tokensServiceServiceDescriptor.Methods().ByName("Create")
	tokensServiceGetMethodDescriptor       = tokensServiceServiceDescriptor.Methods().ByName("Get")
	tokensServiceDeleteMethodDescriptor    = tokensServiceServiceDescriptor.Methods().ByName("Delete")
	tokensServiceRevokeMethodDescriptor    = tokensServiceServiceDescriptor.Methods().ByName("Revoke")
	tokensServiceReinstateMethodDescriptor = tokensServiceServiceDescriptor.Methods().ByName("Reinstate")
	tokensServiceBanMethodDescriptor       = tokensServiceServiceDescriptor.Methods().ByName("Ban")
	tokensServiceRotateMethodDescriptor    = tokensServiceServiceDescriptor.Methods().ByName("Rotate")
)

// TokensServiceClient is a client for the api.zyins.v1.TokensService service.
type TokensServiceClient interface {
	// List returns every token owned by the authenticated account with
	// redacted values. Used by the account console to render the token
	// table.
	List(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error)
	// Create issues a new API token with the requested scopes and expiry.
	// The response is the ONLY place the plaintext token is returned; the
	// caller must persist it immediately.
	Create(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error)
	// Get returns metadata and status for a specific token. The plaintext
	// token value is never returned here; only the four-character `hint`.
	Get(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.TokenDetail], error)
	// Delete immediately revokes a token without recording a reason.
	// Deprecated; new clients use Revoke which accepts a reason for audit.
	// Returns 204 No Content on success.
	Delete(context.Context, *connect.Request[v1.DeleteTokenRequest]) (*connect.Response[v1.DeleteTokenResponse], error)
	// Revoke terminates a token and records the reason for audit. Revoked
	// tokens may be reinstated with Reinstate; banned tokens cannot.
	Revoke(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.TokenDetail], error)
	// Reinstate re-enables a revoked token. Fails with CONFLICT if the
	// token is banned or expired.
	Reinstate(context.Context, *connect.Request[v1.ReinstateTokenRequest]) (*connect.Response[v1.TokenDetail], error)
	// Ban permanently marks a token as banned. Banned tokens cannot be
	// reinstated. Internal surface; not exposed on ReadMe.
	Ban(context.Context, *connect.Request[v1.BanTokenRequest]) (*connect.Response[v1.TokenDetail], error)
	// Rotate creates a new token with the same scopes and configuration
	// as the identified token, then schedules the old one for revocation
	// after `grace_period_seconds` (default 30 days, max 90 days). The
	// new plaintext token value is returned in the response. Callers
	// migrate consumers within the grace window; the sweeper revokes the
	// old token when `revokes_at` elapses (task #118).
	//
	// Task #117: self-service rotation. The legacy
	// `POST /v1/tokens/rotate` (body-keyed) remains for back-compat;
	// new integrators use the resource-style `/v1/tokens/{id}/rotate`.
	Rotate(context.Context, *connect.Request[v1.RotateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error)
}

// NewTokensServiceClient constructs a client for the api.zyins.v1.TokensService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTokensServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TokensServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &tokensServiceClient{
		list: connect.NewClient[v1.ListTokensRequest, v1.ListTokensResponse](
			httpClient,
			baseURL+TokensServiceListProcedure,
			connect.WithSchema(tokensServiceListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1.CreateTokenRequest, v1.CreateTokenResponse](
			httpClient,
			baseURL+TokensServiceCreateProcedure,
			connect.WithSchema(tokensServiceCreateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.GetTokenRequest, v1.TokenDetail](
			httpClient,
			baseURL+TokensServiceGetProcedure,
			connect.WithSchema(tokensServiceGetMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.DeleteTokenRequest, v1.DeleteTokenResponse](
			httpClient,
			baseURL+TokensServiceDeleteProcedure,
			connect.WithSchema(tokensServiceDeleteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		revoke: connect.NewClient[v1.RevokeTokenRequest, v1.TokenDetail](
			httpClient,
			baseURL+TokensServiceRevokeProcedure,
			connect.WithSchema(tokensServiceRevokeMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		reinstate: connect.NewClient[v1.ReinstateTokenRequest, v1.TokenDetail](
			httpClient,
			baseURL+TokensServiceReinstateProcedure,
			connect.WithSchema(tokensServiceReinstateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		ban: connect.NewClient[v1.BanTokenRequest, v1.TokenDetail](
			httpClient,
			baseURL+TokensServiceBanProcedure,
			connect.WithSchema(tokensServiceBanMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		rotate: connect.NewClient[v1.RotateTokenRequest, v1.CreateTokenResponse](
			httpClient,
			baseURL+TokensServiceRotateProcedure,
			connect.WithSchema(tokensServiceRotateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// tokensServiceClient implements TokensServiceClient.
type tokensServiceClient struct {
	list      *connect.Client[v1.ListTokensRequest, v1.ListTokensResponse]
	create    *connect.Client[v1.CreateTokenRequest, v1.CreateTokenResponse]
	get       *connect.Client[v1.GetTokenRequest, v1.TokenDetail]
	delete    *connect.Client[v1.DeleteTokenRequest, v1.DeleteTokenResponse]
	revoke    *connect.Client[v1.RevokeTokenRequest, v1.TokenDetail]
	reinstate *connect.Client[v1.ReinstateTokenRequest, v1.TokenDetail]
	ban       *connect.Client[v1.BanTokenRequest, v1.TokenDetail]
	rotate    *connect.Client[v1.RotateTokenRequest, v1.CreateTokenResponse]
}

// List calls api.zyins.v1.TokensService.List.
func (c *tokensServiceClient) List(ctx context.Context, req *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Create calls api.zyins.v1.TokensService.Create.
func (c *tokensServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Get calls api.zyins.v1.TokensService.Get.
func (c *tokensServiceClient) Get(ctx context.Context, req *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.TokenDetail], error) {
	return c.get.CallUnary(ctx, req)
}

// Delete calls api.zyins.v1.TokensService.Delete.
func (c *tokensServiceClient) Delete(ctx context.Context, req *connect.Request[v1.DeleteTokenRequest]) (*connect.Response[v1.DeleteTokenResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Revoke calls api.zyins.v1.TokensService.Revoke.
func (c *tokensServiceClient) Revoke(ctx context.Context, req *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.TokenDetail], error) {
	return c.revoke.CallUnary(ctx, req)
}

// Reinstate calls api.zyins.v1.TokensService.Reinstate.
func (c *tokensServiceClient) Reinstate(ctx context.Context, req *connect.Request[v1.ReinstateTokenRequest]) (*connect.Response[v1.TokenDetail], error) {
	return c.reinstate.CallUnary(ctx, req)
}

// Ban calls api.zyins.v1.TokensService.Ban.
func (c *tokensServiceClient) Ban(ctx context.Context, req *connect.Request[v1.BanTokenRequest]) (*connect.Response[v1.TokenDetail], error) {
	return c.ban.CallUnary(ctx, req)
}

// Rotate calls api.zyins.v1.TokensService.Rotate.
func (c *tokensServiceClient) Rotate(ctx context.Context, req *connect.Request[v1.RotateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	return c.rotate.CallUnary(ctx, req)
}

// TokensServiceHandler is an implementation of the api.zyins.v1.TokensService service.
type TokensServiceHandler interface {
	// List returns every token owned by the authenticated account with
	// redacted values. Used by the account console to render the token
	// table.
	List(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error)
	// Create issues a new API token with the requested scopes and expiry.
	// The response is the ONLY place the plaintext token is returned; the
	// caller must persist it immediately.
	Create(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error)
	// Get returns metadata and status for a specific token. The plaintext
	// token value is never returned here; only the four-character `hint`.
	Get(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.TokenDetail], error)
	// Delete immediately revokes a token without recording a reason.
	// Deprecated; new clients use Revoke which accepts a reason for audit.
	// Returns 204 No Content on success.
	Delete(context.Context, *connect.Request[v1.DeleteTokenRequest]) (*connect.Response[v1.DeleteTokenResponse], error)
	// Revoke terminates a token and records the reason for audit. Revoked
	// tokens may be reinstated with Reinstate; banned tokens cannot.
	Revoke(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.TokenDetail], error)
	// Reinstate re-enables a revoked token. Fails with CONFLICT if the
	// token is banned or expired.
	Reinstate(context.Context, *connect.Request[v1.ReinstateTokenRequest]) (*connect.Response[v1.TokenDetail], error)
	// Ban permanently marks a token as banned. Banned tokens cannot be
	// reinstated. Internal surface; not exposed on ReadMe.
	Ban(context.Context, *connect.Request[v1.BanTokenRequest]) (*connect.Response[v1.TokenDetail], error)
	// Rotate creates a new token with the same scopes and configuration
	// as the identified token, then schedules the old one for revocation
	// after `grace_period_seconds` (default 30 days, max 90 days). The
	// new plaintext token value is returned in the response. Callers
	// migrate consumers within the grace window; the sweeper revokes the
	// old token when `revokes_at` elapses (task #118).
	//
	// Task #117: self-service rotation. The legacy
	// `POST /v1/tokens/rotate` (body-keyed) remains for back-compat;
	// new integrators use the resource-style `/v1/tokens/{id}/rotate`.
	Rotate(context.Context, *connect.Request[v1.RotateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error)
}

// NewTokensServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTokensServiceHandler(svc TokensServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tokensServiceListHandler := connect.NewUnaryHandler(
		TokensServiceListProcedure,
		svc.List,
		connect.WithSchema(tokensServiceListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	tokensServiceCreateHandler := connect.NewUnaryHandler(
		TokensServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(tokensServiceCreateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	tokensServiceGetHandler := connect.NewUnaryHandler(
		TokensServiceGetProcedure,
		svc.Get,
		connect.WithSchema(tokensServiceGetMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	tokensServiceDeleteHandler := connect.NewUnaryHandler(
		TokensServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(tokensServiceDeleteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	tokensServiceRevokeHandler := connect.NewUnaryHandler(
		TokensServiceRevokeProcedure,
		svc.Revoke,
		connect.WithSchema(tokensServiceRevokeMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	tokensServiceReinstateHandler := connect.NewUnaryHandler(
		TokensServiceReinstateProcedure,
		svc.Reinstate,
		connect.WithSchema(tokensServiceReinstateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	tokensServiceBanHandler := connect.NewUnaryHandler(
		TokensServiceBanProcedure,
		svc.Ban,
		connect.WithSchema(tokensServiceBanMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	tokensServiceRotateHandler := connect.NewUnaryHandler(
		TokensServiceRotateProcedure,
		svc.Rotate,
		connect.WithSchema(tokensServiceRotateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.zyins.v1.TokensService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TokensServiceListProcedure:
			tokensServiceListHandler.ServeHTTP(w, r)
		case TokensServiceCreateProcedure:
			tokensServiceCreateHandler.ServeHTTP(w, r)
		case TokensServiceGetProcedure:
			tokensServiceGetHandler.ServeHTTP(w, r)
		case TokensServiceDeleteProcedure:
			tokensServiceDeleteHandler.ServeHTTP(w, r)
		case TokensServiceRevokeProcedure:
			tokensServiceRevokeHandler.ServeHTTP(w, r)
		case TokensServiceReinstateProcedure:
			tokensServiceReinstateHandler.ServeHTTP(w, r)
		case TokensServiceBanProcedure:
			tokensServiceBanHandler.ServeHTTP(w, r)
		case TokensServiceRotateProcedure:
			tokensServiceRotateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTokensServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTokensServiceHandler struct{}

func (UnimplementedTokensServiceHandler) List(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.TokensService.List is not implemented"))
}

func (UnimplementedTokensServiceHandler) Create(context.Context, *connect.Request[v1.CreateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.TokensService.Create is not implemented"))
}

func (UnimplementedTokensServiceHandler) Get(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.TokenDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.TokensService.Get is not implemented"))
}

func (UnimplementedTokensServiceHandler) Delete(context.Context, *connect.Request[v1.DeleteTokenRequest]) (*connect.Response[v1.DeleteTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.TokensService.Delete is not implemented"))
}

func (UnimplementedTokensServiceHandler) Revoke(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.TokenDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.TokensService.Revoke is not implemented"))
}

func (UnimplementedTokensServiceHandler) Reinstate(context.Context, *connect.Request[v1.ReinstateTokenRequest]) (*connect.Response[v1.TokenDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.TokensService.Reinstate is not implemented"))
}

func (UnimplementedTokensServiceHandler) Ban(context.Context, *connect.Request[v1.BanTokenRequest]) (*connect.Response[v1.TokenDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.TokensService.Ban is not implemented"))
}

func (UnimplementedTokensServiceHandler) Rotate(context.Context, *connect.Request[v1.RotateTokenRequest]) (*connect.Response[v1.CreateTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.zyins.v1.TokensService.Rotate is not implemented"))
}
