// documents.proto defines the document-lifecycle surface for RapidSign
// served from `rapidsign.isaapi.com`. Per ADR-019 this surface is
// bearer-only and server-to-server; no CORS is intentionally exposed.
//
// Endpoint set covered here is the five operations already implemented
// in the rapidsign service (see internal/handler/handler.go). Reserved
// stubs (cancel, audit) and unimplemented legacy bridges
// (case-restoration, pdf-prefill/render, retrieve, replace-signid) are
// intentionally omitted from v1 until their semantics are finalised —
// they are tracked separately in #38.
//
// Scopes
//
//   - CreateDocument   → rapidsign:documents:write
//   - SignDocument     → rapidsign:documents:sign
//   - GetDocument      → rapidsign:documents:read
//   - DownloadDocument → rapidsign:documents:read
//   - NotifyDocument   → rapidsign:documents:notify

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/rapidsign/v1/documents.proto

package rapidsignv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/isa-sdk/sdk/rapidsign/api/rapidsign/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DocumentsServiceName is the fully-qualified name of the DocumentsService service.
	DocumentsServiceName = "api.rapidsign.v1.DocumentsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DocumentsServiceCreateDocumentProcedure is the fully-qualified name of the DocumentsService's
	// CreateDocument RPC.
	DocumentsServiceCreateDocumentProcedure = "/api.rapidsign.v1.DocumentsService/CreateDocument"
	// DocumentsServiceSignDocumentProcedure is the fully-qualified name of the DocumentsService's
	// SignDocument RPC.
	DocumentsServiceSignDocumentProcedure = "/api.rapidsign.v1.DocumentsService/SignDocument"
	// DocumentsServiceGetDocumentProcedure is the fully-qualified name of the DocumentsService's
	// GetDocument RPC.
	DocumentsServiceGetDocumentProcedure = "/api.rapidsign.v1.DocumentsService/GetDocument"
	// DocumentsServiceDownloadDocumentProcedure is the fully-qualified name of the DocumentsService's
	// DownloadDocument RPC.
	DocumentsServiceDownloadDocumentProcedure = "/api.rapidsign.v1.DocumentsService/DownloadDocument"
	// DocumentsServiceNotifyDocumentProcedure is the fully-qualified name of the DocumentsService's
	// NotifyDocument RPC.
	DocumentsServiceNotifyDocumentProcedure = "/api.rapidsign.v1.DocumentsService/NotifyDocument"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	documentsServiceServiceDescriptor                = v1.File_api_rapidsign_v1_documents_proto.Services().ByName("DocumentsService")
	documentsServiceCreateDocumentMethodDescriptor   = documentsServiceServiceDescriptor.Methods().ByName("CreateDocument")
	documentsServiceSignDocumentMethodDescriptor     = documentsServiceServiceDescriptor.Methods().ByName("SignDocument")
	documentsServiceGetDocumentMethodDescriptor      = documentsServiceServiceDescriptor.Methods().ByName("GetDocument")
	documentsServiceDownloadDocumentMethodDescriptor = documentsServiceServiceDescriptor.Methods().ByName("DownloadDocument")
	documentsServiceNotifyDocumentMethodDescriptor   = documentsServiceServiceDescriptor.Methods().ByName("NotifyDocument")
)

// DocumentsServiceClient is a client for the api.rapidsign.v1.DocumentsService service.
type DocumentsServiceClient interface {
	// CreateDocument renders a PDF packet from the supplied sources,
	// stores it, and prepares the signing artefacts (sign_ids, view-only
	// id, expected hashes). The returned `packet_stored` flag confirms
	// the packet was persisted before signing can begin.
	CreateDocument(context.Context, *connect.Request[v1.CreateDocumentRequest]) (*connect.Response[v1.CreateDocumentResponse], error)
	// SignDocument records a signature against an existing sign_id. The
	// sign_id is path-scoped; session_id binds the signature to the
	// originating session so unrelated sessions cannot overwrite it.
	SignDocument(context.Context, *connect.Request[v1.SignDocumentRequest]) (*connect.Response[v1.SignDocumentResponse], error)
	// GetDocument returns the stored signature state for sign_id (when
	// present). Returns 404 when no signature has been captured yet.
	GetDocument(context.Context, *connect.Request[v1.GetDocumentRequest]) (*connect.Response[v1.GetDocumentResponse], error)
	// DownloadDocument returns the signed PDF as gzipped base64.
	// Returns 404 when no document is stored for sign_id.
	DownloadDocument(context.Context, *connect.Request[v1.DownloadDocumentRequest]) (*connect.Response[v1.DownloadDocumentResponse], error)
	// NotifyDocument dispatches a signer-notification email for sign_id.
	// Accepted (202) when the request is queued; delivery failures
	// surface asynchronously via the emailer's own observability.
	NotifyDocument(context.Context, *connect.Request[v1.NotifyDocumentRequest]) (*connect.Response[v1.NotifyDocumentResponse], error)
}

// NewDocumentsServiceClient constructs a client for the api.rapidsign.v1.DocumentsService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDocumentsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DocumentsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &documentsServiceClient{
		createDocument: connect.NewClient[v1.CreateDocumentRequest, v1.CreateDocumentResponse](
			httpClient,
			baseURL+DocumentsServiceCreateDocumentProcedure,
			connect.WithSchema(documentsServiceCreateDocumentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		signDocument: connect.NewClient[v1.SignDocumentRequest, v1.SignDocumentResponse](
			httpClient,
			baseURL+DocumentsServiceSignDocumentProcedure,
			connect.WithSchema(documentsServiceSignDocumentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getDocument: connect.NewClient[v1.GetDocumentRequest, v1.GetDocumentResponse](
			httpClient,
			baseURL+DocumentsServiceGetDocumentProcedure,
			connect.WithSchema(documentsServiceGetDocumentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		downloadDocument: connect.NewClient[v1.DownloadDocumentRequest, v1.DownloadDocumentResponse](
			httpClient,
			baseURL+DocumentsServiceDownloadDocumentProcedure,
			connect.WithSchema(documentsServiceDownloadDocumentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		notifyDocument: connect.NewClient[v1.NotifyDocumentRequest, v1.NotifyDocumentResponse](
			httpClient,
			baseURL+DocumentsServiceNotifyDocumentProcedure,
			connect.WithSchema(documentsServiceNotifyDocumentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// documentsServiceClient implements DocumentsServiceClient.
type documentsServiceClient struct {
	createDocument   *connect.Client[v1.CreateDocumentRequest, v1.CreateDocumentResponse]
	signDocument     *connect.Client[v1.SignDocumentRequest, v1.SignDocumentResponse]
	getDocument      *connect.Client[v1.GetDocumentRequest, v1.GetDocumentResponse]
	downloadDocument *connect.Client[v1.DownloadDocumentRequest, v1.DownloadDocumentResponse]
	notifyDocument   *connect.Client[v1.NotifyDocumentRequest, v1.NotifyDocumentResponse]
}

// CreateDocument calls api.rapidsign.v1.DocumentsService.CreateDocument.
func (c *documentsServiceClient) CreateDocument(ctx context.Context, req *connect.Request[v1.CreateDocumentRequest]) (*connect.Response[v1.CreateDocumentResponse], error) {
	return c.createDocument.CallUnary(ctx, req)
}

// SignDocument calls api.rapidsign.v1.DocumentsService.SignDocument.
func (c *documentsServiceClient) SignDocument(ctx context.Context, req *connect.Request[v1.SignDocumentRequest]) (*connect.Response[v1.SignDocumentResponse], error) {
	return c.signDocument.CallUnary(ctx, req)
}

// GetDocument calls api.rapidsign.v1.DocumentsService.GetDocument.
func (c *documentsServiceClient) GetDocument(ctx context.Context, req *connect.Request[v1.GetDocumentRequest]) (*connect.Response[v1.GetDocumentResponse], error) {
	return c.getDocument.CallUnary(ctx, req)
}

// DownloadDocument calls api.rapidsign.v1.DocumentsService.DownloadDocument.
func (c *documentsServiceClient) DownloadDocument(ctx context.Context, req *connect.Request[v1.DownloadDocumentRequest]) (*connect.Response[v1.DownloadDocumentResponse], error) {
	return c.downloadDocument.CallUnary(ctx, req)
}

// NotifyDocument calls api.rapidsign.v1.DocumentsService.NotifyDocument.
func (c *documentsServiceClient) NotifyDocument(ctx context.Context, req *connect.Request[v1.NotifyDocumentRequest]) (*connect.Response[v1.NotifyDocumentResponse], error) {
	return c.notifyDocument.CallUnary(ctx, req)
}

// DocumentsServiceHandler is an implementation of the api.rapidsign.v1.DocumentsService service.
type DocumentsServiceHandler interface {
	// CreateDocument renders a PDF packet from the supplied sources,
	// stores it, and prepares the signing artefacts (sign_ids, view-only
	// id, expected hashes). The returned `packet_stored` flag confirms
	// the packet was persisted before signing can begin.
	CreateDocument(context.Context, *connect.Request[v1.CreateDocumentRequest]) (*connect.Response[v1.CreateDocumentResponse], error)
	// SignDocument records a signature against an existing sign_id. The
	// sign_id is path-scoped; session_id binds the signature to the
	// originating session so unrelated sessions cannot overwrite it.
	SignDocument(context.Context, *connect.Request[v1.SignDocumentRequest]) (*connect.Response[v1.SignDocumentResponse], error)
	// GetDocument returns the stored signature state for sign_id (when
	// present). Returns 404 when no signature has been captured yet.
	GetDocument(context.Context, *connect.Request[v1.GetDocumentRequest]) (*connect.Response[v1.GetDocumentResponse], error)
	// DownloadDocument returns the signed PDF as gzipped base64.
	// Returns 404 when no document is stored for sign_id.
	DownloadDocument(context.Context, *connect.Request[v1.DownloadDocumentRequest]) (*connect.Response[v1.DownloadDocumentResponse], error)
	// NotifyDocument dispatches a signer-notification email for sign_id.
	// Accepted (202) when the request is queued; delivery failures
	// surface asynchronously via the emailer's own observability.
	NotifyDocument(context.Context, *connect.Request[v1.NotifyDocumentRequest]) (*connect.Response[v1.NotifyDocumentResponse], error)
}

// NewDocumentsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDocumentsServiceHandler(svc DocumentsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	documentsServiceCreateDocumentHandler := connect.NewUnaryHandler(
		DocumentsServiceCreateDocumentProcedure,
		svc.CreateDocument,
		connect.WithSchema(documentsServiceCreateDocumentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	documentsServiceSignDocumentHandler := connect.NewUnaryHandler(
		DocumentsServiceSignDocumentProcedure,
		svc.SignDocument,
		connect.WithSchema(documentsServiceSignDocumentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	documentsServiceGetDocumentHandler := connect.NewUnaryHandler(
		DocumentsServiceGetDocumentProcedure,
		svc.GetDocument,
		connect.WithSchema(documentsServiceGetDocumentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	documentsServiceDownloadDocumentHandler := connect.NewUnaryHandler(
		DocumentsServiceDownloadDocumentProcedure,
		svc.DownloadDocument,
		connect.WithSchema(documentsServiceDownloadDocumentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	documentsServiceNotifyDocumentHandler := connect.NewUnaryHandler(
		DocumentsServiceNotifyDocumentProcedure,
		svc.NotifyDocument,
		connect.WithSchema(documentsServiceNotifyDocumentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.rapidsign.v1.DocumentsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DocumentsServiceCreateDocumentProcedure:
			documentsServiceCreateDocumentHandler.ServeHTTP(w, r)
		case DocumentsServiceSignDocumentProcedure:
			documentsServiceSignDocumentHandler.ServeHTTP(w, r)
		case DocumentsServiceGetDocumentProcedure:
			documentsServiceGetDocumentHandler.ServeHTTP(w, r)
		case DocumentsServiceDownloadDocumentProcedure:
			documentsServiceDownloadDocumentHandler.ServeHTTP(w, r)
		case DocumentsServiceNotifyDocumentProcedure:
			documentsServiceNotifyDocumentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDocumentsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDocumentsServiceHandler struct{}

func (UnimplementedDocumentsServiceHandler) CreateDocument(context.Context, *connect.Request[v1.CreateDocumentRequest]) (*connect.Response[v1.CreateDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.rapidsign.v1.DocumentsService.CreateDocument is not implemented"))
}

func (UnimplementedDocumentsServiceHandler) SignDocument(context.Context, *connect.Request[v1.SignDocumentRequest]) (*connect.Response[v1.SignDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.rapidsign.v1.DocumentsService.SignDocument is not implemented"))
}

func (UnimplementedDocumentsServiceHandler) GetDocument(context.Context, *connect.Request[v1.GetDocumentRequest]) (*connect.Response[v1.GetDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.rapidsign.v1.DocumentsService.GetDocument is not implemented"))
}

func (UnimplementedDocumentsServiceHandler) DownloadDocument(context.Context, *connect.Request[v1.DownloadDocumentRequest]) (*connect.Response[v1.DownloadDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.rapidsign.v1.DocumentsService.DownloadDocument is not implemented"))
}

func (UnimplementedDocumentsServiceHandler) NotifyDocument(context.Context, *connect.Request[v1.NotifyDocumentRequest]) (*connect.Response[v1.NotifyDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.rapidsign.v1.DocumentsService.NotifyDocument is not implemented"))
}
