// health.proto defines the shared observability surface every ISA
// platform service exposes: a liveness probe (`/health`) and a
// readiness probe (`/ready`).
//
// The liveness probe reports in-process state only. It MUST NOT touch
// the database, the cache, or any network dependency; a failure means
// the process should be restarted.
//
// The readiness probe reports whether the service can serve real
// traffic right now. The shared ReadinessResponse below carries the
// canonical two typed probes (fields 3–4), a keyed map for additional
// downstream checks (field 5), and the evaluation timestamp (field 6).
// Service-specific handlers populate the typed slots with whichever
// dependencies they probe; wire numbers stay stable across products.
//
// Both endpoints return HTTP 200 with a typed response body when
// healthy. A failing liveness or readiness check returns HTTP 503 with
// a ProblemDetails body (see common.proto).

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/isa/v1/health.proto

package isav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/isa-sdk/sdk/core/api/isa/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HealthServiceName is the fully-qualified name of the HealthService service.
	HealthServiceName = "api.isa.v1.HealthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthServiceGetHealthProcedure is the fully-qualified name of the HealthService's GetHealth RPC.
	HealthServiceGetHealthProcedure = "/api.isa.v1.HealthService/GetHealth"
	// HealthServiceGetReadinessProcedure is the fully-qualified name of the HealthService's
	// GetReadiness RPC.
	HealthServiceGetReadinessProcedure = "/api.isa.v1.HealthService/GetReadiness"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	healthServiceServiceDescriptor            = v1.File_api_isa_v1_health_proto.Services().ByName("HealthService")
	healthServiceGetHealthMethodDescriptor    = healthServiceServiceDescriptor.Methods().ByName("GetHealth")
	healthServiceGetReadinessMethodDescriptor = healthServiceServiceDescriptor.Methods().ByName("GetReadiness")
)

// HealthServiceClient is a client for the api.isa.v1.HealthService service.
type HealthServiceClient interface {
	// GetHealth is the liveness probe. Verifies in-process state only
	// (binary loaded, request loop running). Does NOT touch the database,
	// the cache, or any downstream dependency. A 503 here means the
	// process should be restarted.
	GetHealth(context.Context, *connect.Request[v1.GetHealthRequest]) (*connect.Response[v1.HealthResponse], error)
	// GetReadiness is the readiness probe. Exercises every dependency
	// required to serve a real user request. A 503 here drains traffic
	// without restarting the task. Implementations populate the shared
	// ReadinessResponse fields defined in this package.
	GetReadiness(context.Context, *connect.Request[v1.GetReadinessRequest]) (*connect.Response[v1.ReadinessResponse], error)
}

// NewHealthServiceClient constructs a client for the api.isa.v1.HealthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &healthServiceClient{
		getHealth: connect.NewClient[v1.GetHealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+HealthServiceGetHealthProcedure,
			connect.WithSchema(healthServiceGetHealthMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getReadiness: connect.NewClient[v1.GetReadinessRequest, v1.ReadinessResponse](
			httpClient,
			baseURL+HealthServiceGetReadinessProcedure,
			connect.WithSchema(healthServiceGetReadinessMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthServiceClient implements HealthServiceClient.
type healthServiceClient struct {
	getHealth    *connect.Client[v1.GetHealthRequest, v1.HealthResponse]
	getReadiness *connect.Client[v1.GetReadinessRequest, v1.ReadinessResponse]
}

// GetHealth calls api.isa.v1.HealthService.GetHealth.
func (c *healthServiceClient) GetHealth(ctx context.Context, req *connect.Request[v1.GetHealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return c.getHealth.CallUnary(ctx, req)
}

// GetReadiness calls api.isa.v1.HealthService.GetReadiness.
func (c *healthServiceClient) GetReadiness(ctx context.Context, req *connect.Request[v1.GetReadinessRequest]) (*connect.Response[v1.ReadinessResponse], error) {
	return c.getReadiness.CallUnary(ctx, req)
}

// HealthServiceHandler is an implementation of the api.isa.v1.HealthService service.
type HealthServiceHandler interface {
	// GetHealth is the liveness probe. Verifies in-process state only
	// (binary loaded, request loop running). Does NOT touch the database,
	// the cache, or any downstream dependency. A 503 here means the
	// process should be restarted.
	GetHealth(context.Context, *connect.Request[v1.GetHealthRequest]) (*connect.Response[v1.HealthResponse], error)
	// GetReadiness is the readiness probe. Exercises every dependency
	// required to serve a real user request. A 503 here drains traffic
	// without restarting the task. Implementations populate the shared
	// ReadinessResponse fields defined in this package.
	GetReadiness(context.Context, *connect.Request[v1.GetReadinessRequest]) (*connect.Response[v1.ReadinessResponse], error)
}

// NewHealthServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthServiceHandler(svc HealthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthServiceGetHealthHandler := connect.NewUnaryHandler(
		HealthServiceGetHealthProcedure,
		svc.GetHealth,
		connect.WithSchema(healthServiceGetHealthMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceGetReadinessHandler := connect.NewUnaryHandler(
		HealthServiceGetReadinessProcedure,
		svc.GetReadiness,
		connect.WithSchema(healthServiceGetReadinessMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.isa.v1.HealthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthServiceGetHealthProcedure:
			healthServiceGetHealthHandler.ServeHTTP(w, r)
		case HealthServiceGetReadinessProcedure:
			healthServiceGetReadinessHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthServiceHandler struct{}

func (UnimplementedHealthServiceHandler) GetHealth(context.Context, *connect.Request[v1.GetHealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.isa.v1.HealthService.GetHealth is not implemented"))
}

func (UnimplementedHealthServiceHandler) GetReadiness(context.Context, *connect.Request[v1.GetReadinessRequest]) (*connect.Response[v1.ReadinessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.isa.v1.HealthService.GetReadiness is not implemented"))
}
